  Object.assign(MOTS, {
    // ---------------- Français ----------------
    "fr-dictee": [["Participe passé", "Forme du verbe utilisée avec un auxiliaire (être ou avoir) ou comme adjectif.", "« mangé », « partie », « écrites »."],
      ["COD (complément d'objet direct)", "Complément du verbe sans préposition ; il répond à « quoi ? » ou « qui ? ».", "« J'ai cueilli <b>les mangues</b>. »"],
      ["Homophones", "Mots qui se prononcent pareil mais s'écrivent différemment.", "a / à, on / ont, ces / ses."],
      ["Accord", "Changement de forme d'un mot selon le genre et le nombre du mot auquel il se rapporte.", "« des robes blanches »."]],
    "fr-communication": [["Émetteur", "Celui qui envoie le message.", "Le proviseur qui écrit aux parents."],
      ["Récepteur", "Celui qui reçoit le message.", "Les parents qui lisent la note."],
      ["Registre de langue", "Manière de parler adaptée à la situation : soutenu, courant ou familier.", "« Je suis épuisé » (soutenu), « je suis fatigué » (courant), « je suis crevé » (familier)."],
      ["Modalité de phrase", "Type de phrase selon l'intention : déclarative, interrogative, injonctive, exclamative.", "« Ferme la porte ! » est injonctive."]],
    "fr-pronoms": [["Pronom", "Mot qui remplace un nom ou un groupe nominal.", "« Awa lit. <b>Elle</b> aime lire. »"],
      ["Pronominalisation", "Remplacement d'un groupe de mots par un pronom pour éviter les répétitions.", "« Je donne le livre à Koffi » → « Je <b>le lui</b> donne. »"],
      ["Pronom relatif", "Pronom qui relie une proposition à un nom : qui, que, dont, où, lequel.", "« Le village <b>où</b> je suis né. »"],
      ["Antécédent", "Nom que remplace le pronom relatif.", "Dans « le livre que je lis », l'antécédent est « livre »."]],
    "fr-adverbe": [["Adverbe", "Mot invariable qui modifie le sens d'un verbe, d'un adjectif ou d'un autre adverbe.", "« Il court <b>vite</b>. »"],
      ["Locution adverbiale", "Groupe de mots qui joue le rôle d'un adverbe.", "« tout à fait », « peu à peu »."],
      ["Degré de l'adverbe", "Variation d'intensité : comparatif ou superlatif.", "« plus vite », « le plus vite »."],
      ["Invariable", "Qui ne change jamais de forme.", "« Elles parlent doucement » (pas de s à doucement)."]],
    "fr-infinitif": [["Infinitif", "Forme du verbe non conjuguée, qui sert de nom au verbe.", "« chanter », « finir », « prendre »."],
      ["Participe présent", "Forme en -ant, invariable, qui exprime une action.", "« Des élèves <b>obéissant</b> à leur maître. »"],
      ["Adjectif verbal", "Adjectif formé sur un verbe, qui s'accorde et exprime une qualité.", "« Des élèves <b>obéissants</b>. »"],
      ["Gérondif", "En + participe présent : il exprime la manière ou le temps.", "« Il révise <b>en écoutant</b> de la musique. »"]],
    "fr-coordination": [["Coordination", "Liaison de deux éléments de même fonction par une conjonction de coordination.", "« Il est fatigué <b>mais</b> il travaille. »"],
      ["Conjonction de coordination", "Mot invariable qui relie : mais, ou, et, donc, or, ni, car.", "« Il pleut, <b>donc</b> je reste. »"],
      ["Connecteur logique", "Mot qui marque le lien entre deux idées (cause, conséquence, opposition…).", "cependant, en effet, ainsi."],
      ["Proposition indépendante", "Proposition qui a un sens complet toute seule.", "« Je mange » ; « tu dors »."]],
    "fr-circonstances": [["Proposition subordonnée", "Proposition qui dépend d'une autre (la principale) et commence par un subordonnant.", "« Je reste <b>parce qu'il pleut</b>. »"],
      ["Circonstance", "Information sur la cause, le but, le temps, la condition, l'opposition…", "« <b>Pour réussir</b>, il travaille » (but)."],
      ["Subordonnant", "Mot qui introduit une subordonnée.", "parce que, afin que, bien que, quand, si."],
      ["Concession", "Idée qu'on reconnaît avant d'affirmer le contraire.", "« <b>Bien qu'il</b> soit fatigué, il vient. »"]],
    "fr-ortho-lexicale": [["Homophones", "Mots qui se prononcent pareil mais s'écrivent différemment.", "sans / s'en / sang ; peu / peut."],
      ["Paronymes", "Mots presque identiques par la forme mais de sens différent.", "« éminent » (remarquable) et « imminent » (tout proche)."],
      ["Orthographe lexicale", "Orthographe des mots eux-mêmes, telle qu'elle est dans le dictionnaire.", "On écrit « fatigant » (adjectif) sans u."],
      ["Quel que / quelque", "« Quel que » + verbe être (accordé) ; « quelque » devant un nom (= un certain, plusieurs).", "« Quelles que soient tes difficultés » ; « quelques livres »."]],
    "fr-ortho-grammaticale": [["Orthographe grammaticale", "Orthographe des accords (verbe, adjectif, participe…).", "« Les filles sont arrivées. »"],
      ["Auxiliaire", "Verbe être ou avoir qui sert à conjuguer aux temps composés.", "« Il <b>a</b> mangé », « elle <b>est</b> partie »."],
      ["Adverbe « tout »", "Invariable (= très, entièrement), sauf devant un adjectif féminin commençant par une consonne.", "« Ils sont tout contents » ; « elle est toute contente »."],
      ["Adjectif qualificatif", "Mot qui donne une qualité au nom et s'accorde avec lui.", "« une robe <b>blanche</b> »."]],
    "fr-methodes": [["Texte argumentatif", "Texte qui cherche à convaincre en défendant une opinion par des arguments.", "Un article pour ou contre le téléphone à l'école."],
      ["Résumé", "Texte plus court qui garde toutes les idées essentielles, dans l'ordre, avec ses propres mots.", "Un texte de 240 mots résumé en 60 mots."],
      ["Article de journal", "Texte qui informe sur un fait réel et récent.", "Un article sur la journée de salubrité du lycée."],
      ["Plan", "Organisation des idées d'un texte en parties.", "Introduction, développement, conclusion."]],
    "fr-argu-atelier": [["Thèse", "L'opinion que l'auteur défend.", "« L'uniforme scolaire devrait être obligatoire. »"],
      ["Argument", "Idée qui prouve ou justifie la thèse.", "« L'uniforme évite les inégalités entre élèves. »"],
      ["Exemple", "Cas précis et réel qui illustre un argument.", "« Au lycée de Daloa, depuis l'uniforme, plus personne ne se moque des vêtements des autres. »"],
      ["Étayer", "Soutenir une thèse avec des arguments et des exemples.", "Défendre l'idée qu'il faut lire tous les jours."],
      ["Réfuter", "Montrer qu'une opinion est fausse ou exagérée, avec des arguments.", "Répondre à « L'école ne sert à rien » en montrant qu'elle ouvre l'accès aux métiers."],
      ["Connecteur", "Mot qui relie les idées et montre leur lien logique.", "d'abord, en effet, par exemple, cependant, donc."]],
    "fr-resume-atelier": [["Résumer", "Réduire un texte en gardant ses idées essentielles, dans l'ordre, avec ses mots.", "Réduire un texte de 200 mots à 50 mots."],
      ["Reformuler", "Dire la même idée avec d'autres mots, plus courts.", "« l'élève est plus détendu et plus attentif en classe » → « il favorise l'attention »."],
      ["Idée essentielle", "Idée indispensable pour comprendre le texte : thèse, arguments, conclusion.", "« Le sport entretient la santé. »"],
      ["Système d'énonciation", "Qui parle dans le texte (je, nous, on) : le résumé le garde.", "Si l'auteur dit « nous », le résumé dit aussi « nous »."]],
    "fr-article-atelier": [["Chapeau", "Court texte sous le titre qui résume l'essentiel de l'article.", "« Samedi, 300 élèves ont nettoyé leur école. Objectif : un cadre sain. »"],
      ["Attaque", "Première phrase de l'article, qui accroche le lecteur.", "« Dès 7 heures, balais en main, les élèves étaient au rendez-vous. »"],
      ["Chute", "Fin de l'article, qui ouvre sur la suite.", "« Rendez-vous est déjà pris pour le mois prochain. »"],
      ["Citation", "Paroles exactes d'une personne, placées entre guillemets.", "« Chaque élève est responsable d'un arbre », explique le proviseur."]],
    // ---------------- Anglais ----------------
    "en-oral-bepc": [["Describe", "Décrire : dire ce que l'on voit, avec des détails.", "« In the picture, I can see a market. »"],
      ["Foreground / background", "Premier plan (devant) / arrière-plan (au fond) d'une image.", "« In the background, there are houses. »"],
      ["Present continuous", "Temps utilisé pour décrire une action en cours : be + V-ing.", "« A woman is selling mangoes. »"],
      ["Summary", "Résumé : dire l'essentiel d'un texte avec ses mots.", "« This text is about malaria. »"]],
    "en-present": [["Present simple", "Temps des habitudes et des vérités générales.", "« I go to school every day. »"],
      ["Present continuous", "Temps des actions en cours : be + V-ing.", "« Look! They are playing football. »"],
      ["Third person", "He, she, it : au present simple, le verbe prend un -s.", "« She lives in Man. »"],
      ["Auxiliary do / does", "Mot qui sert à faire les questions et les négations au present simple.", "« Does he work? — No, he doesn't. »"]],
    "en-past": [["Past simple", "Temps d'une action terminée dans le passé.", "« We went to Bassam yesterday. »"],
      ["Regular verb", "Verbe qui fait son passé en -ed.", "play → played."],
      ["Irregular verb", "Verbe dont le passé est une forme à apprendre par cœur.", "go → went → gone."],
      ["Past continuous", "Action en cours dans le passé : was / were + V-ing.", "« I was reading when he arrived. »"]],
    "en-perfect": [["Present perfect", "Temps qui relie le passé au présent : have / has + participe passé.", "« I have finished my homework. »"],
      ["Past participle", "Troisième forme du verbe, utilisée avec have.", "write → wrote → <b>written</b>."],
      ["For", "« Depuis » suivi d'une durée.", "« for three years »."],
      ["Since", "« Depuis » suivi d'un point de départ.", "« since 2020 »."]],
    "en-future": [["Will", "Auxiliaire du futur : décision spontanée ou prédiction.", "« I will help you. »"],
      ["Be going to", "Futur proche ou projet déjà décidé.", "« I am going to study medicine. »"],
      ["Conditional", "Phrase avec « if » qui exprime une condition.", "« If you work, you will pass. »"],
      ["If-clause", "Partie de la phrase qui commence par « if » ; jamais de « will » dedans (type 1).", "« If it rains, we will stay home. »"]],
    "en-modals": [["Modal verb", "Verbe (can, must, should, may…) qui exprime capacité, obligation, conseil ou possibilité.", "« You should rest. »"],
      ["Obligation", "Ce qu'on est obligé de faire : must / have to.", "« Pupils must wear a uniform. »"],
      ["Prohibition", "Interdiction : mustn't.", "« You mustn't smoke here. »"],
      ["Advice", "Conseil : should.", "« You should sleep early. »"]],
    "en-compare": [["Comparative", "Forme pour comparer deux éléments : -er than / more … than.", "« Abidjan is bigger than Bouaké. »"],
      ["Superlative", "Forme pour dire « le plus » : the -est / the most.", "« the highest mountain »."],
      ["Short adjective", "Adjectif d'une syllabe (ou deux terminées par -y) : on ajoute -er / -est.", "tall → taller → the tallest."],
      ["Long adjective", "Adjectif de deux syllabes ou plus : more / the most.", "difficult → more difficult."]],
    "en-passive": [["Passive voice", "Tournure où le sujet subit l'action : be + participe passé.", "« Cocoa is grown in Côte d'Ivoire. »"],
      ["Active voice", "Tournure où le sujet fait l'action.", "« Farmers grow cocoa. »"],
      ["Reported speech", "Discours rapporté : on répète ce que quelqu'un a dit, en changeant les temps.", "He said: « I am tired » → He said he was tired."],
      ["Agent", "Celui qui fait l'action dans une phrase passive, introduit par « by ».", "« The window was broken <b>by the boy</b>. »"]],
    "en-relatives": [["Relative pronoun", "Pronom qui relie une proposition à un nom : who, which, whose, where.", "« The man who lives here. »"],
      ["Question tag", "Petite question à la fin d'une phrase pour demander confirmation.", "« You like football, <b>don't you</b>? »"],
      ["Linking word", "Mot de liaison entre deux idées.", "because, but, so, although, however."],
      ["Whose", "Pronom relatif de la possession.", "« The girl whose father is a doctor. »"]],
    "en-oral": [["Greeting", "Salutation.", "« Good morning, sir. »"],
      ["Introduce yourself", "Se présenter.", "« My name is Adriel. I am in form three. »"],
      ["Opinion", "Avis personnel.", "« In my opinion, sport is important. »"],
      ["Polite request", "Demande polie.", "« Could you repeat, please? »"]],
    // ---------------- Espagnol ----------------
    "es-presentarse": [["Saludo", "Salutation.", "¡Buenos días!"],
      ["Presentarse", "Se présenter.", "Me llamo Adriel y tengo quince años."],
      ["Nacionalidad", "Nationalité.", "Soy marfileño."],
      ["Edad", "Âge : on l'exprime avec « tener ».", "Tengo quince años."]],
    "es-ser-estar": [["Ser", "Verbe « être » pour l'identité, la nationalité, la profession, le caractère.", "Soy alumno. Es alto."],
      ["Estar", "Verbe « être » pour le lieu et les états passagers.", "Estoy en casa. Estoy cansado."],
      ["Gerundio", "Forme en -ando / -iendo ; avec estar, action en cours.", "Estoy estudiando."],
      ["Estado", "État (passager).", "Mi madre está enferma hoy."]],
    "es-presente": [["Presente", "Temps des actions actuelles et des habitudes.", "Como arroz todos los días."],
      ["Verbo regular", "Verbe qui suit les terminaisons habituelles (-ar, -er, -ir).", "hablar → hablo."],
      ["Verbo irregular", "Verbe qui change de forme.", "tener → tengo ; ir → voy."],
      ["Diptongo", "Changement de voyelle dans le radical : e → ie, o → ue.", "querer → quiero ; poder → puedo."]],
    "es-gustar": [["Gustar", "Plaire : sert à dire ce qu'on aime.", "Me gusta el fútbol."],
      ["Encantar", "Adorer.", "Me encantan los mangos."],
      ["Preferir", "Préférer (e → ie).", "Prefiero el arroz."],
      ["Pronombre (me, te, le…)", "Pronom qui indique à qui la chose plaît.", "A mi hermano <b>le</b> gusta leer."]],
    "es-pasado": [["Pretérito indefinido", "Passé simple espagnol : action terminée dans le passé.", "Ayer hablé con mi abuela."],
      ["Ayer", "Hier : mot qui annonce souvent le passé.", "Ayer fui al mercado."],
      ["Fui", "Passé de « ser » et de « ir » à la 1re personne.", "Fui a Man el año pasado."],
      ["Hice", "Passé de « hacer » (je fis).", "Hice mis deberes."]],
    "es-futuro": [["Futuro", "Temps des actions à venir : infinitif + é, ás, á…", "Pasaré el BEPC."],
      ["Ir a + infinitivo", "Futur proche.", "Voy a estudiar."],
      ["Proyecto", "Projet.", "Quiero ser médico."],
      ["Mañana", "Demain (ou matin).", "Mañana voy al colegio."]],
    // ---------------- Arts et musique ----------------
    "art-couleurs": [["Couleur primaire", "Couleur qu'on ne peut pas obtenir par mélange.", "Le rouge, le jaune, le bleu."],
      ["Couleur secondaire", "Couleur obtenue en mélangeant deux primaires.", "Jaune + bleu = vert."],
      ["Couleurs complémentaires", "Une primaire et la secondaire faite des deux autres ; elles se renforcent côte à côte.", "Le rouge et le vert."],
      ["Camaïeu", "Peinture en plusieurs nuances d'une seule couleur.", "Un paysage peint seulement en bleus."]],
    "art-dessin": [["Perspective", "Technique qui donne l'illusion de la profondeur sur une surface plate.", "Une route qui rétrécit vers l'horizon."],
      ["Point de fuite", "Point où se rejoignent les lignes qui s'éloignent.", "Le bout de la route au loin."],
      ["Ligne d'horizon", "Ligne à hauteur des yeux où le ciel semble toucher la terre.", "La limite entre la mer et le ciel à Bassam."],
      ["Composition", "Organisation des éléments dans une image.", "Placer le personnage principal au premier plan."]],
    "art-patrimoine": [["Patrimoine", "Ensemble des biens culturels hérités des ancêtres.", "Les masques, les pagnes, les danses traditionnelles."],
      ["Masque", "Objet rituel qui cache le visage, utilisé lors de cérémonies.", "Les masques dan de la région de Man."],
      ["Tissage", "Fabrication d'un tissu en entrecroisant des fils.", "Le pagne Kita des Baoulé."],
      ["Artisanat", "Production d'objets faits à la main.", "La poterie de Katiola."]],
    "mus-solfege": [["Portée", "Ensemble de 5 lignes sur lesquelles on écrit les notes.", "Les notes do, ré, mi… sont placées sur la portée."],
      ["Clé de sol", "Signe placé au début de la portée qui fixe le nom des notes.", "Le sol se trouve sur la 2e ligne."],
      ["Mesure", "Groupe de temps séparé par des barres.", "Une mesure à 4 temps."],
      ["Tempo", "Vitesse d'exécution d'un morceau.", "Allegro (rapide), adagio (lent)."]],
    "mus-instruments": [["Instrument à cordes", "Instrument dont on fait vibrer des cordes.", "La kora, la guitare."],
      ["Instrument à vent", "Instrument dans lequel on souffle.", "La flûte, la trompette."],
      ["Percussion", "Instrument qu'on frappe.", "Le djembé, le balafon, le tam-tam."],
      ["Tambour parleur", "Tambour qui imite les sons de la langue pour transmettre des messages.", "L'attoungblan des Akan."]],
    // ---------------- EPS ----------------
    "eps-sante": [["Échauffement", "Exercices progressifs qui préparent le corps à l'effort.", "Trottiner, mobiliser les articulations, s'étirer."],
      ["Hydratation", "Fait de boire assez d'eau.", "Boire avant, pendant et après l'effort."],
      ["Récupération", "Retour au calme après l'effort.", "Marcher, s'étirer doucement."],
      ["Endurance", "Capacité à faire un effort longtemps.", "Courir 20 minutes sans s'arrêter."]],
    "eps-courses": [["Sprint", "Course de vitesse sur une courte distance.", "Le 80 m ou le 100 m."],
      ["Demi-fond", "Course de distance moyenne (souvent 800 m à 1 500 m).", "Le 1 000 m."],
      ["Faux départ", "Départ avant le signal.", "Il peut entraîner l'élimination."],
      ["Témoin", "Bâton que les coureurs d'un relais se passent.", "Il doit être transmis dans la zone de transmission."]],
    "eps-sauts-lancers": [["Appel", "Impulsion donnée par un pied pour sauter.", "La planche d'appel au saut en longueur."],
      ["Course d'élan", "Course avant le saut ou le lancer, pour prendre de la vitesse.", "8 à 12 foulées en longueur."],
      ["Essai nul", "Essai qui ne compte pas.", "Mordre la planche au saut en longueur."],
      ["Butoir", "Pièce à l'avant du cercle de lancer qu'on ne doit pas dépasser.", "Au lancer de poids."]],
    "eps-sports-co": [["Sport collectif", "Sport qui se pratique en équipe.", "Football, handball, basket, volley."],
      ["Fair-play", "Respect des règles, de l'adversaire et de l'arbitre.", "Serrer la main de l'adversaire après le match."],
      ["Arbitre", "Personne qui fait respecter les règles du jeu.", "Il siffle les fautes."],
      ["Hors-jeu", "Au football, position interdite d'un attaquant au moment de la passe.", "L'arbitre assistant lève son drapeau."]]
  });
