  // Traductions complètes en français (bouton « Voir la traduction »)
  const TRAD = {
    "img:marche": "Sur cette image, je vois un marché. Au milieu, il y a une vendeuse derrière son étal. Elle vend des fruits et des légumes : des mangues, des bananes et des tomates. Au-dessus de l'étal, il y a un grand parasol rouge et jaune pour la protéger du soleil. À droite, une cliente tient un panier. Je pense qu'elle achète des mangues. À gauche, un garçon porte un sac rouge. C'est une journée ensoleillée. En Côte d'Ivoire, beaucoup de gens achètent des produits frais au marché tous les jours.",
    "img:classe": "Cette image montre une salle de classe. À gauche, il y a un tableau noir. Sur le tableau, le professeur a écrit « English » et la date : lundi 12 mai. Le professeur est debout à côté du tableau et il le montre du doigt. Devant lui, il y a trois élèves assis à leur table. Ils portent des chemises bleues : c'est leur uniforme scolaire. L'élève du milieu lève la main parce qu'il veut répondre à une question. À droite, il y a une fenêtre. Je pense que c'est un cours d'anglais.",
    "img:repas": "Sur cette image, je vois une famille qui prend un repas ensemble. Il y a quatre personnes : le père, la mère et leurs deux enfants. Ils sont assis autour d'une table. Au milieu de la table, il y a un grand plat de riz avec de la sauce. Il y a aussi une carafe d'eau et des assiettes. La mère sert la nourriture et les enfants mangent. Derrière eux, au mur, il y a un tableau. Ils ont l'air heureux. En Afrique, manger ensemble est important parce que la famille partage le repas et discute.",
    "img:foot": "Cette image montre un match de football. Les joueurs en orange et blanc sont des joueurs ivoiriens, peut-être les Éléphants. Au milieu, un joueur en orange court avec le ballon vers le but. Il va tirer. Devant lui, un joueur en blanc essaie de l'arrêter. À gauche, un autre joueur ivoirien lève les bras. À droite, le gardien de but en vert est prêt à attraper le ballon. À gauche, l'arbitre en noir lève le bras. En haut, beaucoup de supporters regardent le match. J'aime le football parce que c'est un sport d'équipe. En 2026, les Éléphants ont très bien joué à la Coupe du monde.",
    "img:sante": "Sur cette image, je vois un centre de santé. Sur le bâtiment, on peut lire « Centre de santé » et il y a une croix rouge. À droite, une infirmière en uniforme blanc parle à une mère. La mère tient son bébé dans ses bras. Je pense que l'infirmière va vacciner le bébé, peut-être contre le paludisme. À gauche, trois personnes sont assises sur un banc : elles attendent leur tour. Au mur, il y a une affiche : « Dors sous une moustiquaire ! ». Cette image montre que la santé est importante et que nous devons aller au centre de santé quand nous sommes malades.",
    "img:proprete": "Cette image montre une journée de nettoyage dans un quartier. En haut, il y a une banderole : « Journée de nettoyage ». Je vois trois jeunes qui portent des T-shirts jaunes : ce sont des bénévoles. Le garçon à gauche ramasse des déchets et les met dans un sac noir. La fille du milieu balaie la rue avec un balai. À gauche, il y a une poubelle verte. Dans le caniveau, il y a des bouteilles et des sacs en plastique. Ces jeunes nettoient leur quartier pour éviter les inondations et les maladies comme le paludisme. Je pense que c'est un très bon exemple de citoyenneté.",
    "img:cacao": "Sur cette image, je vois une plantation de cacao. Il y a deux cacaoyers avec des cabosses jaunes et orange sur leur tronc. À gauche, un planteur récolte les cabosses avec une machette. Au milieu, une femme porte sur la tête un panier plein de cabosses. Il y a aussi des cabosses par terre. La Côte d'Ivoire est le premier producteur de cacao du monde, donc cette image est très typique de notre pays. Mais en 2026, le prix payé aux planteurs est descendu à 1 200 francs le kilo, alors les planteurs sont inquiets.",
    "img:inondation": "Cette image montre une inondation dans une ville. Il pleut très fort et il y a des nuages sombres dans le ciel. La rue est couverte d'eau. Au milieu, une voiture rouge est à moitié sous l'eau. À droite, un homme marche dans l'eau ; il porte un enfant sur ses épaules pour le protéger. À l'arrière-plan, il y a des maisons et un immeuble. Cette situation est très dangereuse. En juin 2026, de fortes pluies ont provoqué des inondations à Abidjan et beaucoup de personnes sont mortes. Pour éviter les inondations, nous ne devons pas jeter de déchets dans les caniveaux et nous ne devons pas construire dans les zones dangereuses.",
    "txt:awa": "Awa a quatorze ans. Elle habite à Daloa avec ses parents et ses deux frères. Elle est en 3e au Lycée Moderne. Chaque matin, elle se lève à cinq heures et demie, balaie la cour et prend un petit-déjeuner rapide. Ensuite, elle va à l'école à pied avec ses amies. Sa matière préférée est l'anglais parce que son professeur est très gentil. Après l'école, elle aide sa mère au marché. Le soir, elle fait ses devoirs sous la lampe. Awa veut devenir médecin pour aider les gens de sa ville.",
    "res:awa": "Ce texte parle d'Awa, une fille de quatorze ans qui vient de Daloa. Elle est en 3e. Elle se lève très tôt, balaie la cour et va à l'école à pied. Elle aime l'anglais parce que son professeur est gentil. Après l'école, elle aide sa mère au marché et le soir elle fait ses devoirs. Elle veut devenir médecin pour aider les gens.",
    "txt:pluie": "En Côte d'Ivoire, la grande saison des pluies commence en mai et se termine en juillet. Pendant cette période, il pleut presque tous les jours. La pluie est bonne pour les agriculteurs parce que leurs plantes ont besoin d'eau. Mais dans les grandes villes comme Abidjan, les fortes pluies peuvent provoquer des inondations. En juin 2026, des inondations et des glissements de terrain ont tué beaucoup de personnes. Certaines maisons avaient été construites dans des zones dangereuses, et les caniveaux étaient pleins d'ordures. Le gouvernement demande aux gens de ne pas jeter de déchets dans les caniveaux et de quitter les zones dangereuses pendant la saison des pluies.",
    "res:pluie": "Le texte parle de la saison des pluies en Côte d'Ivoire, de mai à juillet. La pluie est utile aux agriculteurs, mais dans les villes comme Abidjan elle peut provoquer des inondations. En juin 2026, des inondations ont tué beaucoup de personnes parce que certaines maisons étaient dans des zones dangereuses et que les caniveaux étaient bouchés par les ordures. Le gouvernement demande aux gens de garder les caniveaux propres et de quitter les zones dangereuses.",
    "txt:lettre": "Cher Kofi, merci pour ta dernière lettre. Je suis content(e) d'apprendre que tu as réussi tes examens. Ici à Accra, les vacances ont commencé. Le week-end dernier, j'ai rendu visite à mes grands-parents dans leur village. Mon grand-père a une grande plantation de cacao et de bananes plantain. Je l'ai aidé dans la plantation et le soir il nous a raconté de vieilles histoires. Le mois prochain, ma famille va visiter Abidjan et j'espère que nous pourrons nous voir. Parle-moi de ta ville et de ton plat préféré. Amitiés, Ama.",
    "res:lettre": "C'est une lettre d'Ama, qui habite à Accra, à son ami Kofi. Elle le félicite pour ses examens. Elle lui raconte qu'elle a rendu visite à la plantation de ses grands-parents pendant les vacances et qu'elle a écouté de vieilles histoires. Sa famille va visiter Abidjan le mois prochain, donc elle espère voir Kofi. Elle lui pose des questions sur sa ville et son plat préféré.",
    "txt:telephone": "Aujourd'hui, beaucoup d'élèves ont un téléphone portable. Certaines personnes pensent que les téléphones sont utiles à l'école : les élèves peuvent chercher des informations, utiliser des dictionnaires et apprendre avec des applications éducatives. Mais d'autres pensent que les téléphones sont un problème. Certains élèves jouent à des jeux ou vont sur les réseaux sociaux pendant les cours, et ils n'écoutent pas le professeur. Certains utilisent même leur téléphone pour tricher pendant les contrôles. Dans beaucoup d'écoles, les téléphones sont interdits en classe. À mon avis, les téléphones peuvent nous aider à apprendre, mais nous devons les utiliser de façon responsable et seulement quand le professeur le permet.",
    "res:telephone": "Le texte parle des téléphones portables à l'école. Les téléphones peuvent être utiles pour trouver des informations et pour apprendre, mais ils peuvent aussi être un problème : certains élèves jouent, vont sur les réseaux sociaux ou trichent. C'est pourquoi beaucoup d'écoles interdisent les téléphones en classe. L'auteur pense que les téléphones peuvent aider les élèves s'ils les utilisent de façon responsable.",
    "txt:paludisme": "Le paludisme est une maladie grave en Afrique. Il est causé par un parasite et il est transmis par la piqûre d'un moustique femelle. Les symptômes sont la fièvre, le mal de tête et la fatigue. Les jeunes enfants et les femmes enceintes sont les plus exposés. En Côte d'Ivoire, le paludisme représente environ trente pour cent des consultations médicales. Pour nous protéger, nous devrions dormir sous une moustiquaire, supprimer l'eau stagnante autour de la maison et aller vite au centre de santé quand nous avons de la fièvre. Aujourd'hui, il existe aussi un vaccin contre le paludisme pour les jeunes enfants.",
    "res:paludisme": "Le texte parle du paludisme, une maladie grave transmise par la piqûre d'un moustique femelle. Les principaux symptômes sont la fièvre, le mal de tête et la fatigue, et les enfants et les femmes enceintes sont les plus exposés. En Côte d'Ivoire, il représente environ trente pour cent des consultations. Pour nous protéger, nous devrions dormir sous une moustiquaire, supprimer l'eau stagnante, aller vite au centre de santé et vacciner les jeunes enfants.",
    "txt:elephants": "En juin 2026, l'équipe nationale de football de Côte d'Ivoire, les Éléphants, a joué la Coupe du monde en Amérique du Nord. Ils ont perdu leur premier match contre l'Allemagne, mais ensuite ils ont battu Curaçao deux buts à zéro. Pour la première fois de leur histoire, ils se sont qualifiés pour la phase à élimination directe. Malheureusement, ils ont perdu contre la Norvège deux buts à un, à Dallas. Tout le pays était fier de l'équipe. Beaucoup de jeunes Ivoiriens rêvent de devenir footballeurs professionnels, mais ils doivent aussi aller à l'école.",
    "res:elephants": "Le texte parle des Éléphants à la Coupe du monde 2026. Après avoir perdu contre l'Allemagne, ils ont battu Curaçao et se sont qualifiés pour la première fois pour la phase à élimination directe. Ensuite, ils ont perdu contre la Norvège, deux buts à un. Le pays était fier d'eux. Le texte dit aussi que les jeunes qui rêvent de football doivent continuer à aller à l'école.",
    "conv:0": ["Peux-tu te présenter ?", "Bonjour. Je m'appelle Adriel. J'ai quinze ans et je suis en 3e. J'habite en Côte d'Ivoire avec ma famille. J'aime les mathématiques et le football."],
    "conv:1": ["Quelle est ta matière préférée ? Pourquoi ?", "Ma matière préférée est les mathématiques parce que j'aime résoudre des problèmes. J'aime aussi l'anglais parce que je peux parler avec des gens d'autres pays."],
    "conv:2": ["Que fais-tu pendant ton temps libre ?", "Pendant mon temps libre, je joue au football avec mes amis, j'écoute de la musique et j'aide mes parents à la maison. Le dimanche, je vais à l'église."],
    "conv:3": ["Que veux-tu faire plus tard ?", "Plus tard, je veux devenir ingénieur. Je veux construire des routes et des ponts dans mon pays. Pour cela, je dois travailler dur à l'école."],
    "conv:4": ["Peux-tu décrire ta ville ?", "Ma ville est grande et animée. Il y a un marché, un hôpital, des écoles et des églises. Les gens sont accueillants, mais parfois les rues sont sales pendant la saison des pluies."],
    "conv:5": ["Peux-tu parler de ta famille ?", "Nous sommes cinq dans ma famille : mon père, ma mère, mon grand frère, ma sœur et moi. Mon père est commerçant et ma mère est enseignante. J'aime ma famille."],
    "conv:6": ["Que penses-tu des réseaux sociaux ?", "À mon avis, les réseaux sociaux sont utiles pour apprendre et communiquer, mais ils peuvent être dangereux : il y a des arnaques et de fausses informations. Nous devons les utiliser de façon responsable."],
    "conv:7": ["Comment te prépares-tu au BEPC ?", "Je me prépare au BEPC tous les jours. Je révise mes leçons le soir, je fais des exercices et j'étudie avec mes amis le week-end. J'essaie aussi de bien dormir."],
    "theme:plastique": ["Que peuvent faire les élèves pour réduire la pollution plastique ?", "Les élèves peuvent faire beaucoup pour réduire la pollution plastique. D'abord, nous pouvons utiliser une gourde au lieu d'acheter des sachets d'eau en plastique. Ensuite, nous pouvons mettre nos déchets à la poubelle et jamais dans les caniveaux. Enfin, nous pouvons organiser des journées de nettoyage à l'école. En Côte d'Ivoire, environ la moitié des déchets plastiques finit dans la nature, donc tout le monde doit agir."],
    "theme:climat": ["Pourquoi les forêts sont-elles importantes ?", "Les forêts sont très importantes. Les arbres produisent de l'oxygène et absorbent le dioxyde de carbone, donc ils luttent contre le changement climatique. Ils protègent le sol et retiennent l'eau. Ils abritent aussi beaucoup d'animaux. En Côte d'Ivoire, beaucoup de forêt a disparu à cause de l'agriculture, alors en 2026 le gouvernement a lancé un programme pour planter des arbres sur un million et demi d'hectares."],
    "theme:paludisme": ["Comment pouvons-nous prévenir le paludisme ?", "Nous pouvons prévenir le paludisme de plusieurs façons. Nous devrions dormir sous une moustiquaire chaque nuit. Nous devons supprimer l'eau stagnante autour de la maison, parce que les moustiques y pondent leurs œufs. Les jeunes enfants peuvent recevoir le vaccin contre le paludisme, qui est gratuit en Côte d'Ivoire. Et si nous avons de la fièvre, nous devrions aller vite au centre de santé."],
    "theme:drogue": ["Que dirais-tu à un ami qui veut essayer la drogue ?", "Je dirais à mon ami que la drogue est très dangereuse. Elle abîme le cerveau et le corps, et les gens deviennent dépendants. La drogue peut aussi détruire tes études et ton avenir. Je dirais : c'est cool de dire non ! Allons plutôt jouer au foot ou étudier ensemble. Et si tu as des problèmes, parlons-en à un adulte en qui nous avons confiance."],
    "theme:numerique": ["Penses-tu que les réseaux sociaux sont bons ou mauvais pour les adolescents ?", "À mon avis, les réseaux sociaux sont à la fois bons et mauvais. Ils sont bons parce que nous pouvons apprendre des choses nouvelles, regarder des cours et parler avec notre famille. Mais ils peuvent être mauvais : il y a des arnaques, du harcèlement en ligne et de fausses informations, et certains élèves passent toute la nuit sur leur téléphone. Donc je pense que nous devons utiliser les réseaux sociaux de façon responsable : ne jamais partager notre mot de passe, vérifier une information avant de la partager et bien dormir avant l'école."],
    "theme:ecole": ["Comment te prépares-tu au BEPC ?", "Je me prépare au BEPC tous les jours, pas seulement à la fin de l'année. Je révise mes leçons le soir et je fais des exercices. Le week-end, j'étudie avec mes amis et nous nous posons des questions les uns aux autres. J'essaie aussi de bien dormir et de ne pas passer trop de temps sur mon téléphone. En 2026, seulement environ la moitié des candidats a réussi, donc je dois travailler dur."],
    "theme:civisme": ["Que peuvent faire les jeunes pour la paix dans leur pays ?", "Les jeunes peuvent faire beaucoup de choses pour la paix. Nous pouvons respecter tout le monde, quelle que soit son ethnie ou sa religion. Nous pouvons refuser la violence et les discours de haine sur les réseaux sociaux. Nous pouvons participer à des activités comme les journées de nettoyage ou le service civique. En 2026, la Côte d'Ivoire a fêté soixante-six ans d'indépendance, et sa devise est Union, Discipline, Travail."],
    "theme:cacao": ["Pourquoi le cacao est-il important pour la Côte d'Ivoire ?", "Le cacao est très important pour la Côte d'Ivoire parce que notre pays est le premier producteur de cacao du monde. Des millions de personnes vivent de la culture du cacao. Le pays exporte le cacao et gagne de l'argent pour construire des routes et des écoles. Mais en 2026, le prix payé aux planteurs est passé de deux mille huit cents à mille deux cents francs le kilo, donc les planteurs sont inquiets. Nous devrions aussi arrêter le travail des enfants dans les plantations de cacao."],
    "theme:sport": ["Quel est ton sport préféré et pourquoi ?", "Mon sport préféré est le football. Je l'aime parce que c'est un sport d'équipe : nous devons jouer ensemble et nous entraider. J'ai été très fier des Éléphants à la Coupe du monde 2026, parce que pour la première fois ils ont atteint la phase à élimination directe. Ils ont perdu contre la Norvège, mais ils ont bien joué. Le sport nous apprend la discipline et le respect des règles."],
    "sujet:en-a": "Kouadio a seize ans et habite à Yamoussoukro. L'année dernière, il a raté son BEPC parce qu'il passait trop de temps sur son téléphone. Ses parents étaient tristes, mais ils ne l'ont pas puni. À la place, son père l'a aidé à faire un emploi du temps. Maintenant, Kouadio étudie tous les soirs de sept heures à neuf heures, et il n'utilise son téléphone que le samedi. Il a aussi rejoint un groupe d'étude avec trois camarades de classe. Ils se retrouvent à la bibliothèque le dimanche et s'expliquent les leçons les uns aux autres. Son professeur d'anglais dit qu'il a fait de grands progrès. Kouadio est confiant : il pense qu'il réussira son examen cette année, et il veut devenir infirmier.",
    "sujet:es-a": "Je m'appelle Aya et j'ai quatorze ans. J'habite à Bouaké avec mes parents et mon petit frère. Le matin, je vais au collège à vélo. J'aime beaucoup les mathématiques, mais je n'aime pas l'histoire. L'après-midi, j'aide ma mère au marché : nous vendons des fruits et des légumes. L'année dernière, je suis allée à Abidjan avec mon oncle et j'ai visité le port. L'année prochaine, je vais étudier dans un lycée d'Abidjan parce que je veux être ingénieure."
  };
  // Bloc repliable « Voir la traduction »
  function blocTraduction(cle) {
    const t = TRAD[cle]; if (!t) return "";
    const corps = Array.isArray(t) ? `<p><b>Question :</b> ${t[0]}</p><p><b>Réponse :</b> ${t[1]}</p>` : `<p>${t}</p>`;
    return `<details class="traduction"><summary>Voir la traduction en français</summary>${corps}<small>Essaie d'abord de comprendre seul, puis vérifie ici. Touche un mot du texte pour avoir sa traduction.</small></details>`;
  }
