  // =========================================================
  // Les mots à connaître : [mot, définition simple, exemple]
  // =========================================================
  const MOTS = {
    // ---------------- Maths ----------------
    bases: [["Fraction", "Nombre écrit sous la forme a/b, qui représente a parts d'une unité partagée en b parts égales.", "3/4 d'un gâteau : on le coupe en 4 et on prend 3 parts."],
      ["Dénominateur", "Nombre du bas d'une fraction : il indique en combien de parts on partage.", "Dans 5/8, le dénominateur est 8."],
      ["Nombre relatif", "Nombre positif ou négatif, avec son signe.", "−5 °C la nuit à Paris, +32 °C à Abidjan."],
      ["Opposé", "L'opposé d'un nombre a le même chiffre mais le signe contraire ; leur somme vaut 0.", "L'opposé de 7 est −7, car 7 + (−7) = 0."]],
    litteral: [["Expression littérale", "Calcul qui contient des lettres représentant des nombres.", "3x + 5, où x peut valoir n'importe quel nombre."],
      ["Développer", "Transformer un produit en somme.", "2(x + 3) = 2x + 6."],
      ["Factoriser", "Transformer une somme en produit (le contraire de développer).", "2x + 6 = 2(x + 3)."],
      ["Identité remarquable", "Égalité toujours vraie qui permet de développer ou factoriser rapidement.", "(a + b)² = a² + 2ab + b²."],
      ["Équation produit nul", "Équation de la forme A × B = 0 : on résout A = 0 ou B = 0.", "(x − 2)(x + 5) = 0 donne x = 2 ou x = −5."]],
    thales: [["Configuration de Thalès", "Figure avec deux droites sécantes coupées par deux droites parallèles.", "Le triangle ABC avec M sur [AB], N sur [AC] et (MN) // (BC)."],
      ["Droites parallèles", "Droites qui ne se coupent jamais, même prolongées.", "Les deux bords d'une route droite."],
      ["Quotient", "Résultat d'une division, souvent écrit sous forme de fraction.", "AM/AB = 4/10 = 0,4."],
      ["Réciproque", "Propriété « à l'envers » : on part de la conclusion pour retrouver l'hypothèse.", "Si AM/AB = AN/AC, alors (MN) // (BC)."]],
    racines: [["Racine carrée", "La racine carrée d'un nombre positif a est le nombre positif dont le carré vaut a.", "√49 = 7 car 7² = 49."],
      ["Carré parfait", "Nombre qui est le carré d'un entier.", "1, 4, 9, 16, 25, 36, 49, 64, 81, 100."],
      ["Valeur absolue", "Distance d'un nombre à zéro : elle est toujours positive.", "|−5| = 5 et |5| = 5."],
      ["Expression conjuguée", "Le conjugué de a + √b est a − √b ; leur produit n'a plus de racine.", "(3 + √2)(3 − √2) = 9 − 2 = 7."]],
    triangle: [["Hypoténuse", "Dans un triangle rectangle, côté opposé à l'angle droit : c'est le plus long.", "Dans ABC rectangle en A, l'hypoténuse est [BC]."],
      ["Côté adjacent", "Côté de l'angle droit qui touche l'angle étudié.", "Pour l'angle B, le côté adjacent est [AB]."],
      ["Côté opposé", "Côté situé en face de l'angle étudié.", "Pour l'angle B, le côté opposé est [AC]."],
      ["Cosinus", "Dans un triangle rectangle, rapport côté adjacent / hypoténuse.", "cos B = AB/BC = 3/5 = 0,6."]],
    calcul: [["Intervalle", "Ensemble de tous les nombres compris entre deux bornes.", "[2 ; 5] contient 2 ; 3,4 ; 4,99 et 5."],
      ["Amplitude", "Longueur d'un intervalle : borne haute moins borne basse.", "L'amplitude de [2 ; 7] est 7 − 2 = 5."],
      ["Encadrement", "Écriture qui place un nombre entre deux valeurs.", "1,41 < √2 < 1,42."],
      ["Arrondi", "Valeur approchée la plus proche à une précision donnée.", "L'arrondi au dixième de 3,46 est 3,5."]],
    angles: [["Angle inscrit", "Angle dont le sommet est sur le cercle et dont les côtés coupent le cercle.", "AĈB avec A, B, C sur le cercle."],
      ["Angle au centre", "Angle dont le sommet est le centre du cercle.", "AÔB, où O est le centre."],
      ["Arc intercepté", "Portion du cercle comprise entre les côtés d'un angle.", "L'arc AB intercepté par l'angle AĈB."],
      ["Diamètre", "Segment qui passe par le centre et relie deux points du cercle.", "Si le rayon vaut 3 cm, le diamètre vaut 6 cm."]],
    vecteurs: [["Vecteur", "Objet défini par une direction, un sens et une longueur, représenté par une flèche.", "AB⃗ va de A vers B."],
      ["Vecteurs égaux", "Vecteurs de même direction, même sens et même longueur.", "Dans un parallélogramme ABCD, AB⃗ = DC⃗."],
      ["Vecteurs colinéaires", "Vecteurs de même direction : l'un est un multiple de l'autre.", "AB⃗ = 3 CD⃗."],
      ["Vecteur nul", "Vecteur de longueur zéro, noté 0⃗.", "AA⃗ = 0⃗."]],
    equations: [["Équation", "Égalité qui contient une inconnue ; la résoudre, c'est trouver sa valeur.", "2x + 3 = 11 donne x = 4."],
      ["Inéquation", "Inégalité qui contient une inconnue ; ses solutions forment un intervalle.", "x + 2 > 5 donne x > 3, soit ]3 ; +∞[."],
      ["Solution", "Valeur de l'inconnue qui rend l'égalité (ou l'inégalité) vraie.", "4 est solution de 2x + 3 = 11."],
      ["Système d'inéquations", "Plusieurs inéquations à vérifier en même temps.", "x ≥ 1 et x < 4 donne [1 ; 4[."]],
    coordonnees: [["Repère orthonormé", "Repère dont les axes sont perpendiculaires et ont la même unité.", "Le quadrillage d'une feuille avec deux axes."],
      ["Abscisse", "Première coordonnée d'un point (sur l'axe horizontal).", "Dans A(3 ; −2), l'abscisse est 3."],
      ["Ordonnée", "Deuxième coordonnée d'un point (sur l'axe vertical).", "Dans A(3 ; −2), l'ordonnée est −2."],
      ["Milieu", "Point situé à égale distance des deux extrémités d'un segment.", "Le milieu de A(0 ; 0) et B(4 ; 2) est I(2 ; 1)."]],
    droites: [["Équation de droite", "Égalité y = ax + b vérifiée par tous les points de la droite.", "y = 2x + 1."],
      ["Coefficient directeur", "Nombre a qui indique la pente de la droite.", "Pour y = 2x + 1, quand x augmente de 1, y augmente de 2."],
      ["Ordonnée à l'origine", "Nombre b : là où la droite coupe l'axe vertical.", "y = 2x + 1 coupe l'axe des y en 1."],
      ["Droites perpendiculaires", "Droites qui se coupent en formant un angle droit.", "y = 2x et y = −0,5x (car 2 × (−0,5) = −1)."]],
    stats: [["Effectif", "Nombre de fois qu'une valeur apparaît.", "8 élèves ont eu 12 : l'effectif de 12 est 8."],
      ["Fréquence", "Effectif divisé par l'effectif total (souvent en %).", "8 élèves sur 40 : fréquence = 20 %."],
      ["Moyenne", "Somme de toutes les valeurs divisée par leur nombre.", "Notes 10, 12, 14 : moyenne = 36 ÷ 3 = 12."],
      ["Médiane", "Valeur qui partage la série rangée en deux groupes de même effectif.", "Pour 3 ; 7 ; 9 ; 12 ; 15, la médiane est 9."],
      ["Mode", "Valeur qui a le plus grand effectif.", "Si l'attiéké est choisi par 12 élèves sur 30, c'est le mode."]],
    systemes: [["Système d'équations", "Deux équations à deux inconnues à vérifier en même temps.", "x + y = 12 et 2x − y = 3."],
      ["Couple solution", "Paire de nombres (x ; y) qui vérifie les deux équations.", "(5 ; 7) est solution de x + y = 12 et 2x − y = 3."],
      ["Substitution", "Méthode : on exprime une inconnue et on la remplace dans l'autre équation.", "x = 12 − y, puis on remplace x dans 2x − y = 3."],
      ["Combinaison", "Méthode : on additionne ou soustrait les équations pour éliminer une inconnue.", "(x + y) + (2x − y) = 12 + 3 donne 3x = 15."]],
    affines: [["Application affine", "Fonction de la forme f(x) = ax + b.", "f(x) = 3x + 2."],
      ["Application linéaire", "Application affine avec b = 0 : f(x) = ax. Elle traduit la proportionnalité.", "Prix de x kg de riz à 400 F : f(x) = 400x."],
      ["Image", "Résultat f(x) obtenu en remplaçant x par un nombre.", "Si f(x) = 3x + 2, l'image de 4 est 14."],
      ["Antécédent", "Nombre de départ qui a une image donnée.", "Si f(x) = 3x + 2, l'antécédent de 14 est 4."]],
    pyramides: [["Pyramide", "Solide avec une base polygonale et des faces triangulaires qui se rejoignent en un sommet.", "Les pyramides d'Égypte ont une base carrée."],
      ["Cône de révolution", "Solide obtenu en faisant tourner un triangle rectangle autour d'un côté de l'angle droit.", "Un cornet de glace."],
      ["Génératrice", "Segment qui relie le sommet du cône à un point du cercle de base.", "Si r = 3 et h = 4, la génératrice mesure 5."],
      ["Réduction", "Figure dont toutes les longueurs sont multipliées par k < 1.", "Couper une pyramide à mi-hauteur donne une réduction de coefficient 1/2."]],
    // ---------------- Physique-Chimie ----------------
    "pc-masse": [["Masse", "Quantité de matière d'un corps, en kilogrammes (kg). Elle ne change pas avec le lieu.", "Un sac de riz de 25 kg a la même masse à Abidjan et sur la Lune."],
      ["Poids", "Force d'attraction exercée par la Terre sur un corps, en newtons (N).", "Le poids d'un sac de 25 kg est 250 N (avec g = 10 N/kg)."],
      ["Intensité de la pesanteur (g)", "Rapport P/m, en N/kg ; il vaut environ 10 N/kg sur Terre.", "Sur la Lune, g ≈ 1,6 N/kg."],
      ["Centre de gravité", "Point où s'applique le poids d'un corps.", "Le milieu d'une règle homogène."]],
    "pc-forces": [["Force", "Action mécanique capable de mettre en mouvement, de freiner ou de déformer un corps.", "Pousser une brouette."],
      ["Force de contact", "Force qui s'exerce quand les deux corps se touchent.", "La main qui pousse une porte."],
      ["Force à distance", "Force qui s'exerce sans contact.", "L'aimant qui attire un clou, le poids."],
      ["Dynamomètre", "Appareil qui mesure l'intensité d'une force en newtons.", "Un peson de marché."]],
    "pc-equilibre": [["Équilibre", "Un corps est en équilibre s'il reste immobile.", "Une lampe suspendue qui ne bouge pas."],
      ["Forces qui se compensent", "Forces de même droite d'action, de sens contraires et de même intensité.", "Le poids d'une lampe et la tension du fil."],
      ["Tension d'un fil", "Force exercée par un fil tendu sur l'objet qu'il retient.", "Le fil qui tient un seau au-dessus d'un puits."],
      ["Réaction du support", "Force exercée par une surface sur un objet posé dessus.", "La table qui soutient un livre."]],
    "pc-travail": [["Travail d'une force", "Énergie transférée par une force qui déplace son point d'application : W = F × L, en joules.", "Pousser une charrette avec 100 N sur 5 m : W = 500 J."],
      ["Travail moteur", "Travail d'une force qui favorise le mouvement (positif).", "La force d'un porteur qui soulève un colis."],
      ["Travail résistant", "Travail d'une force qui s'oppose au mouvement (négatif).", "Les frottements du sol sur une caisse."],
      ["Puissance", "Travail effectué par seconde : P = W / t, en watts.", "1 500 J en 10 s donnent 150 W."]],
    "pc-energie": [["Énergie cinétique", "Énergie d'un corps due à sa vitesse : Ec = ½ m v².", "Une moto qui roule vite a beaucoup d'énergie cinétique."],
      ["Énergie potentielle", "Énergie d'un corps due à sa hauteur : Ep = m g h.", "Une mangue accrochée en haut de l'arbre."],
      ["Énergie mécanique", "Somme de l'énergie cinétique et de l'énergie potentielle.", "Em = Ec + Ep."],
      ["Conservation de l'énergie", "Sans frottements, l'énergie mécanique reste constante.", "En tombant, la mangue perd de l'Ep et gagne autant d'Ec."]],
    "pc-electrolyse": [["Électrolyse", "Décomposition d'une substance par le passage du courant électrique.", "L'électrolyse de l'eau donne du dihydrogène et du dioxygène."],
      ["Cathode", "Électrode reliée à la borne négative (−).", "Le dihydrogène se dégage à la cathode."],
      ["Anode", "Électrode reliée à la borne positive (+).", "Le dioxygène se dégage à l'anode."],
      ["Synthèse", "Fabrication d'un corps à partir d'autres corps.", "La synthèse de l'eau : 2 H₂ + O₂ → 2 H₂O."]],
    "pc-alcanes": [["Hydrocarbure", "Corps formé uniquement de carbone et d'hydrogène.", "Le méthane CH₄, le butane C₄H₁₀."],
      ["Alcane", "Hydrocarbure saturé de formule CₙH₂ₙ₊₂.", "Le propane C₃H₈."],
      ["Combustion complète", "Combustion avec assez de dioxygène : elle donne CO₂ et eau (flamme bleue).", "Le gaz de cuisine bien réglé."],
      ["Combustion incomplète", "Combustion avec trop peu de dioxygène : elle donne de la suie et du CO toxique (flamme jaune).", "Les casseroles noircies par une flamme jaune."]],
    "pc-lentilles": [["Lentille convergente", "Lentille à bords minces qui concentre la lumière.", "Une loupe."],
      ["Lentille divergente", "Lentille à bords épais qui disperse la lumière.", "Les verres de lunettes d'un myope."],
      ["Foyer image (F')", "Point où convergent les rayons arrivant parallèles à l'axe.", "Le point brûlant quand on concentre le soleil avec une loupe."],
      ["Vergence", "Grandeur C = 1/f (f en mètres), exprimée en dioptries (δ).", "f = 0,2 m donne C = 5 δ."]],
    "pc-oeil": [["Cristallin", "Partie de l'œil qui joue le rôle d'une lentille convergente.", "Il se bombe pour regarder de près."],
      ["Rétine", "Membrane au fond de l'œil où se forme l'image.", "Comme l'écran au cinéma."],
      ["Myopie", "Défaut : on voit mal de loin ; l'image se forme avant la rétine.", "Un élève myope ne lit pas bien le tableau du fond de la classe."],
      ["Hypermétropie", "Défaut : on voit mal de près ; l'image se forme derrière la rétine.", "Difficulté à lire un livre tenu près des yeux."]],
    "pc-oxydation": [["Oxydation", "Réaction d'un corps avec le dioxygène.", "La combustion du charbon de bois."],
      ["Oxyde", "Corps formé par la réaction d'un élément avec l'oxygène.", "L'oxyde de cuivre CuO, noir."],
      ["Rouille", "Oxyde de fer formé lentement en présence d'eau et d'air.", "Un portail en fer non peint qui rouille."],
      ["Corps pur simple", "Corps formé d'une seule sorte d'atomes.", "Le fer, le cuivre, le carbone."]],
    "pc-reduction": [["Réduction", "Réaction qui enlève l'oxygène d'un oxyde.", "L'oxyde de cuivre transformé en cuivre."],
      ["Réducteur", "Corps qui capte l'oxygène d'un oxyde.", "Le carbone dans 2 CuO + C → 2 Cu + CO₂."],
      ["Oxydoréduction", "Réaction où ont lieu en même temps une oxydation et une réduction.", "Le carbone est oxydé pendant que l'oxyde de cuivre est réduit."],
      ["Haut fourneau", "Grand four industriel où l'on réduit le minerai de fer pour obtenir la fonte.", "La sidérurgie."]],
    "pc-solutions": [["pH", "Nombre de 0 à 14 qui indique si une solution est acide, neutre ou basique.", "Le jus de citron a un pH d'environ 2."],
      ["Solution acide", "Solution de pH inférieur à 7.", "Le vinaigre."],
      ["Solution basique", "Solution de pH supérieur à 7.", "L'eau de Javel, l'eau savonneuse."],
      ["Indicateur coloré", "Substance qui change de couleur selon le pH.", "Le BBT : jaune (acide), vert (neutre), bleu (basique)."]],
    "pc-puissance-elec": [["Puissance électrique", "Énergie consommée par seconde par un appareil : P = U × I, en watts.", "Un fer à repasser de 1 100 W."],
      ["Puissance nominale", "Puissance indiquée sur l'appareil pour un fonctionnement normal.", "« 220 V – 60 W » sur une ampoule."],
      ["Énergie électrique", "E = P × t : ce que l'appareil consomme pendant un temps donné.", "Une ampoule de 60 W allumée 10 h consomme 0,6 kWh."],
      ["Kilowattheure (kWh)", "Unité d'énergie utilisée sur les factures d'électricité.", "Le compteur de la CIE compte les kWh."]],
    "pc-ohm": [["Résistance", "Grandeur qui caractérise la difficulté du courant à traverser un conducteur, en ohms (Ω).", "Un résistor de 100 Ω."],
      ["Loi d'Ohm", "Pour un conducteur ohmique, U = R × I.", "R = 20 Ω et I = 0,5 A donnent U = 10 V."],
      ["Conducteur ohmique", "Dipôle qui respecte la loi d'Ohm.", "Le résistor d'un fer à repasser."],
      ["Effet Joule", "Échauffement d'un conducteur traversé par un courant.", "La résistance d'un chauffe-eau."]]
  };
  Object.assign(MOTS, {
    // ---------------- SVT ----------------
    "svt-aliments": [["Aliment", "Produit que l'on mange ou que l'on boit pour vivre et grandir.", "L'attiéké, le poisson, la mangue, l'eau."],
      ["Nutriment", "Substance simple issue de la digestion, qui peut passer dans le sang.", "Le glucose issu de l'amidon du riz."],
      ["Ration alimentaire", "Quantité et variété d'aliments nécessaires à une personne pour une journée.", "Un adolescent a besoin de plus d'énergie qu'un enfant de 5 ans."],
      ["Carence", "Manque d'un nutriment dans l'alimentation, qui provoque une maladie.", "Le manque de vitamine C provoque le scorbut."],
      ["Aliment bâtisseur", "Aliment riche en protides, qui construit et répare le corps.", "Le poisson, les œufs, les haricots."]],
    "svt-digestion": [["Digestion", "Transformation des aliments en nutriments dans le tube digestif.", "L'amidon du foutou transformé en glucose."],
      ["Enzyme", "Substance qui découpe les grosses molécules des aliments.", "L'amylase de la salive transforme l'amidon en sucre."],
      ["Suc digestif", "Liquide produit par une glande, qui contient des enzymes.", "La salive, le suc gastrique, le suc pancréatique."],
      ["Absorption intestinale", "Passage des nutriments de l'intestin grêle vers le sang.", "Le glucose passe dans le sang à travers les villosités."],
      ["Villosité intestinale", "Petit repli de la paroi de l'intestin grêle qui augmente la surface d'absorption.", "Des millions de villosités tapissent l'intestin."]],
    "svt-sang": [["Plasma", "Partie liquide et jaunâtre du sang.", "Il représente environ 55 % du sang."],
      ["Hématie", "Globule rouge : cellule du sang qui transporte le dioxygène grâce à l'hémoglobine.", "Environ 5 millions par mm³ de sang."],
      ["Leucocyte", "Globule blanc : cellule du sang qui défend l'organisme contre les microbes.", "Ils attaquent les microbes d'une plaie infectée."],
      ["Plaquette", "Élément du sang qui permet la coagulation.", "Elles arrêtent le saignement d'une petite coupure."],
      ["Anémie", "Manque de globules rouges ou d'hémoglobine.", "Un enfant qui a eu souvent le paludisme peut être anémié."]],
    "svt-transfusion": [["Transfusion sanguine", "Injection de sang d'un donneur à un receveur compatible.", "Après un accident, un blessé reçoit du sang."],
      ["Antigène", "Molécule à la surface des hématies qui détermine le groupe sanguin.", "Les hématies du groupe A portent l'antigène A."],
      ["Anticorps", "Molécule du plasma qui attaque un antigène étranger.", "Le plasma d'une personne du groupe A contient des anti-B."],
      ["Agglutination", "Collage des hématies entre elles quand elles rencontrent l'anticorps correspondant.", "Du sang B donné à une personne du groupe A."],
      ["Donneur universel", "Groupe qui peut donner à tous : O (et O Rh− en tenant compte du Rhésus).", "Une personne O− peut donner à tout le monde."]],
    "svt-circulation": [["Artère", "Vaisseau qui transporte le sang du cœur vers les organes.", "L'aorte."],
      ["Veine", "Vaisseau qui ramène le sang des organes vers le cœur.", "Les veines caves."],
      ["Capillaire", "Très petit vaisseau où se font les échanges entre le sang et les cellules.", "Les capillaires des muscles."],
      ["Grande circulation", "Trajet du sang du cœur gauche vers les organes et retour au cœur droit.", "Ventricule gauche → aorte → organes → veines caves."],
      ["Petite circulation", "Trajet du sang du cœur droit vers les poumons et retour au cœur gauche.", "Le sang s'y charge en dioxygène."]],
    "svt-grossesse": [["Grossesse précoce", "Grossesse qui survient chez une adolescente, avant l'âge adulte.", "Une élève de 15 ans enceinte."],
      ["Ovulation", "Libération d'un ovule par l'ovaire, vers le 14e jour d'un cycle de 28 jours.", "C'est la période où la fécondation est possible."],
      ["Fécondation", "Union d'un spermatozoïde et d'un ovule.", "Elle donne une cellule-œuf."],
      ["Contraception", "Ensemble des moyens pour éviter une grossesse.", "Le préservatif, qui protège aussi des IST."]],
    "svt-vih": [["VIH", "Virus de l'immunodéficience humaine, qui détruit les lymphocytes T4.", "Il se transmet par le sang, les rapports sexuels et de la mère à l'enfant."],
      ["Sida", "Stade avancé de l'infection au VIH : l'organisme ne se défend plus.", "Apparition de maladies opportunistes."],
      ["Maladie opportuniste", "Maladie qui profite de l'affaiblissement des défenses de l'organisme.", "La tuberculose chez une personne au stade sida."],
      ["Séropositif", "Personne dont le test révèle la présence d'anticorps contre le VIH.", "Sous ARV, une personne séropositive vit normalement."],
      ["ARV", "Antirétroviraux : médicaments qui bloquent la multiplication du VIH.", "Gratuits en Côte d'Ivoire."]],
    "svt-sol": [["Sol", "Couche superficielle de la Terre, formée de minéraux, de matière organique, d'eau et d'air.", "La terre du jardin de l'école."],
      ["Humus", "Matière organique issue de la décomposition des débris végétaux et animaux.", "La couche sombre sous les feuilles mortes en forêt."],
      ["Horizon", "Couche du sol qui a une couleur et une composition particulières.", "L'horizon humifère, en haut du profil."],
      ["Perméabilité", "Capacité d'un sol à laisser passer l'eau.", "Un sol sableux est très perméable."],
      ["Roche-mère", "Roche située en bas du profil, à partir de laquelle le sol se forme.", "Le granite sous un sol de savane."]],
    "svt-sol-plantes": [["Poil absorbant", "Prolongement fin de la racine qui absorbe l'eau et les sels minéraux.", "Visible près de l'extrémité d'une racine de haricot."],
      ["Sève brute", "Eau et sels minéraux qui montent des racines vers les feuilles.", "Elle circule dans les vaisseaux du bois."],
      ["Sels minéraux", "Éléments nutritifs du sol dont la plante a besoin (azote, phosphore, potassium).", "Le NPK des engrais."],
      ["Photosynthèse", "Fabrication de matière organique par la plante grâce à la lumière, avec rejet de dioxygène.", "Les feuilles vertes du manguier au soleil."]],
    "svt-degradation": [["Érosion", "Arrachement et transport du sol par l'eau ou le vent.", "La terre emportée par la pluie sur une pente nue."],
      ["Lessivage", "Entraînement des sels minéraux en profondeur par l'eau.", "Un sol sableux perd vite ses éléments nutritifs."],
      ["Désertification", "Transformation progressive d'une région en désert.", "Elle menace le nord de l'Afrique de l'Ouest."],
      ["Déforestation", "Destruction des forêts.", "Les forêts coupées pour installer des plantations."]],
    "svt-protection": [["Jachère", "Terre laissée au repos pendant un certain temps pour qu'elle retrouve sa fertilité.", "Un champ non cultivé pendant 3 ans."],
      ["Compost", "Engrais naturel obtenu par la décomposition de déchets végétaux.", "Les épluchures et feuilles mises en tas."],
      ["Rotation des cultures", "Changement de culture d'une saison à l'autre sur le même champ.", "Maïs une année, arachide l'année suivante."],
      ["Agroforesterie", "Association d'arbres et de cultures sur une même parcelle.", "Du cacao planté à l'ombre de grands arbres."],
      ["Reboisement", "Plantation d'arbres sur une terre déboisée.", "Le programme de 2026 vise 1,5 million d'hectares."]],
    // ---------------- Histoire-Géographie ----------------
    "hg-colonisation": [["Impérialisme", "Volonté d'une puissance d'étendre sa domination sur d'autres territoires.", "Les puissances européennes se partagent l'Afrique à la fin du XIXe siècle."],
      ["Colonisation", "Occupation et exploitation d'un territoire par une puissance étrangère.", "La Côte d'Ivoire devient colonie française en 1893."],
      ["Colonie", "Territoire dominé et administré par une puissance étrangère.", "La colonie de Côte d'Ivoire, créée le 10 mars 1893."],
      ["Résistance", "Lutte d'un peuple contre la conquête ou la domination étrangère.", "Samory Touré a combattu les Français jusqu'en 1898."],
      ["Travail forcé", "Travail obligatoire et non payé imposé aux colonisés.", "Construction de routes et de voies ferrées."]],
    "hg-independance": [["Indépendance", "Situation d'un pays qui se gouverne lui-même, sans domination étrangère.", "La Côte d'Ivoire est indépendante depuis le 7 août 1960."],
      ["Décolonisation", "Processus par lequel les colonies deviennent indépendantes.", "La plupart des pays d'Afrique de l'Ouest en 1960."],
      ["Parti politique", "Association de personnes qui veulent conquérir le pouvoir par les élections.", "Le PDCI, créé en 1946."],
      ["Autonomie interne", "Droit pour une colonie de gérer ses propres affaires intérieures.", "Accordée par la loi-cadre de 1956."],
      ["Référendum", "Vote par lequel les citoyens répondent oui ou non à une question.", "Le référendum du 28 septembre 1958."]],
    "hg-crises": [["Crise sociopolitique", "Période de troubles graves qui touche la société et le pouvoir.", "La crise post-électorale ivoirienne de 2010-2011."],
      ["Coup d'État", "Prise du pouvoir par la force, contre les règles.", "Plusieurs coups d'État au Sahel depuis 2020."],
      ["Génocide", "Extermination volontaire d'un groupe humain à cause de son origine.", "Le génocide des Tutsi au Rwanda en 1994."],
      ["Réfugié", "Personne qui fuit son pays à cause de la guerre ou des persécutions.", "Des milliers de réfugiés lors des crises."],
      ["Réconciliation", "Retour à la paix et à l'entente entre des groupes qui s'opposaient.", "Les commissions de dialogue après une crise."]],
    "hg-ww2": [["Guerre mondiale", "Guerre qui oppose de nombreux pays sur plusieurs continents.", "La Seconde Guerre mondiale (1939-1945)."],
      ["Totalitarisme", "Régime qui contrôle toute la vie des citoyens et supprime les libertés.", "Le nazisme d'Hitler en Allemagne."],
      ["Shoah", "Génocide des Juifs d'Europe par les nazis.", "Environ 6 millions de victimes."],
      ["Guerre totale", "Guerre qui mobilise toutes les ressources d'un pays et touche aussi les civils.", "Bombardements des villes, usines tournées vers l'armement."],
      ["Capitulation", "Reddition d'une armée ou d'un pays vaincu.", "L'Allemagne capitule le 8 mai 1945."]],
    "hg-onu": [["ONU", "Organisation des Nations unies, créée en 1945 pour maintenir la paix dans le monde.", "193 États membres, siège à New York."],
      ["Droit de veto", "Pouvoir d'un membre permanent du Conseil de sécurité de bloquer une décision.", "La Chine, les États-Unis, la France, le Royaume-Uni et la Russie l'ont."],
      ["Casques bleus", "Soldats de l'ONU envoyés pour maintenir la paix.", "L'ONUCI en Côte d'Ivoire (2004-2017)."],
      ["Institution spécialisée", "Organisation de l'ONU chargée d'un domaine précis.", "L'OMS pour la santé, l'UNESCO pour l'éducation."]],
    "hg-ua": [["Union africaine (UA)", "Organisation qui regroupe les 55 États d'Afrique, créée en 2002.", "Siège à Addis-Abeba."],
      ["Panafricanisme", "Idée selon laquelle les peuples africains doivent s'unir.", "La création de l'OUA en 1963."],
      ["Intégration régionale", "Rapprochement de pays voisins pour coopérer (économie, circulation).", "La CEDEAO, l'UEMOA."],
      ["ZLECAf", "Zone de libre-échange continentale africaine : pour faciliter le commerce entre pays africains.", "Échanges lancés en 2021."]],
    "hg-atouts": [["Atout", "Avantage qui favorise le développement d'un pays.", "Des sols fertiles, une population jeune."],
      ["Relief", "Forme du terrain : plaines, plateaux, montagnes.", "Les montagnes de l'ouest, avec le mont Nimba."],
      ["Climat équatorial", "Climat chaud et humide toute l'année, avec quatre saisons.", "Le sud de la Côte d'Ivoire."],
      ["Ressources naturelles", "Richesses fournies par la nature.", "L'or, le pétrole, les forêts, l'eau."],
      ["Population active", "Personnes en âge de travailler et qui travaillent ou cherchent un emploi.", "Les jeunes qui entrent sur le marché du travail."]],
    "hg-secteurs": [["Secteur primaire", "Activités qui exploitent directement la nature.", "L'agriculture, la pêche, l'élevage, les mines."],
      ["Secteur secondaire", "Activités qui transforment les matières premières.", "Une chocolaterie, une usine de ciment."],
      ["Secteur tertiaire", "Activités de services.", "Le commerce, les banques, les transports, l'école."],
      ["Culture d'exportation", "Culture destinée à être vendue à l'étranger.", "Le cacao, l'anacarde, l'hévéa."],
      ["Culture vivrière", "Culture destinée à nourrir la population du pays.", "Le manioc, l'igname, le riz."]],
    "hg-problemes": [["Développement", "Amélioration des conditions de vie de la population (santé, éducation, revenus).", "Construire des écoles et des hôpitaux."],
      ["Exode rural", "Départ des habitants des campagnes vers les villes.", "Des jeunes qui quittent le village pour Abidjan."],
      ["Endettement", "Situation d'un pays qui a emprunté beaucoup d'argent et doit le rembourser.", "Le remboursement de la dette réduit les dépenses d'éducation."],
      ["Diversification", "Développement de nouvelles activités pour ne pas dépendre d'un seul produit.", "Produire de l'anacarde, de l'hévéa, et transformer le cacao."]],
    "hg-afrique": [["Mondialisation", "Intensification des échanges de marchandises, de capitaux et d'informations dans le monde.", "Un téléphone assemblé en Asie et vendu à Bouaké."],
      ["Matière première", "Produit brut tiré de la nature, avant transformation.", "Le cacao, le pétrole, le cobalt."],
      ["Produit manufacturé", "Produit fabriqué en usine.", "Une voiture, un ordinateur."],
      ["Commerce extérieur", "Échanges d'un pays avec l'étranger : importations et exportations.", "La Côte d'Ivoire exporte du cacao et importe des machines."]],
    // ---------------- EDHC ----------------
    "edhc-parents": [["Droits de l'enfant", "Droits reconnus à tout enfant par la Convention de l'ONU de 1989.", "Le droit à l'éducation, à la santé, aux loisirs."],
      ["Épanouissement", "Développement harmonieux du corps, de l'esprit et de la personnalité.", "Un enfant qui étudie, joue et est écouté."],
      ["Scolarisation obligatoire", "Obligation d'aller à l'école de 6 à 16 ans en Côte d'Ivoire.", "Instaurée en 2015."],
      ["Acte de naissance", "Document officiel qui prouve l'identité d'une personne.", "Indispensable pour s'inscrire au BEPC."]],
    "edhc-violences": [["Violence", "Acte qui porte atteinte à l'intégrité physique ou morale d'une personne.", "Coups, insultes répétées, harcèlement."],
      ["Mutilations génitales féminines", "Ablation d'une partie des organes génitaux féminins, interdite en Côte d'Ivoire depuis 1998.", "Une pratique punie par la loi."],
      ["Mariage précoce", "Mariage d'un enfant avant l'âge légal.", "Une fille de 14 ans mariée de force."],
      ["DUDH", "Déclaration universelle des droits de l'homme, adoptée par l'ONU le 10 décembre 1948.", "Article 1 : les hommes naissent libres et égaux en droits."]],
    "edhc-humanitaire": [["Organisation humanitaire", "Organisation qui aide les victimes de guerres ou de catastrophes.", "La Croix-Rouge, Médecins sans frontières."],
      ["Droit international humanitaire (DIH)", "Règles qui protègent les personnes pendant les conflits armés.", "Les Conventions de Genève de 1949."],
      ["Neutralité", "Fait de ne prendre parti pour aucun camp.", "La Croix-Rouge soigne les blessés des deux camps."],
      ["Réfugié", "Personne qui a fui son pays pour échapper à un danger.", "Le HCR aide les réfugiés."]],
    "edhc-partis": [["Démocratie", "Régime où le pouvoir appartient au peuple, qui choisit ses dirigeants par le vote.", "L'élection présidentielle tous les 5 ans."],
      ["Multipartisme", "Existence de plusieurs partis politiques.", "En Côte d'Ivoire depuis 1990."],
      ["Institution", "Organe officiel qui fait fonctionner l'État.", "L'Assemblée nationale, le Conseil constitutionnel."],
      ["Constitution", "Loi fondamentale qui organise l'État et les pouvoirs.", "La Constitution ivoirienne du 8 novembre 2016."],
      ["Tolérance", "Respect des opinions et des différences des autres.", "Écouter un camarade d'un autre parti sans l'insulter."]],
    "edhc-vote": [["Vote", "Acte par lequel un citoyen exprime son choix lors d'une élection.", "Mettre son bulletin dans l'urne."],
      ["Suffrage universel", "Droit de vote accordé à tous les citoyens majeurs.", "Tout Ivoirien de 18 ans et plus inscrit sur la liste."],
      ["Liste électorale", "Registre des personnes autorisées à voter.", "Il faut s'y inscrire pour voter."],
      ["Abstention", "Fait de ne pas aller voter.", "Un fort taux d'abstention affaiblit la démocratie."]],
    "edhc-impot": [["Impôt", "Contribution obligatoire versée à l'État pour financer les services publics.", "L'impôt sur les salaires."],
      ["Impôt direct", "Impôt payé directement par la personne à l'administration.", "L'impôt foncier sur une maison."],
      ["Impôt indirect", "Impôt inclus dans le prix d'un produit ou d'un service.", "La TVA de 18 % dans le prix d'un savon."],
      ["Contribuable", "Personne qui paie des impôts.", "Un commerçant qui paie sa patente."],
      ["Fraude fiscale", "Fait d'échapper illégalement à l'impôt.", "Cacher ses revenus pour moins payer."]],
    "edhc-biens": [["Bien public", "Bien qui appartient à la collectivité et sert à tous.", "Les tables-bancs, les routes, les lampadaires."],
      ["Vandalisme", "Destruction volontaire de biens.", "Casser les lampes de la classe."],
      ["Collectivité", "Ensemble des personnes qui vivent dans un même lieu.", "Les habitants d'une commune."],
      ["Civisme", "Respect des règles et des biens communs par le citoyen.", "Jeter ses déchets dans la poubelle."]],
    "edhc-entreprise": [["Entreprise", "Organisation qui produit des biens ou des services pour les vendre.", "Un atelier de couture, un maquis."],
      ["Étude de marché", "Enquête pour connaître les clients, les concurrents et les prix.", "Demander aux voisins s'ils achèteraient du jus de bissap."],
      ["Plan d'affaires", "Document qui décrit le projet, ses coûts et ses recettes prévues.", "Présenté à une microfinance pour obtenir un prêt."],
      ["Insertion sociale", "Fait de trouver sa place dans la société, notamment par le travail.", "Un jeune qui ouvre son atelier de soudure."]],
    "edhc-alliances": [["Cohésion sociale", "Entente et solidarité entre les membres d'une société.", "Les communautés qui vivent en paix dans un quartier."],
      ["Alliance à plaisanterie", "Pacte ancien entre peuples qui autorise la taquinerie et impose l'entraide.", "Entre certains peuples Mandé et Gour."],
      ["Ethnie", "Groupe humain qui partage une langue, une culture et des traditions.", "Les Sénoufo, les Baoulé, les Bété."],
      ["Tolérance", "Acceptation des différences des autres.", "Respecter les coutumes d'une autre ethnie."]],
    "edhc-sante": [["Automédication", "Fait de se soigner soi-même sans avis médical.", "Prendre n'importe quel comprimé contre la fièvre."],
      ["Ordonnance", "Document rédigé par un médecin qui indique les médicaments et les doses.", "Présentée à la pharmacie."],
      ["Médicament de la rue", "Médicament vendu hors des pharmacies, souvent faux ou périmé.", "Des comprimés vendus au marché ou dans les cars."],
      ["CMU", "Couverture maladie universelle : système qui aide à payer les soins.", "La carte CMU."]],
    "edhc-depistage": [["Dépistage", "Test qui permet de savoir si l'on est porteur d'une maladie.", "Le test du VIH, gratuit et confidentiel."],
      ["Confidentialité", "Fait de garder secrète une information personnelle.", "Le résultat du test n'est donné qu'à la personne."],
      ["Stigmatisation", "Fait de rejeter ou de montrer du doigt une personne.", "Refuser de manger avec une personne vivant avec le VIH."],
      ["PTME", "Prévention de la transmission du VIH de la mère à l'enfant.", "Grâce aux ARV, le bébé naît sans le virus."]],
    "edhc-parcs": [["Parc national", "Espace naturel protégé par l'État pour préserver la faune et la flore.", "Le parc national de Taï."],
      ["Biodiversité", "Diversité des espèces vivantes dans un milieu.", "Chimpanzés, éléphants, hippopotames pygmées de Taï."],
      ["Braconnage", "Chasse ou pêche illégale.", "Tuer des éléphants pour leur ivoire."],
      ["Patrimoine mondial", "Site reconnu par l'UNESCO pour sa valeur exceptionnelle.", "Taï, la Comoé et le mont Nimba."]],
    "edhc-eau": [["Eau potable", "Eau qu'on peut boire sans danger pour la santé.", "L'eau distribuée par la SODECI."],
      ["Gaspillage", "Utilisation excessive ou inutile d'une ressource.", "Laisser couler le robinet."],
      ["Ressource naturelle", "Richesse fournie par la nature, parfois limitée.", "L'eau, le bois, le sol."],
      ["Paix sociale", "Situation où les membres d'une communauté vivent sans conflit.", "Respecter les tours à la borne-fontaine."]]
  });
  Object.assign(MOTS, {
    // ---------------- Français ----------------
    "fr-dictee": [["Participe passé", "Forme du verbe utilisée avec un auxiliaire (être ou avoir) ou comme adjectif.", "« mangé », « partie », « écrites »."],
      ["COD (complément d'objet direct)", "Complément du verbe sans préposition ; il répond à « quoi ? » ou « qui ? ».", "« J'ai cueilli <b>les mangues</b>. »"],
      ["Homophones", "Mots qui se prononcent pareil mais s'écrivent différemment.", "a / à, on / ont, ces / ses."],
      ["Accord", "Changement de forme d'un mot selon le genre et le nombre du mot auquel il se rapporte.", "« des robes blanches »."]],
    "fr-communication": [["Émetteur", "Celui qui envoie le message.", "Le proviseur qui écrit aux parents."],
      ["Récepteur", "Celui qui reçoit le message.", "Les parents qui lisent la note."],
      ["Registre de langue", "Manière de parler adaptée à la situation : soutenu, courant ou familier.", "« Je suis épuisé » (soutenu), « je suis fatigué » (courant), « je suis crevé » (familier)."],
      ["Modalité de phrase", "Type de phrase selon l'intention : déclarative, interrogative, injonctive, exclamative.", "« Ferme la porte ! » est injonctive."]],
    "fr-pronoms": [["Pronom", "Mot qui remplace un nom ou un groupe nominal.", "« Awa lit. <b>Elle</b> aime lire. »"],
      ["Pronominalisation", "Remplacement d'un groupe de mots par un pronom pour éviter les répétitions.", "« Je donne le livre à Koffi » → « Je <b>le lui</b> donne. »"],
      ["Pronom relatif", "Pronom qui relie une proposition à un nom : qui, que, dont, où, lequel.", "« Le village <b>où</b> je suis né. »"],
      ["Antécédent", "Nom que remplace le pronom relatif.", "Dans « le livre que je lis », l'antécédent est « livre »."]],
    "fr-adverbe": [["Adverbe", "Mot invariable qui modifie le sens d'un verbe, d'un adjectif ou d'un autre adverbe.", "« Il court <b>vite</b>. »"],
      ["Locution adverbiale", "Groupe de mots qui joue le rôle d'un adverbe.", "« tout à fait », « peu à peu »."],
      ["Degré de l'adverbe", "Variation d'intensité : comparatif ou superlatif.", "« plus vite », « le plus vite »."],
      ["Invariable", "Qui ne change jamais de forme.", "« Elles parlent doucement » (pas de s à doucement)."]],
    "fr-infinitif": [["Infinitif", "Forme du verbe non conjuguée, qui sert de nom au verbe.", "« chanter », « finir », « prendre »."],
      ["Participe présent", "Forme en -ant, invariable, qui exprime une action.", "« Des élèves <b>obéissant</b> à leur maître. »"],
      ["Adjectif verbal", "Adjectif formé sur un verbe, qui s'accorde et exprime une qualité.", "« Des élèves <b>obéissants</b>. »"],
      ["Gérondif", "En + participe présent : il exprime la manière ou le temps.", "« Il révise <b>en écoutant</b> de la musique. »"]],
    "fr-coordination": [["Coordination", "Liaison de deux éléments de même fonction par une conjonction de coordination.", "« Il est fatigué <b>mais</b> il travaille. »"],
      ["Conjonction de coordination", "Mot invariable qui relie : mais, ou, et, donc, or, ni, car.", "« Il pleut, <b>donc</b> je reste. »"],
      ["Connecteur logique", "Mot qui marque le lien entre deux idées (cause, conséquence, opposition…).", "cependant, en effet, ainsi."],
      ["Proposition indépendante", "Proposition qui a un sens complet toute seule.", "« Je mange » ; « tu dors »."]],
    "fr-circonstances": [["Proposition subordonnée", "Proposition qui dépend d'une autre (la principale) et commence par un subordonnant.", "« Je reste <b>parce qu'il pleut</b>. »"],
      ["Circonstance", "Information sur la cause, le but, le temps, la condition, l'opposition…", "« <b>Pour réussir</b>, il travaille » (but)."],
      ["Subordonnant", "Mot qui introduit une subordonnée.", "parce que, afin que, bien que, quand, si."],
      ["Concession", "Idée qu'on reconnaît avant d'affirmer le contraire.", "« <b>Bien qu'il</b> soit fatigué, il vient. »"]],
    "fr-ortho-lexicale": [["Homophones", "Mots qui se prononcent pareil mais s'écrivent différemment.", "sans / s'en / sang ; peu / peut."],
      ["Paronymes", "Mots presque identiques par la forme mais de sens différent.", "« éminent » (remarquable) et « imminent » (tout proche)."],
      ["Orthographe lexicale", "Orthographe des mots eux-mêmes, telle qu'elle est dans le dictionnaire.", "On écrit « fatigant » (adjectif) sans u."],
      ["Quel que / quelque", "« Quel que » + verbe être (accordé) ; « quelque » devant un nom (= un certain, plusieurs).", "« Quelles que soient tes difficultés » ; « quelques livres »."]],
    "fr-ortho-grammaticale": [["Orthographe grammaticale", "Orthographe des accords (verbe, adjectif, participe…).", "« Les filles sont arrivées. »"],
      ["Auxiliaire", "Verbe être ou avoir qui sert à conjuguer aux temps composés.", "« Il <b>a</b> mangé », « elle <b>est</b> partie »."],
      ["Adverbe « tout »", "Invariable (= très, entièrement), sauf devant un adjectif féminin commençant par une consonne.", "« Ils sont tout contents » ; « elle est toute contente »."],
      ["Adjectif qualificatif", "Mot qui donne une qualité au nom et s'accorde avec lui.", "« une robe <b>blanche</b> »."]],
    "fr-methodes": [["Texte argumentatif", "Texte qui cherche à convaincre en défendant une opinion par des arguments.", "Un article pour ou contre le téléphone à l'école."],
      ["Résumé", "Texte plus court qui garde toutes les idées essentielles, dans l'ordre, avec ses propres mots.", "Un texte de 240 mots résumé en 60 mots."],
      ["Article de journal", "Texte qui informe sur un fait réel et récent.", "Un article sur la journée de salubrité du lycée."],
      ["Plan", "Organisation des idées d'un texte en parties.", "Introduction, développement, conclusion."]],
    "fr-argu-atelier": [["Thèse", "L'opinion que l'auteur défend.", "« L'uniforme scolaire devrait être obligatoire. »"],
      ["Argument", "Idée qui prouve ou justifie la thèse.", "« L'uniforme évite les inégalités entre élèves. »"],
      ["Exemple", "Cas précis et réel qui illustre un argument.", "« Au lycée de Daloa, depuis l'uniforme, plus personne ne se moque des vêtements des autres. »"],
      ["Étayer", "Soutenir une thèse avec des arguments et des exemples.", "Défendre l'idée qu'il faut lire tous les jours."],
      ["Réfuter", "Montrer qu'une opinion est fausse ou exagérée, avec des arguments.", "Répondre à « L'école ne sert à rien » en montrant qu'elle ouvre l'accès aux métiers."],
      ["Connecteur", "Mot qui relie les idées et montre leur lien logique.", "d'abord, en effet, par exemple, cependant, donc."]],
    "fr-resume-atelier": [["Résumer", "Réduire un texte en gardant ses idées essentielles, dans l'ordre, avec ses mots.", "Réduire un texte de 200 mots à 50 mots."],
      ["Reformuler", "Dire la même idée avec d'autres mots, plus courts.", "« l'élève est plus détendu et plus attentif en classe » → « il favorise l'attention »."],
      ["Idée essentielle", "Idée indispensable pour comprendre le texte : thèse, arguments, conclusion.", "« Le sport entretient la santé. »"],
      ["Système d'énonciation", "Qui parle dans le texte (je, nous, on) : le résumé le garde.", "Si l'auteur dit « nous », le résumé dit aussi « nous »."]],
    "fr-article-atelier": [["Chapeau", "Court texte sous le titre qui résume l'essentiel de l'article.", "« Samedi, 300 élèves ont nettoyé leur école. Objectif : un cadre sain. »"],
      ["Attaque", "Première phrase de l'article, qui accroche le lecteur.", "« Dès 7 heures, balais en main, les élèves étaient au rendez-vous. »"],
      ["Chute", "Fin de l'article, qui ouvre sur la suite.", "« Rendez-vous est déjà pris pour le mois prochain. »"],
      ["Citation", "Paroles exactes d'une personne, placées entre guillemets.", "« Chaque élève est responsable d'un arbre », explique le proviseur."]],
    // ---------------- Anglais ----------------
    "en-oral-bepc": [["Describe", "Décrire : dire ce que l'on voit, avec des détails.", "« In the picture, I can see a market. »"],
      ["Foreground / background", "Premier plan (devant) / arrière-plan (au fond) d'une image.", "« In the background, there are houses. »"],
      ["Present continuous", "Temps utilisé pour décrire une action en cours : be + V-ing.", "« A woman is selling mangoes. »"],
      ["Summary", "Résumé : dire l'essentiel d'un texte avec ses mots.", "« This text is about malaria. »"]],
    "en-present": [["Present simple", "Temps des habitudes et des vérités générales.", "« I go to school every day. »"],
      ["Present continuous", "Temps des actions en cours : be + V-ing.", "« Look! They are playing football. »"],
      ["Third person", "He, she, it : au present simple, le verbe prend un -s.", "« She lives in Man. »"],
      ["Auxiliary do / does", "Mot qui sert à faire les questions et les négations au present simple.", "« Does he work? — No, he doesn't. »"]],
    "en-past": [["Past simple", "Temps d'une action terminée dans le passé.", "« We went to Bassam yesterday. »"],
      ["Regular verb", "Verbe qui fait son passé en -ed.", "play → played."],
      ["Irregular verb", "Verbe dont le passé est une forme à apprendre par cœur.", "go → went → gone."],
      ["Past continuous", "Action en cours dans le passé : was / were + V-ing.", "« I was reading when he arrived. »"]],
    "en-perfect": [["Present perfect", "Temps qui relie le passé au présent : have / has + participe passé.", "« I have finished my homework. »"],
      ["Past participle", "Troisième forme du verbe, utilisée avec have.", "write → wrote → <b>written</b>."],
      ["For", "« Depuis » suivi d'une durée.", "« for three years »."],
      ["Since", "« Depuis » suivi d'un point de départ.", "« since 2020 »."]],
    "en-future": [["Will", "Auxiliaire du futur : décision spontanée ou prédiction.", "« I will help you. »"],
      ["Be going to", "Futur proche ou projet déjà décidé.", "« I am going to study medicine. »"],
      ["Conditional", "Phrase avec « if » qui exprime une condition.", "« If you work, you will pass. »"],
      ["If-clause", "Partie de la phrase qui commence par « if » ; jamais de « will » dedans (type 1).", "« If it rains, we will stay home. »"]],
    "en-modals": [["Modal verb", "Verbe (can, must, should, may…) qui exprime capacité, obligation, conseil ou possibilité.", "« You should rest. »"],
      ["Obligation", "Ce qu'on est obligé de faire : must / have to.", "« Pupils must wear a uniform. »"],
      ["Prohibition", "Interdiction : mustn't.", "« You mustn't smoke here. »"],
      ["Advice", "Conseil : should.", "« You should sleep early. »"]],
    "en-compare": [["Comparative", "Forme pour comparer deux éléments : -er than / more … than.", "« Abidjan is bigger than Bouaké. »"],
      ["Superlative", "Forme pour dire « le plus » : the -est / the most.", "« the highest mountain »."],
      ["Short adjective", "Adjectif d'une syllabe (ou deux terminées par -y) : on ajoute -er / -est.", "tall → taller → the tallest."],
      ["Long adjective", "Adjectif de deux syllabes ou plus : more / the most.", "difficult → more difficult."]],
    "en-passive": [["Passive voice", "Tournure où le sujet subit l'action : be + participe passé.", "« Cocoa is grown in Côte d'Ivoire. »"],
      ["Active voice", "Tournure où le sujet fait l'action.", "« Farmers grow cocoa. »"],
      ["Reported speech", "Discours rapporté : on répète ce que quelqu'un a dit, en changeant les temps.", "He said: « I am tired » → He said he was tired."],
      ["Agent", "Celui qui fait l'action dans une phrase passive, introduit par « by ».", "« The window was broken <b>by the boy</b>. »"]],
    "en-relatives": [["Relative pronoun", "Pronom qui relie une proposition à un nom : who, which, whose, where.", "« The man who lives here. »"],
      ["Question tag", "Petite question à la fin d'une phrase pour demander confirmation.", "« You like football, <b>don't you</b>? »"],
      ["Linking word", "Mot de liaison entre deux idées.", "because, but, so, although, however."],
      ["Whose", "Pronom relatif de la possession.", "« The girl whose father is a doctor. »"]],
    "en-oral": [["Greeting", "Salutation.", "« Good morning, sir. »"],
      ["Introduce yourself", "Se présenter.", "« My name is Adriel. I am in form three. »"],
      ["Opinion", "Avis personnel.", "« In my opinion, sport is important. »"],
      ["Polite request", "Demande polie.", "« Could you repeat, please? »"]],
    // ---------------- Espagnol ----------------
    "es-presentarse": [["Saludo", "Salutation.", "¡Buenos días!"],
      ["Presentarse", "Se présenter.", "Me llamo Adriel y tengo quince años."],
      ["Nacionalidad", "Nationalité.", "Soy marfileño."],
      ["Edad", "Âge : on l'exprime avec « tener ».", "Tengo quince años."]],
    "es-ser-estar": [["Ser", "Verbe « être » pour l'identité, la nationalité, la profession, le caractère.", "Soy alumno. Es alto."],
      ["Estar", "Verbe « être » pour le lieu et les états passagers.", "Estoy en casa. Estoy cansado."],
      ["Gerundio", "Forme en -ando / -iendo ; avec estar, action en cours.", "Estoy estudiando."],
      ["Estado", "État (passager).", "Mi madre está enferma hoy."]],
    "es-presente": [["Presente", "Temps des actions actuelles et des habitudes.", "Como arroz todos los días."],
      ["Verbo regular", "Verbe qui suit les terminaisons habituelles (-ar, -er, -ir).", "hablar → hablo."],
      ["Verbo irregular", "Verbe qui change de forme.", "tener → tengo ; ir → voy."],
      ["Diptongo", "Changement de voyelle dans le radical : e → ie, o → ue.", "querer → quiero ; poder → puedo."]],
    "es-gustar": [["Gustar", "Plaire : sert à dire ce qu'on aime.", "Me gusta el fútbol."],
      ["Encantar", "Adorer.", "Me encantan los mangos."],
      ["Preferir", "Préférer (e → ie).", "Prefiero el arroz."],
      ["Pronombre (me, te, le…)", "Pronom qui indique à qui la chose plaît.", "A mi hermano <b>le</b> gusta leer."]],
    "es-pasado": [["Pretérito indefinido", "Passé simple espagnol : action terminée dans le passé.", "Ayer hablé con mi abuela."],
      ["Ayer", "Hier : mot qui annonce souvent le passé.", "Ayer fui al mercado."],
      ["Fui", "Passé de « ser » et de « ir » à la 1re personne.", "Fui a Man el año pasado."],
      ["Hice", "Passé de « hacer » (je fis).", "Hice mis deberes."]],
    "es-futuro": [["Futuro", "Temps des actions à venir : infinitif + é, ás, á…", "Pasaré el BEPC."],
      ["Ir a + infinitivo", "Futur proche.", "Voy a estudiar."],
      ["Proyecto", "Projet.", "Quiero ser médico."],
      ["Mañana", "Demain (ou matin).", "Mañana voy al colegio."]],
    // ---------------- Arts et musique ----------------
    "art-couleurs": [["Couleur primaire", "Couleur qu'on ne peut pas obtenir par mélange.", "Le rouge, le jaune, le bleu."],
      ["Couleur secondaire", "Couleur obtenue en mélangeant deux primaires.", "Jaune + bleu = vert."],
      ["Couleurs complémentaires", "Une primaire et la secondaire faite des deux autres ; elles se renforcent côte à côte.", "Le rouge et le vert."],
      ["Camaïeu", "Peinture en plusieurs nuances d'une seule couleur.", "Un paysage peint seulement en bleus."]],
    "art-dessin": [["Perspective", "Technique qui donne l'illusion de la profondeur sur une surface plate.", "Une route qui rétrécit vers l'horizon."],
      ["Point de fuite", "Point où se rejoignent les lignes qui s'éloignent.", "Le bout de la route au loin."],
      ["Ligne d'horizon", "Ligne à hauteur des yeux où le ciel semble toucher la terre.", "La limite entre la mer et le ciel à Bassam."],
      ["Composition", "Organisation des éléments dans une image.", "Placer le personnage principal au premier plan."]],
    "art-patrimoine": [["Patrimoine", "Ensemble des biens culturels hérités des ancêtres.", "Les masques, les pagnes, les danses traditionnelles."],
      ["Masque", "Objet rituel qui cache le visage, utilisé lors de cérémonies.", "Les masques dan de la région de Man."],
      ["Tissage", "Fabrication d'un tissu en entrecroisant des fils.", "Le pagne Kita des Baoulé."],
      ["Artisanat", "Production d'objets faits à la main.", "La poterie de Katiola."]],
    "mus-solfege": [["Portée", "Ensemble de 5 lignes sur lesquelles on écrit les notes.", "Les notes do, ré, mi… sont placées sur la portée."],
      ["Clé de sol", "Signe placé au début de la portée qui fixe le nom des notes.", "Le sol se trouve sur la 2e ligne."],
      ["Mesure", "Groupe de temps séparé par des barres.", "Une mesure à 4 temps."],
      ["Tempo", "Vitesse d'exécution d'un morceau.", "Allegro (rapide), adagio (lent)."]],
    "mus-instruments": [["Instrument à cordes", "Instrument dont on fait vibrer des cordes.", "La kora, la guitare."],
      ["Instrument à vent", "Instrument dans lequel on souffle.", "La flûte, la trompette."],
      ["Percussion", "Instrument qu'on frappe.", "Le djembé, le balafon, le tam-tam."],
      ["Tambour parleur", "Tambour qui imite les sons de la langue pour transmettre des messages.", "L'attoungblan des Akan."]],
    // ---------------- EPS ----------------
    "eps-sante": [["Échauffement", "Exercices progressifs qui préparent le corps à l'effort.", "Trottiner, mobiliser les articulations, s'étirer."],
      ["Hydratation", "Fait de boire assez d'eau.", "Boire avant, pendant et après l'effort."],
      ["Récupération", "Retour au calme après l'effort.", "Marcher, s'étirer doucement."],
      ["Endurance", "Capacité à faire un effort longtemps.", "Courir 20 minutes sans s'arrêter."]],
    "eps-courses": [["Sprint", "Course de vitesse sur une courte distance.", "Le 80 m ou le 100 m."],
      ["Demi-fond", "Course de distance moyenne (souvent 800 m à 1 500 m).", "Le 1 000 m."],
      ["Faux départ", "Départ avant le signal.", "Il peut entraîner l'élimination."],
      ["Témoin", "Bâton que les coureurs d'un relais se passent.", "Il doit être transmis dans la zone de transmission."]],
    "eps-sauts-lancers": [["Appel", "Impulsion donnée par un pied pour sauter.", "La planche d'appel au saut en longueur."],
      ["Course d'élan", "Course avant le saut ou le lancer, pour prendre de la vitesse.", "8 à 12 foulées en longueur."],
      ["Essai nul", "Essai qui ne compte pas.", "Mordre la planche au saut en longueur."],
      ["Butoir", "Pièce à l'avant du cercle de lancer qu'on ne doit pas dépasser.", "Au lancer de poids."]],
    "eps-sports-co": [["Sport collectif", "Sport qui se pratique en équipe.", "Football, handball, basket, volley."],
      ["Fair-play", "Respect des règles, de l'adversaire et de l'arbitre.", "Serrer la main de l'adversaire après le match."],
      ["Arbitre", "Personne qui fait respecter les règles du jeu.", "Il siffle les fautes."],
      ["Hors-jeu", "Au football, position interdite d'un attaquant au moment de la passe.", "L'arbitre assistant lève son drapeau."]]
  });
