  // Dictionnaire espagnol → français (formes conjuguées incluses)
  const DICO_ES_BRUT = `a=à
abiyán=Abidjan (en espagnol)
abuela=grand-mère
africano=africain
ahora=maintenant
al=au (a + el)
alto=grand (de taille), haut
alumno=élève
arroz=riz
asignatura=matière (à l'école)
ayer=hier
ayudo=j'aide (ayudar)
año=année, an
años=ans, années (tengo 14 años = j'ai 14 ans)
bailar=danser
bicicleta=vélo
buenas noches=bonsoir, bonne nuit
buenas=bonnes (buenas tardes = bonjour l'après-midi)
buenos días=bonjour (le matin)
buenos=bons
cansado=fatigué
carta=lettre
casa=maison
catorce=quatorze
centro=centre
cinco=cinq
cincuenta=cinquante
ciudad=ville
clase=classe, cours
colegio=collège
comemos=nous mangeons (comer)
comen=ils / elles mangent (comer)
comer=manger
comida=repas, nourriture
comieron=ils / elles mangèrent, ont mangé (comer, passé)
comimos=nous mangeâmes, avons mangé (comer, passé)
comió=il / elle mangea, a mangé (comer, passé)
como=comme ; je mange (comer)
con=avec
conjuga=conjugue
contesta=réponds
costeño=✗ faux ami : costeño veut dire « de la côte », pas « ivoirien » (on dit marfileño)
cuántos=combien (cuántos años tienes = quel âge as-tu)
de=de
deberes=devoirs
del=du (de + el)
después=après, ensuite
día=jour
días=jours
dónde=où
edad=âge
el=le
él=il, lui
ella=elle
ellos=ils, eux
en=en, dans, à
encanta=j'adore (me encanta = j'adore, avec un nom singulier)
encantan=j'adore (me encantan, avec un nom pluriel)
enferma=malade (fille)
enfermo=malade (garçon)
eres=tu es (ser)
es=il / elle est ; c'est (ser)
escribe=écris ; il / elle écrit (escribir)
escribir=écrire
escribió=il / elle écrivit, a écrit (escribir, passé)
escribí=j'écrivis, j'ai écrit (escribir, passé)
escribía=j'écrivais, il écrivait (escribir, imparfait)
español=espagnol
estaba=j'étais, il / elle était (estar, imparfait)
estamos=nous sommes (estar : état, lieu)
estar=être (état passager, lieu)
estoy=je suis (estar : état, lieu)
estudiando=en train d'étudier (estar + gérondif)
estudiar=étudier
estuve=je fus, j'ai été (estar, passé)
estuvo=il / elle fut, a été (estar, passé)
está=il / elle est (estar)
están=ils / elles sont (estar)
estás=tu es (estar)
frases=phrases
frutas=fruits
fueron=ils allèrent / furent (ir ou ser, passé)
fui=j'allai, je suis allé (ir) ; je fus (ser)
fuimos=nous allâmes, sommes allés (ir, passé)
fútbol=football
gusta=plaît (me gusta = j'aime, avec un nom singulier ou un verbe)
gustamos=✗ forme fausse ici : pour « j'aime » on dit me gusta / me gustan
gustan=plaisent (me gustan = j'aime, avec un nom pluriel)
gustas=tu plais
gusto=goût ; mucho gusto = enchanté
gustos=goûts
habla=il / elle parle (hablar)
hablaba=je parlais, il / elle parlait (hablar, imparfait)
hablamos=nous parlons (hablar)
hablar=parler
hablas=tu parles (hablar)
hablo=je parle (hablar)
hablé=je parlai, j'ai parlé (hablar, passé)
habló=il / elle parla, a parlé (hablar, passé)
hace=il / elle fait (hacer) ; hace calor = il fait chaud
hacer=faire
hacerá=✗ forme fausse : le futur de hacer est haré, hará
haco=✗ forme fausse : « je fais » se dit hago
hací=✗ forme fausse : « je fis » se dit hice
hago=je fais (hacer)
hará=il / elle fera (hacer, futur)
hasta=jusqu'à (hasta luego = à plus tard)
hay=il y a
hermano=frère
hice=je fis, j'ai fait (hacer, passé)
historia=histoire
hizo=il / elle fit, a fait (hacer, passé)
hoy=aujourd'hui
iba=j'allais, il / elle allait (ir, imparfait)
ingeniera=ingénieure
ir=aller
iré=j'irai (ir, futur)
ivoriano=✗ mot inventé : « ivoirien » se dit marfileño
la=la
las=les (féminin)
leer=lire
liceo=lycée
llamo=je m'appelle (me llamo, llamarse)
los=les (masculin)
madre=mère
mangos=mangues
marfileño=ivoirien
marfileños=ivoiriens
matemáticas=mathématiques
mañana=demain ; matin (por la mañana = le matin)
me=me, moi
mercado=marché
mi=mon, ma
mí=moi (a mí = à moi)
mis=mes
mucho=beaucoup
música=musique
muy=très
médica=médecin (femme)
médico=médecin
nada=rien
no=non ; ne… pas
noches=nuits (buenas noches = bonsoir)
nombre=nom, prénom
nos=nous
nosotros=nous
os=vous (complément)
padre=père
padres=parents
pasaba=passait (pasar, imparfait)
pasada=dernière, passée (la semana pasada = la semaine dernière)
pasado=passé, dernier (el año pasado = l'année dernière)
pasar=passer
pasaré=je passerai (pasar, futur)
paso=je passe (pasar)
pasé=je passai, j'ai passé (pasar, passé)
país=pays
pequeño=petit
pero=mais
pescado=poisson (à manger)
pie=pied (a pie = à pied)
poder=pouvoir
podo=✗ forme fausse : « je peux » se dit puedo
pon=mets
por=par, pour (por la mañana = le matin)
porque=parce que
prefiero=je préfère (preferir)
presente=présent
preséntate=présente-toi
profesor=professeur
proyecto=projet
próximo=prochain
pudo=il / elle put, a pu (poder, passé)
puede=il / elle peut (poder)
puedo=je peux (poder)
puerto=port
quere=✗ forme fausse : « il veut » se dit quiere
querer=vouloir, aimer
qué=que, quoi, quel
quiere=il / elle veut (querer)
quiero=je veux (querer)
quince=quinze
se=se
semana=semaine
ser=être (identité, caractère)
somos=nous sommes (ser)
son=ils / elles sont (ser) ; son las ocho = il est huit heures
soy=je suis (ser)
tal=tel ; ¿qué tal? = comment ça va ?
tarde=après-midi ; tard
te=te, toi
tendré=j'aurai (tener, futur)
tener=avoir
teneré=✗ forme fausse : le futur de tener est tendré
tenes=✗ forme fausse : « tu as » se dit tienes
tengo=j'ai (tener)
tercero=troisième (tercero de secundaria = la 3e)
texto=texte
tiene=il / elle a (tener)
tienes=tu as (tener)
todo=tout
todos=tous (todos los días = tous les jours)
trabajo=travail ; je travaille
tuve=j'eus, j'ai eu (tener, passé)
tío=oncle
tú=tu, toi
tu=ton, ta
un=un
una=une
va=il / elle va (ir)
vacaciones=vacances
vais=vous allez (ir)
vamos=nous allons (ir)
vas=tu vas (ir)
vendemos=nous vendons (vender)
verduras=légumes
viajamos=nous voyageons ; nous avons voyagé (viajar)
viajar=voyager
viajaremos=nous voyagerons (viajar, futur)
viajaron=ils / elles voyagèrent, ont voyagé (viajar, passé)
viajábamos=nous voyagions (viajar, imparfait)
visité=je visitai, j'ai visité (visitar, passé)
vive=il / elle vit, habite (vivir)
vivemos=✗ forme fausse : « nous vivons » se dit vivimos
viven=ils / elles vivent (vivir)
vivimos=nous vivons (vivir)
vivir=vivre, habiter
vivo=je vis, j'habite (vivir)
voy=je vais (ir) ; voy a + verbe = je vais (futur proche)
y=et
yo=je, moi
íbamos=nous allions (ir, imparfait)
aya=Aya (prénom)
bouaké=Bouaké (ville)
yamoussoukro=Yamoussoukro (capitale)
salir=sortir, partir
llamas=tu t'appelles (te llamas)
llama=il / elle s'appelle (se llama)
vives=tu vis, tu habites (vivir)
curso=classe, année scolaire
bien=bien
gracias=merci
familia=famille
tardes=après-midi (buenas tardes = bon après-midi)
sois=vous êtes (ser)
estáis=vous êtes (estar)
sur=sud
ocho=huit
siete=sept
tres=trois
dos=deux
dieciséis=seize
para=pour
profesora=professeure
hermana=sœur
hermanas=sœurs
hermanos=frères ; frères et sœurs
ingeniero=ingénieur
examen=examen
escuela=école
cerca=près (cerca de = près de)
alumnos=élèves
comes=tu manges (comer)
come=il / elle mange (comer)
habláis=vous parlez (hablar)
coméis=vous mangez (comer)
vivís=vous vivez (vivir)
hablan=ils / elles parlent (hablar)
haces=tu fais (hacer)
hacemos=nous faisons (hacer)
hacen=ils / elles font (hacer)
tenemos=nous avons (tener)
tienen=ils / elles ont (tener)
van=ils / elles vont (ir)
puedes=tu peux (poder)
podemos=nous pouvons (poder)
pueden=ils / elles peuvent (poder)
quieres=tu veux (querer)
queremos=nous voulons (querer)
quieren=ils / elles veulent (querer)
francés=français
poco=peu (un poco = un peu)
autobús=bus
ayudarme=m'aider
ayudar=aider
teno=✗ forme fausse : « j'ai » se dit tengo
sábados=samedis (los sábados = le samedi)
sábado=samedi
domingo=dimanche
venir=venir
enfermera=infirmière
enfermero=infirmier
cantina=cantine
cada=chaque
noche=nuit, soir
ti=toi (a ti = à toi)
le=lui (le gusta = il / elle aime)
les=leur (les gusta = ils / elles aiment)
vosotros=vous
lluvia=pluie
encanto=✗ forme fausse ici : « j'adore » se dit me encanta
africana=africaine
baloncesto=basket-ball
cocinar=cuisiner
deportes=sports
comí=je mangeai, j'ai mangé (comer, passé)
viví=je vécus, j'ai vécu (vivir, passé)
hablaste=tu parlas, tu as parlé (hablar, passé)
comiste=tu mangeas, tu as mangé (comer, passé)
viviste=tu vécus, tu as vécu (vivir, passé)
vivió=il / elle vécut, a vécu (vivir, passé)
hablasteis=vous avez parlé (hablar, passé)
comisteis=vous avez mangé (comer, passé)
vivisteis=vous avez vécu (vivir, passé)
hablaron=ils / elles ont parlé (hablar, passé)
vivieron=ils / elles ont vécu (vivir, passé)
fuiste=tu allas, tu es allé ; tu fus (ir / ser, passé)
fue=il / elle alla, est allé ; fut (ir / ser, passé)
tuviste=tu as eu (tener, passé)
tuvo=il / elle a eu (tener, passé)
tuvimos=nous avons eu (tener, passé)
tuvieron=ils / elles ont eu (tener, passé)
hiciste=tu as fait (hacer, passé)
hicimos=nous avons fait (hacer, passé)
hicieron=ils / elles ont fait (hacer, passé)
estuviste=tu as été (estar, passé)
estuvimos=nous avons été (estar, passé)
estuvieron=ils / elles ont été (estar, passé)
hació=✗ forme fausse : « il a fait » se dit hizo
tení=✗ forme fausse : « j'ai eu » se dit tuve
buena=bonne
nota=note
visitamos=nous visitons ; nous avons visité (visitar)
nuestros=nos
abuelos=grands-parents
amigos=amis
trabajó=il / elle a travaillé (trabajar, passé)
hablaré=je parlerai (hablar, futur)
comeré=je mangerai (comer, futur)
viviré=je vivrai, j'habiterai (vivir, futur)
hablarás=tu parleras (hablar, futur)
comerás=tu mangeras (comer, futur)
vivirás=tu vivras (vivir, futur)
hablará=il / elle parlera (hablar, futur)
comerá=il / elle mangera (comer, futur)
vivirá=il / elle vivra (vivir, futur)
hablaremos=nous parlerons (hablar, futur)
comeremos=nous mangerons (comer, futur)
viviremos=nous vivrons, nous habiterons (vivir, futur)
hablaréis=vous parlerez (hablar, futur)
comeréis=vous mangerez (comer, futur)
viviréis=vous vivrez (vivir, futur)
hablarán=ils / elles parleront (hablar, futur)
comerán=ils / elles mangeront (comer, futur)
vivirán=ils / elles vivront (vivir, futur)
haré=je ferai (hacer, futur)
harás=tu feras (hacer, futur)
podré=je pourrai (poder, futur)
saldré=je sortirai (salir, futur)
decir=dire
diré=je dirai (decir, futur)
vendré=je viendrai (venir, futur)
abogado=avocat
abogada=avocate
periodista=journaliste
futbolista=footballeur
sea=sois, soit (cuando sea mayor = quand je serai grand)
mayor=plus grand, adulte
lloverá=il pleuvra (llover, futur)
llover=pleuvoir
jugar=jouer
seré=je serai (ser, futur)
director=directeur
mayo=mai
iremos=nous irons (ir, futur)
playa=plage`;
