  // =========================================================
  // Dictionnaire anglais → français intégré (hors ligne). Une ligne = mot=traduction
  // =========================================================
  const DICO_EN_BRUT = `a=un, une
about=à propos de, sur ; environ
above=au-dessus de
absorb=absorber
according to=selon
act=agir
active=actif (la voix active)
activities=activités
activity=activité
addicted=dépendant (à une drogue)
addiction=dépendance, addiction
adjective=adjectif
adult=adulte
advice=conseil(s)
africa=Afrique
after=après
afternoon=après-midi
against=contre
agent=agent (celui qui fait l'action)
ago=il y a (dans le passé) : two years ago = il y a deux ans
ai=IA (intelligence artificielle)
all=tout, tous, toutes
allow=permettre, autoriser
almost=presque
already=déjà
also=aussi
although=bien que
always=toujours
am=suis (I am = je suis)
america=Amérique
an=un, une (devant une voyelle)
and=et
animal=animal
another=un autre, une autre
answer=réponse ; répondre
apple=pomme
app=application
apps=applications (sur le téléphone)
are=es, sommes, êtes, sont (verbe be)
area=zone, quartier
aren't=ne sont pas (are not)
arm=bras
around=autour de
arrive=arriver
as=comme ; aussi… que (as tall as = aussi grand que)
asia=Asie
ask=demander ; poser (une question)
at=à
ate=mangea, a mangé (passé de eat)
attention=attention
august=août
auxiliary=auxiliaire
avoid=éviter
baby=bébé
background=arrière-plan (au fond de l'image)
bad=mauvais
badder=✗ forme fausse : le comparatif de bad est worse
bag=sac
ball=ballon, balle
banana=banane
banner=banderole
base=base (forme de base du verbe)
basket=panier
beach=plage
beat=battre (vaincre) ; battit
because=parce que
become=devenir
bed=lit
been=été (participe passé de be)
before=avant
began=commença (passé de begin)
begin=commencer
beginned=✗ forme fausse : le passé de begin est began
begun=commencé (participe passé de begin)
behind=derrière
bench=banc
best=le meilleur ; meilleur(e)s
better=meilleur, mieux
big=grand, gros
bigger=plus grand
biggest=le plus grand
bird=oiseau
birthday=anniversaire
bite=piqûre, morsure ; piquer, mordre
black=noir
blackboard=tableau noir
blocked=bouché, bloqué
blue=bleu
body=corps
boil=bouillir
book=livre
born=né (be born = naître)
borrow=emprunter
both=les deux
bottle=bouteille
bought=acheta, acheté (passé et participe de buy)
boughted=✗ forme fausse : le passé de buy est bought
boy=garçon
brain=cerveau
bread=pain
breakfast=petit-déjeuner
bridge=pont
broke=cassa (passé de break)
broken=cassé (participe passé de break)
brother=frère
brought=apporta, apporté (passé de bring) — à ne pas confondre avec bought
bucket=seau
build=construire
building=bâtiment, immeuble
built=construisit, construit (passé de build)
bus=bus, car
but=mais
buy=acheter
buyed=✗ forme fausse : le passé de buy est bought
by=par ; près de
can=pouvoir, savoir faire (I can swim = je sais nager)
can't=ne peut pas (cannot)
cans=✗ forme fausse : can ne prend jamais de -s
car=voiture
carbon dioxide=dioxyde de carbone (CO₂)
carbon=carbone
carry=porter, transporter
catch=attraper
cause=causer, provoquer ; cause
celebrate=célébrer, fêter
centre=centre
change=changement ; changer
cheap=bon marché, pas cher
cheat=tricher
check=vérifier
cheese=fromage
child=enfant
children=enfants
church=église
city=ville
cities=villes
citizen=citoyen
citizenship=citoyenneté
civic=civique
class=classe
classmate=camarade de classe
classroom=salle de classe
clause=proposition (partie de phrase)
clean=propre ; nettoyer
clean-up=nettoyage
climate=climat
close=fermer ; proche
cloud=nuage
coach=entraîneur
cocoa=cacao
code=code
cold=froid
colour=couleur
come=venir
communicate=communiquer
comparative=comparatif
complete=compléter ; complet
compulsory=obligatoire
conditional=conditionnel
confident=confiant, sûr de soi
congratulate=féliciter
consultation=consultation (chez le médecin)
continue=continuer
continuous=continu (forme en -ing : be + V-ing)
cooking=cuisine (faire la cuisine)
cool=cool, génial ; frais
cough=toux
could=pouvait, pourrait (passé ou forme polie de can)
country=pays
countries=pays (pluriel)
covered=couvert
cream=crème
cross=croix
cup=coupe (sport) ; tasse
customer=client(e)
cyberbullying=harcèlement en ligne
damage=abîmer, endommager ; dégâts
dancing=danser (la danse)
dangerous=dangereux
dark=sombre, foncé
date=date
day=jour, journée
dear=cher, chère (au début d'une lettre)
december=décembre
deforestation=déforestation
describe=décrire
desk=table, bureau (d'élève)
destroy=détruire
dictionary=dictionnaire
dictionaries=dictionnaires
did=fit, a fait (passé de do) ; auxiliaire du passé
didn't=ne… pas (au passé : did not)
die=mourir
difficult=difficile
difficulter=✗ forme fausse : on dit more difficult
dioxide=dioxyde
dirty=sale
disappear=disparaître
discipline=discipline
disease=maladie
dish=plat
do=faire ; auxiliaire des questions et négations au présent
doctor=médecin, docteur
does=fait ; auxiliaire (he / she / it) au présent
doesn't=ne… pas (does not)
don't=ne… pas (do not)
done=fait (participe passé de do)
door=porte
down=en bas, vers le bas
drain=caniveau, égout
dream=rêver ; rêve
drink=boire
drive=conduire
drop=laisser tomber, abandonner
drug=drogue ; médicament
dry=sec
dustbin=poubelle
during=pendant
each other=l'un l'autre, mutuellement
each=chaque
early=tôt
easy=facile
eat=manger
eated=✗ forme fausse : le passé de eat est ate
eaten=mangé (participe passé de eat)
education=éducation
educational=éducatif
egg=œuf
eight=huit
elephant=éléphant (the Elephants = l'équipe nationale ivoirienne)
eliminate=éliminer
end=fin ; finir
energy=énergie
engineer=ingénieur
england=Angleterre
english=anglais
environment=environnement
ethnic=ethnique
europe=Europe
even=même
evening=soir, soirée
ever=déjà (dans une question), jamais
every=chaque, tous les (every day = tous les jours)
everybody=tout le monde
exam=examen
example=exemple
exercise=exercice
expensive=cher, coûteux
explain=expliquer
export=exporter ; exportation
exposed=exposé
fail=échouer, rater (un examen)
fair play=fair-play, esprit sportif
fair=juste, loyal
fake news=fausses informations
fake=faux
false=faux
family=famille
fan=supporter, fan
farm=ferme, plantation
farmer=agriculteur, planteur
farming=agriculture
father=père
favourite=préféré
fell=tomba, a baissé (passé de fall)
female=femelle, féminin
fever=fièvre
fewer=moins de (avec un nom pluriel)
fifteen=quinze
fight=combattre, lutter contre
film=film
find=trouver
finish=finir
first=premier ; d'abord
five=cinq
flood=inondation ; inonder
fly=voler (dans l'air)
food=nourriture
football=football
footballer=footballeur
for=pour ; depuis (+ durée : for two years)
forbid=interdire
forbidden=interdit
foreground=premier plan (devant sur l'image)
forest=forêt
form three=classe de 3e
form=classe (form three = 3e) ; forme
four=quatre
fourteen=quatorze
france=France
franc=franc (monnaie)
free=libre ; gratuit
fresh=frais
friend=ami(e)
friendly=aimable, accueillant
from=de, depuis
front=devant (in front of = devant)
fruit=fruit(s)
full=plein
future=futur, avenir
game=jeu, match
garage=garage
gave=donna (passé de give)
germany=Allemagne
get up=se lever
get=obtenir, recevoir ; devenir
girl=fille
give=donner
gived=✗ forme fausse : le passé de give est gave
given=donné (participe passé de give)
go=aller
goal=but
goalkeeper=gardien de but
goes=va (he / she / it goes)
going to=aller (futur proche : I'm going to = je vais)
gone=allé (participe passé de go)
good=bon, bien
goodest=✗ forme fausse : le superlatif de good est the best
got=obtint (passé de get)
government=gouvernement
grandfather=grand-père
grandparents=grands-parents
great=grand, génial
green=vert
greeting=salutation
ground=sol, terre
group=groupe
grow=cultiver ; grandir
grower=producteur, planteur
grown=cultivé (participe passé de grow)
gutter=caniveau
had=avait, a eu (passé de have)
half past five=cinq heures et demie
half=moitié, demi
hand=main
happen=arriver, se passer
happier=plus heureux
happiest=le plus heureux
happy=heureux, content
happyer=✗ forme fausse : on écrit happier (y devient i)
hard=dur, difficile ; dur (work hard = travailler dur)
harmful=nuisible, dangereux
harvest=récolte ; récolter
has=a (he / she / it has)
hate=haïr, détester ; haine
have=avoir ; auxiliaire du present perfect
haven't=n'ai pas, n'avons pas (have not)
he=il
head=tête
headache=mal de tête
health centre=centre de santé
health=santé
hear=entendre
heavily=fortement, abondamment
heavy=lourd, fort (heavy rain = forte pluie)
hectare=hectare
helmet=casque
help=aider ; aide
her=elle, la, lui ; son, sa, ses (à elle)
here=ici
high=haut, élevé
higher=plus haut
highest=le plus haut
highway=route, autoroute
him=le, lui
his=son, sa, ses (à lui)
history=histoire
hold=tenir
holidays=vacances
home=maison, chez soi
homework=devoirs
hope=espérer ; espoir
hospital=hôpital
hot=chaud
hour=heure
house=maison
how=comment
how old=quel âge
however=cependant
hundred=cent
hungry=affamé (be hungry = avoir faim)
i=je
i'm=je suis (I am)
ice cream=glace (dessert)
ice=glace
if=si
important=important
in=dans, en, à
independence=indépendance
information=information(s)
instead=à la place
intelligence=intelligence
intelligent=intelligent
intelligenter=✗ forme fausse : on dit more intelligent
intelligentest=✗ forme fausse : on dit the most intelligent
interesting=intéressant
introduce=présenter
introduce yourself=présente-toi
irregular=irrégulier
is=est (verbe be)
isn't=n'est pas (is not)
it=il, elle, cela, le, la
it's=c'est, il est (it is)
ivorian=ivoirien
january=janvier
join=rejoindre, s'inscrire à
jug=carafe, cruche
july=juillet
june=juin
just=juste ; venir de (I have just eaten = je viens de manger)
keep=garder
kick=frapper du pied
kill=tuer
kilo=kilo
kind=gentil ; sorte
knock=frapper (à la porte)
knockout stage=phase à élimination directe
known=connu (participe passé de know)
labour=travail (pénible) : child labour = travail des enfants
lamp=lampe
landslide=glissement de terrain
language=langue
last=dernier ; last year = l'année dernière
late=tard, en retard
launch=lancer
lay=pondre (des œufs) ; poser
learn=apprendre
least=le moins
leave=quitter, partir, laisser
left=gauche (on the left = à gauche) ; quitta
less=moins
lesson=leçon, cours
let's=allons, faisons (let us)
letter=lettre
library=bibliothèque
life=vie
light=lumière
like=aimer ; comme
lines=lignes
linking word=mot de liaison
listen=écouter
live=vivre, habiter
lively=animé, vivant
long=long
longer=plus long
longest=le plus long
look=regarder ; sembler (they look happy = ils ont l'air heureux)
lose=perdre
lost=perdit, perdu (passé de lose)
lot=beaucoup (a lot of = beaucoup de)
love=aimer, adorer ; amour
machete=machette
made=fit, fait (passé de make)
main=principal
make=faire, fabriquer
malaria=paludisme
man=homme
mango=mangue
mangoes=mangues
many=beaucoup de, nombreux
market=marché
match=match
mathematics=mathématiques
maths=maths
may=pouvoir (permission polie ou possibilité)
may i=puis-je
maybe=peut-être
me=me, moi
meal=repas
meaning=sens, signification
media=médias
medical=médical
medicine=médecine ; médicament
meet=rencontrer, se retrouver
men=hommes
middle=milieu (in the middle = au milieu)
might=pourrait (possibilité)
million=million
mindedness=état d'esprit (civic-mindedness = civisme)
mobile phone=téléphone portable
mobile=portable, mobile
modal=modal (verbe comme can, must, should)
moment=moment
monday=lundi
money=argent
month=mois
more=plus
morning=matin
mosquito net=moustiquaire
mosquito=moustique
most=le plus ; la plupart
mother=mère
motto=devise
mount=mont
mountain=montagne
move=bouger, déménager
much=beaucoup
music=musique
must=devoir (obligation)
mustn't=ne pas devoir, interdit (must not)
my=mon, ma, mes
name=nom, prénom
national=national
nature=nature
need=avoir besoin de
neighbourhood=quartier
net=filet
never=jamais
new=nouveau
news=nouvelles, informations
next=prochain ; à côté (next to = à côté de)
night=nuit
nil=zéro (score)
nine=neuf
no=non ; aucun
noise=bruit
north=nord
not=ne… pas
now=maintenant
nurse=infirmier, infirmière
o'clock=heure(s) (eight o'clock = huit heures)
obligation=obligation
of=de
off=éteint ; loin
old=vieux, âgé
on=sur ; le (on Sundays = le dimanche)
one=un
only=seulement
opinion=avis, opinion
or=ou
orange=orange
organise=organiser
other=autre
our=notre, nos
ourselves=nous-mêmes
out=dehors
over=au-dessus ; terminé
oxygen=oxygène
paid=payé (passé de pay)
parasite=parasite
parents=parents
part=partie
participle=participe
pass=réussir (un examen) ; passer
passive=passif (la voix passive)
password=mot de passe
past=passé
peace=paix
peer pressure=pression des camarades
peer=camarade du même âge
pen=stylo
pen friend=correspondant
people=gens, personnes
per=par
percent=pour cent
perfect=parfait
period=période
person=personne
phone=téléphone
pick up=ramasser
picture=image, photo
piece=morceau
pizza=pizza
plant=plante ; planter
plantain=banane plantain
plantation=plantation
plastic=plastique
plate=assiette
play=jouer
player=joueur
please=s'il te plaît, s'il vous plaît
pod=cabosse, gousse
point=montrer du doigt ; point
polite=poli
pollute=polluer
pollution=pollution
poster=affiche
pregnancy=grossesse
pregnant=enceinte
prepare=préparer
present=présent
president=président
pressure=pression
prevent=prévenir, empêcher
price=prix
problem=problème
produce=produire
producer=producteur
professional=professionnel
programme=programme
progress=progrès
prohibition=interdiction
pronoun=pronom
protect=protéger
proud=fier
punish=punir
pupil=élève
put=mettre, poser
qualify=se qualifier
question=question
quick=rapide
quickly=rapidement
rain=pluie ; pleuvoir
rainy season=saison des pluies
rainy=pluvieux
raise=lever
reach=atteindre
read=lire ; lu
ready=prêt
recycle=recycler
red=rouge
reduce=réduire
referee=arbitre
reforest=reboiser
refuse=refuser
regular=régulier
relative=relatif
religion=religion
remove=enlever, supprimer
repeat=répéter
reported speech=discours rapporté
reported=rapporté
represent=représenter
request=demande
respect=respecter ; respect
responsibly=de façon responsable
rest=se reposer ; repos
review=réviser
rice=riz
right=droite (on the right = à droite) ; juste
river=fleuve, rivière
road=route
rubbish=déchets, ordures
rule=règle
run=courir
sachet=sachet
sad=triste
said=dit, a dit (passé de say)
saturday=samedi
sauce=sauce
saw=vit, a vu (passé de see)
say=dire
scam=arnaque
school=école
sea=mer
season=saison
second=deuxième ; seconde
secretary=secrétaire
see=voir
seen=vu (participe passé de see)
sell=vendre
seller=vendeur, vendeuse
serious=grave, sérieux
serve=servir
service=service
seven=sept
several=plusieurs
shake=secouer ; shake hands = serrer la main
shall=futur ou proposition (shall we…? = et si on… ?)
share=partager
she=elle
shirt=chemise
shoot=tirer (au but)
short=court
should=devrait (conseil)
shoulder=épaule
show=montrer
sick=malade
simple=simple
since=depuis (+ point de départ : since 2020)
singer=chanteur, chanteuse
sing=chanter
sir=monsieur
sister=sœur
sit=être assis, s'asseoir
situation=situation
six=six
sixteen=seize
sixty=soixante
sixty-six=soixante-six
skin=peau
sky=ciel
sleep=dormir ; sommeil
smoke=fumer ; fumée
snow=neiger ; neige
so=donc ; si, tellement
social media=réseaux sociaux
social=social
soda=soda, boisson sucrée
soil=sol, terre
solve=résoudre
some=quelques, du, de la
someone=quelqu'un
sometimes=parfois
sorry=désolé
speak=parler
speech=discours, parole (hate speech = discours de haine)
spend=passer (du temps) ; dépenser
spent=passa, passé (passé de spend)
spoken=parlé (participe passé de speak)
sport=sport
stage=phase, étape
stagnant=stagnant (eau qui ne coule pas)
stall=étal (de marché)
stand=être debout
start=commencer
statement=affirmation, phrase
stay=rester
stop=arrêter
story=histoire, récit
stories=histoires
street=rue
student=élève, étudiant
studied=étudia, étudié (passé de study)
study=étudier ; étude
study group=groupe d'étude
subject=matière (à l'école) ; sujet
summary=résumé
sun=soleil
sunday=dimanche
sunny=ensoleillé
superlative=superlatif
supporter=supporter
sweep=balayer
swim=nager
symptom=symptôme
table=table
tag=étiquette ; question tag = petite question en fin de phrase
take=prendre
take part=participer
talk=parler, discuter
tall=grand (de taille)
taller=plus grand
tallest=le plus grand
teach=enseigner
teacher=professeur, enseignant
team=équipe
teenager=adolescent
tell=dire, raconter
ten=dix
test=contrôle, test
text=texte
than=que (dans une comparaison)
thank you=merci
thank=remercier
that=que ; ce, cette ; cela
the=le, la, les
their=leur, leurs
them=les, leur
then=ensuite, puis ; alors
there are=il y a (pluriel)
there is=il y a (singulier)
there=là ; there is / there are = il y a
these=ces, ceux-ci
they=ils, elles
thing=chose
think=penser, croire
third=troisième ; troisièmement
thirty=trente
this=ce, cette ; ceci
thousand=mille
three=trois
throw=jeter
time=temps ; fois ; heure
timetable=emploi du temps
tired=fatigué
tiredness=fatigue
to=à, vers ; pour (devant un verbe)
tobacco=tabac
today=aujourd'hui
together=ensemble
told=dit, raconta (passé de tell)
tomato=tomate
tomatoes=tomates
tomorrow=demain
too=aussi ; trop
top=haut, sommet (at the top = en haut)
towards=vers
town=ville
trader=commerçant
transmit=transmettre
tree=arbre
true=vrai
trunk=tronc
trust=faire confiance à
try=essayer
turn=tour (wait for their turn = attendre son tour)
tv=télévision
two=deux
type=taper (au clavier) ; type
typical=typique
umbrella=parasol, parapluie
under=sous
understand=comprendre
unfortunately=malheureusement
uniform=uniforme
union=union
up=en haut ; get up = se lever
us=nous
use=utiliser
useful=utile
usually=d'habitude
vaccinate=vacciner
vaccine=vaccin
vegetable=légume
verb=verbe
very=très
violence=violence
visit=visiter, rendre visite
voice=voix
volunteer=bénévole, volontaire
wait=attendre
walk=marcher, aller à pied
wall=mur
want=vouloir
was=était, a été (passé de be : I / he / she / it)
waste=déchets ; gaspiller
watch=regarder ; montre
watchs=✗ forme fausse : on écrit watches
water=eau
water bottle=gourde
way=manière, façon ; chemin
we=nous
wear=porter (un vêtement)
weather=temps (météo)
week=semaine
weekend=week-end
well=bien
went=alla, est allé (passé de go)
were=étaient, étions (passé de be)
weren't=n'étaient pas (were not)
what=que, quoi, quel
whatever=quel que soit, n'importe quel
when=quand
where=où
which=qui, que (pour une chose) ; quel
white=blanc
who=qui
whole=entier
whose=dont, à qui
why=pourquoi
will=futur (I will go = j'irai)
win=gagner
window=fenêtre
windy=venteux
wish=souhait ; best wishes = amitiés
with=avec
without=sans
woman=femme
women=femmes
won=gagna, gagné (passé de win)
won't=ne… pas (futur : will not)
word=mot
work=travailler ; travail
world=monde
world cup=Coupe du monde
worried=inquiet
worse=pire, plus mauvais
worst=le pire
would=conditionnel (I would say = je dirais)
wouldn't=ne… pas (conditionnel : would not)
write=écrire
writed=✗ forme fausse : le passé de write est wrote
writer=auteur
written=écrit (participe passé de write)
wrote=écrivit, a écrit (passé de write)
yard=cour
year=année, an
yellow=jaune
yesterday=hier
yet=encore, déjà (dans une question ou une négation)
you=tu, vous
young=jeune
your=ton, ta, tes, votre, vos
yourself=toi-même
according=selon (according to)
artificial=artificiel
be=être
broom=balai
candidate=candidat
justify=justifier
knockout=élimination directe
linking=de liaison (linking word = mot de liaison)
pick=cueillir ; pick up = ramasser
village=village
brazil=Brésil
canada=Canada
norway=Norvège
senegal=Sénégal
london=Londres
paris=Paris
accra=Accra (capitale du Ghana)
abidjan=Abidjan
nile=le Nil (fleuve)`;
