  Object.assign(MOTS, {
    // ---------------- SVT ----------------
    "svt-aliments": [["Aliment", "Produit que l'on mange ou que l'on boit pour vivre et grandir.", "L'attiéké, le poisson, la mangue, l'eau."],
      ["Nutriment", "Substance simple issue de la digestion, qui peut passer dans le sang.", "Le glucose issu de l'amidon du riz."],
      ["Ration alimentaire", "Quantité et variété d'aliments nécessaires à une personne pour une journée.", "Un adolescent a besoin de plus d'énergie qu'un enfant de 5 ans."],
      ["Carence", "Manque d'un nutriment dans l'alimentation, qui provoque une maladie.", "Le manque de vitamine C provoque le scorbut."],
      ["Aliment bâtisseur", "Aliment riche en protides, qui construit et répare le corps.", "Le poisson, les œufs, les haricots."]],
    "svt-digestion": [["Digestion", "Transformation des aliments en nutriments dans le tube digestif.", "L'amidon du foutou transformé en glucose."],
      ["Enzyme", "Substance qui découpe les grosses molécules des aliments.", "L'amylase de la salive transforme l'amidon en sucre."],
      ["Suc digestif", "Liquide produit par une glande, qui contient des enzymes.", "La salive, le suc gastrique, le suc pancréatique."],
      ["Absorption intestinale", "Passage des nutriments de l'intestin grêle vers le sang.", "Le glucose passe dans le sang à travers les villosités."],
      ["Villosité intestinale", "Petit repli de la paroi de l'intestin grêle qui augmente la surface d'absorption.", "Des millions de villosités tapissent l'intestin."]],
    "svt-sang": [["Plasma", "Partie liquide et jaunâtre du sang.", "Il représente environ 55 % du sang."],
      ["Hématie", "Globule rouge : cellule du sang qui transporte le dioxygène grâce à l'hémoglobine.", "Environ 5 millions par mm³ de sang."],
      ["Leucocyte", "Globule blanc : cellule du sang qui défend l'organisme contre les microbes.", "Ils attaquent les microbes d'une plaie infectée."],
      ["Plaquette", "Élément du sang qui permet la coagulation.", "Elles arrêtent le saignement d'une petite coupure."],
      ["Anémie", "Manque de globules rouges ou d'hémoglobine.", "Un enfant qui a eu souvent le paludisme peut être anémié."]],
    "svt-transfusion": [["Transfusion sanguine", "Injection de sang d'un donneur à un receveur compatible.", "Après un accident, un blessé reçoit du sang."],
      ["Antigène", "Molécule à la surface des hématies qui détermine le groupe sanguin.", "Les hématies du groupe A portent l'antigène A."],
      ["Anticorps", "Molécule du plasma qui attaque un antigène étranger.", "Le plasma d'une personne du groupe A contient des anti-B."],
      ["Agglutination", "Collage des hématies entre elles quand elles rencontrent l'anticorps correspondant.", "Du sang B donné à une personne du groupe A."],
      ["Donneur universel", "Groupe qui peut donner à tous : O (et O Rh− en tenant compte du Rhésus).", "Une personne O− peut donner à tout le monde."]],
    "svt-circulation": [["Artère", "Vaisseau qui transporte le sang du cœur vers les organes.", "L'aorte."],
      ["Veine", "Vaisseau qui ramène le sang des organes vers le cœur.", "Les veines caves."],
      ["Capillaire", "Très petit vaisseau où se font les échanges entre le sang et les cellules.", "Les capillaires des muscles."],
      ["Grande circulation", "Trajet du sang du cœur gauche vers les organes et retour au cœur droit.", "Ventricule gauche → aorte → organes → veines caves."],
      ["Petite circulation", "Trajet du sang du cœur droit vers les poumons et retour au cœur gauche.", "Le sang s'y charge en dioxygène."]],
    "svt-grossesse": [["Grossesse précoce", "Grossesse qui survient chez une adolescente, avant l'âge adulte.", "Une élève de 15 ans enceinte."],
      ["Ovulation", "Libération d'un ovule par l'ovaire, vers le 14e jour d'un cycle de 28 jours.", "C'est la période où la fécondation est possible."],
      ["Fécondation", "Union d'un spermatozoïde et d'un ovule.", "Elle donne une cellule-œuf."],
      ["Contraception", "Ensemble des moyens pour éviter une grossesse.", "Le préservatif, qui protège aussi des IST."]],
    "svt-vih": [["VIH", "Virus de l'immunodéficience humaine, qui détruit les lymphocytes T4.", "Il se transmet par le sang, les rapports sexuels et de la mère à l'enfant."],
      ["Sida", "Stade avancé de l'infection au VIH : l'organisme ne se défend plus.", "Apparition de maladies opportunistes."],
      ["Maladie opportuniste", "Maladie qui profite de l'affaiblissement des défenses de l'organisme.", "La tuberculose chez une personne au stade sida."],
      ["Séropositif", "Personne dont le test révèle la présence d'anticorps contre le VIH.", "Sous ARV, une personne séropositive vit normalement."],
      ["ARV", "Antirétroviraux : médicaments qui bloquent la multiplication du VIH.", "Gratuits en Côte d'Ivoire."]],
    "svt-sol": [["Sol", "Couche superficielle de la Terre, formée de minéraux, de matière organique, d'eau et d'air.", "La terre du jardin de l'école."],
      ["Humus", "Matière organique issue de la décomposition des débris végétaux et animaux.", "La couche sombre sous les feuilles mortes en forêt."],
      ["Horizon", "Couche du sol qui a une couleur et une composition particulières.", "L'horizon humifère, en haut du profil."],
      ["Perméabilité", "Capacité d'un sol à laisser passer l'eau.", "Un sol sableux est très perméable."],
      ["Roche-mère", "Roche située en bas du profil, à partir de laquelle le sol se forme.", "Le granite sous un sol de savane."]],
    "svt-sol-plantes": [["Poil absorbant", "Prolongement fin de la racine qui absorbe l'eau et les sels minéraux.", "Visible près de l'extrémité d'une racine de haricot."],
      ["Sève brute", "Eau et sels minéraux qui montent des racines vers les feuilles.", "Elle circule dans les vaisseaux du bois."],
      ["Sels minéraux", "Éléments nutritifs du sol dont la plante a besoin (azote, phosphore, potassium).", "Le NPK des engrais."],
      ["Photosynthèse", "Fabrication de matière organique par la plante grâce à la lumière, avec rejet de dioxygène.", "Les feuilles vertes du manguier au soleil."]],
    "svt-degradation": [["Érosion", "Arrachement et transport du sol par l'eau ou le vent.", "La terre emportée par la pluie sur une pente nue."],
      ["Lessivage", "Entraînement des sels minéraux en profondeur par l'eau.", "Un sol sableux perd vite ses éléments nutritifs."],
      ["Désertification", "Transformation progressive d'une région en désert.", "Elle menace le nord de l'Afrique de l'Ouest."],
      ["Déforestation", "Destruction des forêts.", "Les forêts coupées pour installer des plantations."]],
    "svt-protection": [["Jachère", "Terre laissée au repos pendant un certain temps pour qu'elle retrouve sa fertilité.", "Un champ non cultivé pendant 3 ans."],
      ["Compost", "Engrais naturel obtenu par la décomposition de déchets végétaux.", "Les épluchures et feuilles mises en tas."],
      ["Rotation des cultures", "Changement de culture d'une saison à l'autre sur le même champ.", "Maïs une année, arachide l'année suivante."],
      ["Agroforesterie", "Association d'arbres et de cultures sur une même parcelle.", "Du cacao planté à l'ombre de grands arbres."],
      ["Reboisement", "Plantation d'arbres sur une terre déboisée.", "Le programme de 2026 vise 1,5 million d'hectares."]],
    // ---------------- Histoire-Géographie ----------------
    "hg-colonisation": [["Impérialisme", "Volonté d'une puissance d'étendre sa domination sur d'autres territoires.", "Les puissances européennes se partagent l'Afrique à la fin du XIXe siècle."],
      ["Colonisation", "Occupation et exploitation d'un territoire par une puissance étrangère.", "La Côte d'Ivoire devient colonie française en 1893."],
      ["Colonie", "Territoire dominé et administré par une puissance étrangère.", "La colonie de Côte d'Ivoire, créée le 10 mars 1893."],
      ["Résistance", "Lutte d'un peuple contre la conquête ou la domination étrangère.", "Samory Touré a combattu les Français jusqu'en 1898."],
      ["Travail forcé", "Travail obligatoire et non payé imposé aux colonisés.", "Construction de routes et de voies ferrées."]],
    "hg-independance": [["Indépendance", "Situation d'un pays qui se gouverne lui-même, sans domination étrangère.", "La Côte d'Ivoire est indépendante depuis le 7 août 1960."],
      ["Décolonisation", "Processus par lequel les colonies deviennent indépendantes.", "La plupart des pays d'Afrique de l'Ouest en 1960."],
      ["Parti politique", "Association de personnes qui veulent conquérir le pouvoir par les élections.", "Le PDCI, créé en 1946."],
      ["Autonomie interne", "Droit pour une colonie de gérer ses propres affaires intérieures.", "Accordée par la loi-cadre de 1956."],
      ["Référendum", "Vote par lequel les citoyens répondent oui ou non à une question.", "Le référendum du 28 septembre 1958."]],
    "hg-crises": [["Crise sociopolitique", "Période de troubles graves qui touche la société et le pouvoir.", "La crise post-électorale ivoirienne de 2010-2011."],
      ["Coup d'État", "Prise du pouvoir par la force, contre les règles.", "Plusieurs coups d'État au Sahel depuis 2020."],
      ["Génocide", "Extermination volontaire d'un groupe humain à cause de son origine.", "Le génocide des Tutsi au Rwanda en 1994."],
      ["Réfugié", "Personne qui fuit son pays à cause de la guerre ou des persécutions.", "Des milliers de réfugiés lors des crises."],
      ["Réconciliation", "Retour à la paix et à l'entente entre des groupes qui s'opposaient.", "Les commissions de dialogue après une crise."]],
    "hg-ww2": [["Guerre mondiale", "Guerre qui oppose de nombreux pays sur plusieurs continents.", "La Seconde Guerre mondiale (1939-1945)."],
      ["Totalitarisme", "Régime qui contrôle toute la vie des citoyens et supprime les libertés.", "Le nazisme d'Hitler en Allemagne."],
      ["Shoah", "Génocide des Juifs d'Europe par les nazis.", "Environ 6 millions de victimes."],
      ["Guerre totale", "Guerre qui mobilise toutes les ressources d'un pays et touche aussi les civils.", "Bombardements des villes, usines tournées vers l'armement."],
      ["Capitulation", "Reddition d'une armée ou d'un pays vaincu.", "L'Allemagne capitule le 8 mai 1945."]],
    "hg-onu": [["ONU", "Organisation des Nations unies, créée en 1945 pour maintenir la paix dans le monde.", "193 États membres, siège à New York."],
      ["Droit de veto", "Pouvoir d'un membre permanent du Conseil de sécurité de bloquer une décision.", "La Chine, les États-Unis, la France, le Royaume-Uni et la Russie l'ont."],
      ["Casques bleus", "Soldats de l'ONU envoyés pour maintenir la paix.", "L'ONUCI en Côte d'Ivoire (2004-2017)."],
      ["Institution spécialisée", "Organisation de l'ONU chargée d'un domaine précis.", "L'OMS pour la santé, l'UNESCO pour l'éducation."]],
    "hg-ua": [["Union africaine (UA)", "Organisation qui regroupe les 55 États d'Afrique, créée en 2002.", "Siège à Addis-Abeba."],
      ["Panafricanisme", "Idée selon laquelle les peuples africains doivent s'unir.", "La création de l'OUA en 1963."],
      ["Intégration régionale", "Rapprochement de pays voisins pour coopérer (économie, circulation).", "La CEDEAO, l'UEMOA."],
      ["ZLECAf", "Zone de libre-échange continentale africaine : pour faciliter le commerce entre pays africains.", "Échanges lancés en 2021."]],
    "hg-atouts": [["Atout", "Avantage qui favorise le développement d'un pays.", "Des sols fertiles, une population jeune."],
      ["Relief", "Forme du terrain : plaines, plateaux, montagnes.", "Les montagnes de l'ouest, avec le mont Nimba."],
      ["Climat équatorial", "Climat chaud et humide toute l'année, avec quatre saisons.", "Le sud de la Côte d'Ivoire."],
      ["Ressources naturelles", "Richesses fournies par la nature.", "L'or, le pétrole, les forêts, l'eau."],
      ["Population active", "Personnes en âge de travailler et qui travaillent ou cherchent un emploi.", "Les jeunes qui entrent sur le marché du travail."]],
    "hg-secteurs": [["Secteur primaire", "Activités qui exploitent directement la nature.", "L'agriculture, la pêche, l'élevage, les mines."],
      ["Secteur secondaire", "Activités qui transforment les matières premières.", "Une chocolaterie, une usine de ciment."],
      ["Secteur tertiaire", "Activités de services.", "Le commerce, les banques, les transports, l'école."],
      ["Culture d'exportation", "Culture destinée à être vendue à l'étranger.", "Le cacao, l'anacarde, l'hévéa."],
      ["Culture vivrière", "Culture destinée à nourrir la population du pays.", "Le manioc, l'igname, le riz."]],
    "hg-problemes": [["Développement", "Amélioration des conditions de vie de la population (santé, éducation, revenus).", "Construire des écoles et des hôpitaux."],
      ["Exode rural", "Départ des habitants des campagnes vers les villes.", "Des jeunes qui quittent le village pour Abidjan."],
      ["Endettement", "Situation d'un pays qui a emprunté beaucoup d'argent et doit le rembourser.", "Le remboursement de la dette réduit les dépenses d'éducation."],
      ["Diversification", "Développement de nouvelles activités pour ne pas dépendre d'un seul produit.", "Produire de l'anacarde, de l'hévéa, et transformer le cacao."]],
    "hg-afrique": [["Mondialisation", "Intensification des échanges de marchandises, de capitaux et d'informations dans le monde.", "Un téléphone assemblé en Asie et vendu à Bouaké."],
      ["Matière première", "Produit brut tiré de la nature, avant transformation.", "Le cacao, le pétrole, le cobalt."],
      ["Produit manufacturé", "Produit fabriqué en usine.", "Une voiture, un ordinateur."],
      ["Commerce extérieur", "Échanges d'un pays avec l'étranger : importations et exportations.", "La Côte d'Ivoire exporte du cacao et importe des machines."]],
    // ---------------- EDHC ----------------
    "edhc-parents": [["Droits de l'enfant", "Droits reconnus à tout enfant par la Convention de l'ONU de 1989.", "Le droit à l'éducation, à la santé, aux loisirs."],
      ["Épanouissement", "Développement harmonieux du corps, de l'esprit et de la personnalité.", "Un enfant qui étudie, joue et est écouté."],
      ["Scolarisation obligatoire", "Obligation d'aller à l'école de 6 à 16 ans en Côte d'Ivoire.", "Instaurée en 2015."],
      ["Acte de naissance", "Document officiel qui prouve l'identité d'une personne.", "Indispensable pour s'inscrire au BEPC."]],
    "edhc-violences": [["Violence", "Acte qui porte atteinte à l'intégrité physique ou morale d'une personne.", "Coups, insultes répétées, harcèlement."],
      ["Mutilations génitales féminines", "Ablation d'une partie des organes génitaux féminins, interdite en Côte d'Ivoire depuis 1998.", "Une pratique punie par la loi."],
      ["Mariage précoce", "Mariage d'un enfant avant l'âge légal.", "Une fille de 14 ans mariée de force."],
      ["DUDH", "Déclaration universelle des droits de l'homme, adoptée par l'ONU le 10 décembre 1948.", "Article 1 : les hommes naissent libres et égaux en droits."]],
    "edhc-humanitaire": [["Organisation humanitaire", "Organisation qui aide les victimes de guerres ou de catastrophes.", "La Croix-Rouge, Médecins sans frontières."],
      ["Droit international humanitaire (DIH)", "Règles qui protègent les personnes pendant les conflits armés.", "Les Conventions de Genève de 1949."],
      ["Neutralité", "Fait de ne prendre parti pour aucun camp.", "La Croix-Rouge soigne les blessés des deux camps."],
      ["Réfugié", "Personne qui a fui son pays pour échapper à un danger.", "Le HCR aide les réfugiés."]],
    "edhc-partis": [["Démocratie", "Régime où le pouvoir appartient au peuple, qui choisit ses dirigeants par le vote.", "L'élection présidentielle tous les 5 ans."],
      ["Multipartisme", "Existence de plusieurs partis politiques.", "En Côte d'Ivoire depuis 1990."],
      ["Institution", "Organe officiel qui fait fonctionner l'État.", "L'Assemblée nationale, le Conseil constitutionnel."],
      ["Constitution", "Loi fondamentale qui organise l'État et les pouvoirs.", "La Constitution ivoirienne du 8 novembre 2016."],
      ["Tolérance", "Respect des opinions et des différences des autres.", "Écouter un camarade d'un autre parti sans l'insulter."]],
    "edhc-vote": [["Vote", "Acte par lequel un citoyen exprime son choix lors d'une élection.", "Mettre son bulletin dans l'urne."],
      ["Suffrage universel", "Droit de vote accordé à tous les citoyens majeurs.", "Tout Ivoirien de 18 ans et plus inscrit sur la liste."],
      ["Liste électorale", "Registre des personnes autorisées à voter.", "Il faut s'y inscrire pour voter."],
      ["Abstention", "Fait de ne pas aller voter.", "Un fort taux d'abstention affaiblit la démocratie."]],
    "edhc-impot": [["Impôt", "Contribution obligatoire versée à l'État pour financer les services publics.", "L'impôt sur les salaires."],
      ["Impôt direct", "Impôt payé directement par la personne à l'administration.", "L'impôt foncier sur une maison."],
      ["Impôt indirect", "Impôt inclus dans le prix d'un produit ou d'un service.", "La TVA de 18 % dans le prix d'un savon."],
      ["Contribuable", "Personne qui paie des impôts.", "Un commerçant qui paie sa patente."],
      ["Fraude fiscale", "Fait d'échapper illégalement à l'impôt.", "Cacher ses revenus pour moins payer."]],
    "edhc-biens": [["Bien public", "Bien qui appartient à la collectivité et sert à tous.", "Les tables-bancs, les routes, les lampadaires."],
      ["Vandalisme", "Destruction volontaire de biens.", "Casser les lampes de la classe."],
      ["Collectivité", "Ensemble des personnes qui vivent dans un même lieu.", "Les habitants d'une commune."],
      ["Civisme", "Respect des règles et des biens communs par le citoyen.", "Jeter ses déchets dans la poubelle."]],
    "edhc-entreprise": [["Entreprise", "Organisation qui produit des biens ou des services pour les vendre.", "Un atelier de couture, un maquis."],
      ["Étude de marché", "Enquête pour connaître les clients, les concurrents et les prix.", "Demander aux voisins s'ils achèteraient du jus de bissap."],
      ["Plan d'affaires", "Document qui décrit le projet, ses coûts et ses recettes prévues.", "Présenté à une microfinance pour obtenir un prêt."],
      ["Insertion sociale", "Fait de trouver sa place dans la société, notamment par le travail.", "Un jeune qui ouvre son atelier de soudure."]],
    "edhc-alliances": [["Cohésion sociale", "Entente et solidarité entre les membres d'une société.", "Les communautés qui vivent en paix dans un quartier."],
      ["Alliance à plaisanterie", "Pacte ancien entre peuples qui autorise la taquinerie et impose l'entraide.", "Entre certains peuples Mandé et Gour."],
      ["Ethnie", "Groupe humain qui partage une langue, une culture et des traditions.", "Les Sénoufo, les Baoulé, les Bété."],
      ["Tolérance", "Acceptation des différences des autres.", "Respecter les coutumes d'une autre ethnie."]],
    "edhc-sante": [["Automédication", "Fait de se soigner soi-même sans avis médical.", "Prendre n'importe quel comprimé contre la fièvre."],
      ["Ordonnance", "Document rédigé par un médecin qui indique les médicaments et les doses.", "Présentée à la pharmacie."],
      ["Médicament de la rue", "Médicament vendu hors des pharmacies, souvent faux ou périmé.", "Des comprimés vendus au marché ou dans les cars."],
      ["CMU", "Couverture maladie universelle : système qui aide à payer les soins.", "La carte CMU."]],
    "edhc-depistage": [["Dépistage", "Test qui permet de savoir si l'on est porteur d'une maladie.", "Le test du VIH, gratuit et confidentiel."],
      ["Confidentialité", "Fait de garder secrète une information personnelle.", "Le résultat du test n'est donné qu'à la personne."],
      ["Stigmatisation", "Fait de rejeter ou de montrer du doigt une personne.", "Refuser de manger avec une personne vivant avec le VIH."],
      ["PTME", "Prévention de la transmission du VIH de la mère à l'enfant.", "Grâce aux ARV, le bébé naît sans le virus."]],
    "edhc-parcs": [["Parc national", "Espace naturel protégé par l'État pour préserver la faune et la flore.", "Le parc national de Taï."],
      ["Biodiversité", "Diversité des espèces vivantes dans un milieu.", "Chimpanzés, éléphants, hippopotames pygmées de Taï."],
      ["Braconnage", "Chasse ou pêche illégale.", "Tuer des éléphants pour leur ivoire."],
      ["Patrimoine mondial", "Site reconnu par l'UNESCO pour sa valeur exceptionnelle.", "Taï, la Comoé et le mont Nimba."]],
    "edhc-eau": [["Eau potable", "Eau qu'on peut boire sans danger pour la santé.", "L'eau distribuée par la SODECI."],
      ["Gaspillage", "Utilisation excessive ou inutile d'une ressource.", "Laisser couler le robinet."],
      ["Ressource naturelle", "Richesse fournie par la nature, parfois limitée.", "L'eau, le bois, le sol."],
      ["Paix sociale", "Situation où les membres d'une communauté vivent sans conflit.", "Respecter les tours à la borne-fontaine."]]
  });
