  // =========================================================
  // Les mots à connaître : [mot, définition simple, exemple]
  // =========================================================
  const MOTS = {
    // ---------------- Maths ----------------
    bases: [["Fraction", "Nombre écrit sous la forme a/b, qui représente a parts d'une unité partagée en b parts égales.", "3/4 d'un gâteau : on le coupe en 4 et on prend 3 parts."],
      ["Dénominateur", "Nombre du bas d'une fraction : il indique en combien de parts on partage.", "Dans 5/8, le dénominateur est 8."],
      ["Nombre relatif", "Nombre positif ou négatif, avec son signe.", "−5 °C la nuit à Paris, +32 °C à Abidjan."],
      ["Opposé", "L'opposé d'un nombre a le même chiffre mais le signe contraire ; leur somme vaut 0.", "L'opposé de 7 est −7, car 7 + (−7) = 0."]],
    litteral: [["Expression littérale", "Calcul qui contient des lettres représentant des nombres.", "3x + 5, où x peut valoir n'importe quel nombre."],
      ["Développer", "Transformer un produit en somme.", "2(x + 3) = 2x + 6."],
      ["Factoriser", "Transformer une somme en produit (le contraire de développer).", "2x + 6 = 2(x + 3)."],
      ["Identité remarquable", "Égalité toujours vraie qui permet de développer ou factoriser rapidement.", "(a + b)² = a² + 2ab + b²."],
      ["Équation produit nul", "Équation de la forme A × B = 0 : on résout A = 0 ou B = 0.", "(x − 2)(x + 5) = 0 donne x = 2 ou x = −5."]],
    thales: [["Configuration de Thalès", "Figure avec deux droites sécantes coupées par deux droites parallèles.", "Le triangle ABC avec M sur [AB], N sur [AC] et (MN) // (BC)."],
      ["Droites parallèles", "Droites qui ne se coupent jamais, même prolongées.", "Les deux bords d'une route droite."],
      ["Quotient", "Résultat d'une division, souvent écrit sous forme de fraction.", "AM/AB = 4/10 = 0,4."],
      ["Réciproque", "Propriété « à l'envers » : on part de la conclusion pour retrouver l'hypothèse.", "Si AM/AB = AN/AC, alors (MN) // (BC)."]],
    racines: [["Racine carrée", "La racine carrée d'un nombre positif a est le nombre positif dont le carré vaut a.", "√49 = 7 car 7² = 49."],
      ["Carré parfait", "Nombre qui est le carré d'un entier.", "1, 4, 9, 16, 25, 36, 49, 64, 81, 100."],
      ["Valeur absolue", "Distance d'un nombre à zéro : elle est toujours positive.", "|−5| = 5 et |5| = 5."],
      ["Expression conjuguée", "Le conjugué de a + √b est a − √b ; leur produit n'a plus de racine.", "(3 + √2)(3 − √2) = 9 − 2 = 7."]],
    triangle: [["Hypoténuse", "Dans un triangle rectangle, côté opposé à l'angle droit : c'est le plus long.", "Dans ABC rectangle en A, l'hypoténuse est [BC]."],
      ["Côté adjacent", "Côté de l'angle droit qui touche l'angle étudié.", "Pour l'angle B, le côté adjacent est [AB]."],
      ["Côté opposé", "Côté situé en face de l'angle étudié.", "Pour l'angle B, le côté opposé est [AC]."],
      ["Cosinus", "Dans un triangle rectangle, rapport côté adjacent / hypoténuse.", "cos B = AB/BC = 3/5 = 0,6."]],
    calcul: [["Intervalle", "Ensemble de tous les nombres compris entre deux bornes.", "[2 ; 5] contient 2 ; 3,4 ; 4,99 et 5."],
      ["Amplitude", "Longueur d'un intervalle : borne haute moins borne basse.", "L'amplitude de [2 ; 7] est 7 − 2 = 5."],
      ["Encadrement", "Écriture qui place un nombre entre deux valeurs.", "1,41 < √2 < 1,42."],
      ["Arrondi", "Valeur approchée la plus proche à une précision donnée.", "L'arrondi au dixième de 3,46 est 3,5."]],
    angles: [["Angle inscrit", "Angle dont le sommet est sur le cercle et dont les côtés coupent le cercle.", "AĈB avec A, B, C sur le cercle."],
      ["Angle au centre", "Angle dont le sommet est le centre du cercle.", "AÔB, où O est le centre."],
      ["Arc intercepté", "Portion du cercle comprise entre les côtés d'un angle.", "L'arc AB intercepté par l'angle AĈB."],
      ["Diamètre", "Segment qui passe par le centre et relie deux points du cercle.", "Si le rayon vaut 3 cm, le diamètre vaut 6 cm."]],
    vecteurs: [["Vecteur", "Objet défini par une direction, un sens et une longueur, représenté par une flèche.", "AB⃗ va de A vers B."],
      ["Vecteurs égaux", "Vecteurs de même direction, même sens et même longueur.", "Dans un parallélogramme ABCD, AB⃗ = DC⃗."],
      ["Vecteurs colinéaires", "Vecteurs de même direction : l'un est un multiple de l'autre.", "AB⃗ = 3 CD⃗."],
      ["Vecteur nul", "Vecteur de longueur zéro, noté 0⃗.", "AA⃗ = 0⃗."]],
    equations: [["Équation", "Égalité qui contient une inconnue ; la résoudre, c'est trouver sa valeur.", "2x + 3 = 11 donne x = 4."],
      ["Inéquation", "Inégalité qui contient une inconnue ; ses solutions forment un intervalle.", "x + 2 > 5 donne x > 3, soit ]3 ; +∞[."],
      ["Solution", "Valeur de l'inconnue qui rend l'égalité (ou l'inégalité) vraie.", "4 est solution de 2x + 3 = 11."],
      ["Système d'inéquations", "Plusieurs inéquations à vérifier en même temps.", "x ≥ 1 et x < 4 donne [1 ; 4[."]],
    coordonnees: [["Repère orthonormé", "Repère dont les axes sont perpendiculaires et ont la même unité.", "Le quadrillage d'une feuille avec deux axes."],
      ["Abscisse", "Première coordonnée d'un point (sur l'axe horizontal).", "Dans A(3 ; −2), l'abscisse est 3."],
      ["Ordonnée", "Deuxième coordonnée d'un point (sur l'axe vertical).", "Dans A(3 ; −2), l'ordonnée est −2."],
      ["Milieu", "Point situé à égale distance des deux extrémités d'un segment.", "Le milieu de A(0 ; 0) et B(4 ; 2) est I(2 ; 1)."]],
    droites: [["Équation de droite", "Égalité y = ax + b vérifiée par tous les points de la droite.", "y = 2x + 1."],
      ["Coefficient directeur", "Nombre a qui indique la pente de la droite.", "Pour y = 2x + 1, quand x augmente de 1, y augmente de 2."],
      ["Ordonnée à l'origine", "Nombre b : là où la droite coupe l'axe vertical.", "y = 2x + 1 coupe l'axe des y en 1."],
      ["Droites perpendiculaires", "Droites qui se coupent en formant un angle droit.", "y = 2x et y = −0,5x (car 2 × (−0,5) = −1)."]],
    stats: [["Effectif", "Nombre de fois qu'une valeur apparaît.", "8 élèves ont eu 12 : l'effectif de 12 est 8."],
      ["Fréquence", "Effectif divisé par l'effectif total (souvent en %).", "8 élèves sur 40 : fréquence = 20 %."],
      ["Moyenne", "Somme de toutes les valeurs divisée par leur nombre.", "Notes 10, 12, 14 : moyenne = 36 ÷ 3 = 12."],
      ["Médiane", "Valeur qui partage la série rangée en deux groupes de même effectif.", "Pour 3 ; 7 ; 9 ; 12 ; 15, la médiane est 9."],
      ["Mode", "Valeur qui a le plus grand effectif.", "Si l'attiéké est choisi par 12 élèves sur 30, c'est le mode."]],
    systemes: [["Système d'équations", "Deux équations à deux inconnues à vérifier en même temps.", "x + y = 12 et 2x − y = 3."],
      ["Couple solution", "Paire de nombres (x ; y) qui vérifie les deux équations.", "(5 ; 7) est solution de x + y = 12 et 2x − y = 3."],
      ["Substitution", "Méthode : on exprime une inconnue et on la remplace dans l'autre équation.", "x = 12 − y, puis on remplace x dans 2x − y = 3."],
      ["Combinaison", "Méthode : on additionne ou soustrait les équations pour éliminer une inconnue.", "(x + y) + (2x − y) = 12 + 3 donne 3x = 15."]],
    affines: [["Application affine", "Fonction de la forme f(x) = ax + b.", "f(x) = 3x + 2."],
      ["Application linéaire", "Application affine avec b = 0 : f(x) = ax. Elle traduit la proportionnalité.", "Prix de x kg de riz à 400 F : f(x) = 400x."],
      ["Image", "Résultat f(x) obtenu en remplaçant x par un nombre.", "Si f(x) = 3x + 2, l'image de 4 est 14."],
      ["Antécédent", "Nombre de départ qui a une image donnée.", "Si f(x) = 3x + 2, l'antécédent de 14 est 4."]],
    pyramides: [["Pyramide", "Solide avec une base polygonale et des faces triangulaires qui se rejoignent en un sommet.", "Les pyramides d'Égypte ont une base carrée."],
      ["Cône de révolution", "Solide obtenu en faisant tourner un triangle rectangle autour d'un côté de l'angle droit.", "Un cornet de glace."],
      ["Génératrice", "Segment qui relie le sommet du cône à un point du cercle de base.", "Si r = 3 et h = 4, la génératrice mesure 5."],
      ["Réduction", "Figure dont toutes les longueurs sont multipliées par k < 1.", "Couper une pyramide à mi-hauteur donne une réduction de coefficient 1/2."]],
    // ---------------- Physique-Chimie ----------------
    "pc-masse": [["Masse", "Quantité de matière d'un corps, en kilogrammes (kg). Elle ne change pas avec le lieu.", "Un sac de riz de 25 kg a la même masse à Abidjan et sur la Lune."],
      ["Poids", "Force d'attraction exercée par la Terre sur un corps, en newtons (N).", "Le poids d'un sac de 25 kg est 250 N (avec g = 10 N/kg)."],
      ["Intensité de la pesanteur (g)", "Rapport P/m, en N/kg ; il vaut environ 10 N/kg sur Terre.", "Sur la Lune, g ≈ 1,6 N/kg."],
      ["Centre de gravité", "Point où s'applique le poids d'un corps.", "Le milieu d'une règle homogène."]],
    "pc-forces": [["Force", "Action mécanique capable de mettre en mouvement, de freiner ou de déformer un corps.", "Pousser une brouette."],
      ["Force de contact", "Force qui s'exerce quand les deux corps se touchent.", "La main qui pousse une porte."],
      ["Force à distance", "Force qui s'exerce sans contact.", "L'aimant qui attire un clou, le poids."],
      ["Dynamomètre", "Appareil qui mesure l'intensité d'une force en newtons.", "Un peson de marché."]],
    "pc-equilibre": [["Équilibre", "Un corps est en équilibre s'il reste immobile.", "Une lampe suspendue qui ne bouge pas."],
      ["Forces qui se compensent", "Forces de même droite d'action, de sens contraires et de même intensité.", "Le poids d'une lampe et la tension du fil."],
      ["Tension d'un fil", "Force exercée par un fil tendu sur l'objet qu'il retient.", "Le fil qui tient un seau au-dessus d'un puits."],
      ["Réaction du support", "Force exercée par une surface sur un objet posé dessus.", "La table qui soutient un livre."]],
    "pc-travail": [["Travail d'une force", "Énergie transférée par une force qui déplace son point d'application : W = F × L, en joules.", "Pousser une charrette avec 100 N sur 5 m : W = 500 J."],
      ["Travail moteur", "Travail d'une force qui favorise le mouvement (positif).", "La force d'un porteur qui soulève un colis."],
      ["Travail résistant", "Travail d'une force qui s'oppose au mouvement (négatif).", "Les frottements du sol sur une caisse."],
      ["Puissance", "Travail effectué par seconde : P = W / t, en watts.", "1 500 J en 10 s donnent 150 W."]],
    "pc-energie": [["Énergie cinétique", "Énergie d'un corps due à sa vitesse : Ec = ½ m v².", "Une moto qui roule vite a beaucoup d'énergie cinétique."],
      ["Énergie potentielle", "Énergie d'un corps due à sa hauteur : Ep = m g h.", "Une mangue accrochée en haut de l'arbre."],
      ["Énergie mécanique", "Somme de l'énergie cinétique et de l'énergie potentielle.", "Em = Ec + Ep."],
      ["Conservation de l'énergie", "Sans frottements, l'énergie mécanique reste constante.", "En tombant, la mangue perd de l'Ep et gagne autant d'Ec."]],
    "pc-electrolyse": [["Électrolyse", "Décomposition d'une substance par le passage du courant électrique.", "L'électrolyse de l'eau donne du dihydrogène et du dioxygène."],
      ["Cathode", "Électrode reliée à la borne négative (−).", "Le dihydrogène se dégage à la cathode."],
      ["Anode", "Électrode reliée à la borne positive (+).", "Le dioxygène se dégage à l'anode."],
      ["Synthèse", "Fabrication d'un corps à partir d'autres corps.", "La synthèse de l'eau : 2 H₂ + O₂ → 2 H₂O."]],
    "pc-alcanes": [["Hydrocarbure", "Corps formé uniquement de carbone et d'hydrogène.", "Le méthane CH₄, le butane C₄H₁₀."],
      ["Alcane", "Hydrocarbure saturé de formule CₙH₂ₙ₊₂.", "Le propane C₃H₈."],
      ["Combustion complète", "Combustion avec assez de dioxygène : elle donne CO₂ et eau (flamme bleue).", "Le gaz de cuisine bien réglé."],
      ["Combustion incomplète", "Combustion avec trop peu de dioxygène : elle donne de la suie et du CO toxique (flamme jaune).", "Les casseroles noircies par une flamme jaune."]],
    "pc-lentilles": [["Lentille convergente", "Lentille à bords minces qui concentre la lumière.", "Une loupe."],
      ["Lentille divergente", "Lentille à bords épais qui disperse la lumière.", "Les verres de lunettes d'un myope."],
      ["Foyer image (F')", "Point où convergent les rayons arrivant parallèles à l'axe.", "Le point brûlant quand on concentre le soleil avec une loupe."],
      ["Vergence", "Grandeur C = 1/f (f en mètres), exprimée en dioptries (δ).", "f = 0,2 m donne C = 5 δ."]],
    "pc-oeil": [["Cristallin", "Partie de l'œil qui joue le rôle d'une lentille convergente.", "Il se bombe pour regarder de près."],
      ["Rétine", "Membrane au fond de l'œil où se forme l'image.", "Comme l'écran au cinéma."],
      ["Myopie", "Défaut : on voit mal de loin ; l'image se forme avant la rétine.", "Un élève myope ne lit pas bien le tableau du fond de la classe."],
      ["Hypermétropie", "Défaut : on voit mal de près ; l'image se forme derrière la rétine.", "Difficulté à lire un livre tenu près des yeux."]],
    "pc-oxydation": [["Oxydation", "Réaction d'un corps avec le dioxygène.", "La combustion du charbon de bois."],
      ["Oxyde", "Corps formé par la réaction d'un élément avec l'oxygène.", "L'oxyde de cuivre CuO, noir."],
      ["Rouille", "Oxyde de fer formé lentement en présence d'eau et d'air.", "Un portail en fer non peint qui rouille."],
      ["Corps pur simple", "Corps formé d'une seule sorte d'atomes.", "Le fer, le cuivre, le carbone."]],
    "pc-reduction": [["Réduction", "Réaction qui enlève l'oxygène d'un oxyde.", "L'oxyde de cuivre transformé en cuivre."],
      ["Réducteur", "Corps qui capte l'oxygène d'un oxyde.", "Le carbone dans 2 CuO + C → 2 Cu + CO₂."],
      ["Oxydoréduction", "Réaction où ont lieu en même temps une oxydation et une réduction.", "Le carbone est oxydé pendant que l'oxyde de cuivre est réduit."],
      ["Haut fourneau", "Grand four industriel où l'on réduit le minerai de fer pour obtenir la fonte.", "La sidérurgie."]],
    "pc-solutions": [["pH", "Nombre de 0 à 14 qui indique si une solution est acide, neutre ou basique.", "Le jus de citron a un pH d'environ 2."],
      ["Solution acide", "Solution de pH inférieur à 7.", "Le vinaigre."],
      ["Solution basique", "Solution de pH supérieur à 7.", "L'eau de Javel, l'eau savonneuse."],
      ["Indicateur coloré", "Substance qui change de couleur selon le pH.", "Le BBT : jaune (acide), vert (neutre), bleu (basique)."]],
    "pc-puissance-elec": [["Puissance électrique", "Énergie consommée par seconde par un appareil : P = U × I, en watts.", "Un fer à repasser de 1 100 W."],
      ["Puissance nominale", "Puissance indiquée sur l'appareil pour un fonctionnement normal.", "« 220 V – 60 W » sur une ampoule."],
      ["Énergie électrique", "E = P × t : ce que l'appareil consomme pendant un temps donné.", "Une ampoule de 60 W allumée 10 h consomme 0,6 kWh."],
      ["Kilowattheure (kWh)", "Unité d'énergie utilisée sur les factures d'électricité.", "Le compteur de la CIE compte les kWh."]],
    "pc-ohm": [["Résistance", "Grandeur qui caractérise la difficulté du courant à traverser un conducteur, en ohms (Ω).", "Un résistor de 100 Ω."],
      ["Loi d'Ohm", "Pour un conducteur ohmique, U = R × I.", "R = 20 Ω et I = 0,5 A donnent U = 10 V."],
      ["Conducteur ohmique", "Dipôle qui respecte la loi d'Ohm.", "Le résistor d'un fer à repasser."],
      ["Effet Joule", "Échauffement d'un conducteur traversé par un courant.", "La résistance d'un chauffe-eau."]]
  };
