  // =========================================================
  // Corrigés de A à Z : résumé et texte argumentatif
  // =========================================================
  // Résumé : pour chaque paragraphe [rôle, idée essentielle, ce qu'on enlève, reformulation]
  const GUIDES_RESUME = {
    sport: { theme: "le sport à l'école", these: "Le sport scolaire, souvent jugé secondaire, est en réalité essentiel.", enonciation: "L'auteur parle de façon générale (« on », « l'élève ») : le résumé reste impersonnel.",
      paras: [["Thèse", "Le sport est jugé secondaire, mais il est essentiel.", "« On considère souvent… », « dans la formation des élèves »", "Jugé secondaire, le sport scolaire est pourtant essentiel."],
        ["Argument 1", "Il entretient la santé et combat l'obésité.", "les exemples (courir, sauter, football, handball), les détails (cœur, muscles, os), « dans nos villes »", "Il préserve la santé et combat l'obésité."],
        ["Argument 2", "Il aide à apprendre : attention et mémoire.", "« après une séance », « plus détendu », « les médecins affirment »", "Il améliore aussi l'attention et la mémoire."],
        ["Argument 3", "Il forme le caractère : règles, solidarité, effort.", "« dans une équipe », l'arbitre et l'adversaire, « persévérance », « à l'école comme au travail »", "De plus, il forge le respect des règles, la solidarité et l'effort."],
        ["Concession et réfutation", "Le manque de moyens n'est pas un obstacle : peu suffit.", "l'énumération « un espace dégagé, un ballon et un enseignant motivé »", "Même sans grands moyens, on peut le pratiquer."],
        ["Conclusion", "Il faut valoriser le sport, garant de réussite.", "le proverbe « un esprit sain dans un corps sain »", "Valorisons-le donc : il garantit la réussite."]],
      connecteurs: "pourtant (opposition à l'idée reçue), aussi et de plus (ajout d'arguments), même sans (concession), donc (conclusion)" },
    forets: { theme: "la protection des forêts", these: "La disparition des forêts n'est pas une fatalité : chacun peut agir.", enonciation: "L'auteur dit « nous » et « notre avenir » : on peut garder ce « nous » (« Protégeons »).",
      paras: [["Thèse", "Les forêts disparaissent, mais on peut agir.", "« en quelques dizaines d'années », « ce qui reste »", "Notre pays a perdu beaucoup de forêts, mais chacun peut agir."],
        ["Argument 1 : leur utilité", "Elles protègent la biodiversité, les sols, l'eau et favorisent les pluies.", "« dont certains n'existent nulle part ailleurs », « sans elles, les terres s'appauvrissent »", "Elles préservent la biodiversité, les sols, l'eau et les pluies utiles aux cultures."],
        ["Argument 2 : les menaces", "Plantations illégales, feux et exploitation du bois les menacent.", "« chaque année des milliers d'hectares », « dans les forêts classées »", "Pourtant, plantations illégales, feux et exploitation incontrôlée les menacent."],
        ["Argument 3 : les solutions", "Reboisement, agroforesterie et actions des élèves.", "« en 2026 », « ambitieux », le détail du cacao à l'ombre, « sensibiliser leur famille »", "Reboisement, agroforesterie et actions des élèves offrent des solutions."],
        ["Réfutation d'une objection", "Détruire la forêt ruine aussi l'agriculture.", "« Certains diront que… nourrir le pays. C'est vrai »", "Détruire la forêt ruinerait l'agriculture elle-même."],
        ["Conclusion", "Protéger les forêts, c'est protéger l'avenir.", "« Il est temps que chacun prenne ses responsabilités »", "Protégeons-la donc pour notre avenir."]],
      connecteurs: "mais (opposition), pourtant (contraste entre utilité et menaces), donc (conclusion)" }
  };

  // Texte argumentatif : rédaction complète annotée. Rôles : amorce, sujet, probleme, annonce, arg, expl, ex, trans, bilan, avis, ouverture, conc
  const GUIDES_ARGU = [
    { id: "reseaux", titre: "Discuter une opinion : les réseaux sociaux", sujet: "« Certains pensent que les réseaux sociaux sont un danger pour les élèves. » Partages-tu ce point de vue ? Tu répondras dans un développement argumenté d'une trentaine de lignes.",
      analyse: ["<b>Le thème</b> : les réseaux sociaux et les élèves (attention : on parle des <b>élèves</b>, pas de tout le monde).", "<b>La thèse proposée</b> : les réseaux sociaux sont un danger.", "<b>La consigne</b> : « Partages-tu ce point de vue ? » On peut répondre oui, non, ou <b>nuancer</b>. Le plus riche est de nuancer : montrer les dangers, puis les avantages, puis donner sa position.", "<b>Les mots-clés à garder en tête</b> : danger, élèves, réussite, sécurité."],
      idees: [["Dangers (pour la thèse)", ["perte de temps, fatigue, baisse des notes", "arnaques, usurpation d'identité, harcèlement", "fausses informations", "addiction"]], ["Avantages (contre la thèse)", ["apprendre : cours en vidéo, groupes de révision", "garder le lien avec la famille éloignée", "s'informer, créer, entreprendre"]], ["Ce qui compte (position)", ["tout dépend de l'usage", "rôle des parents et de l'école", "campagne « En ligne, tous responsables »"]]],
      plan: ["<b>Introduction</b> : amorce, rappel du sujet, question, annonce du plan.", "<b>I. Des dangers réels</b> : 1) perte de temps ; 2) arnaques et harcèlement.", "<b>II. Mais aussi des avantages</b> : 1) apprendre ; 2) rapprocher les familles.", "<b>III. Tout dépend de l'usage</b> : 1) se fixer des règles ; 2) le rôle des adultes.", "<b>Conclusion</b> : bilan, prise de position, ouverture."],
      texte: [
        [["amorce", "Aujourd'hui, presque tous les élèves possèdent un téléphone et passent chaque jour de longues heures sur WhatsApp, TikTok ou Facebook."], ["sujet", "Certains y voient un véritable danger pour leur réussite et leur sécurité."], ["probleme", "Les réseaux sociaux sont-ils vraiment une menace pour les élèves, ou peuvent-ils aussi les aider ?"], ["annonce", "Nous verrons d'abord leurs dangers réels, puis leurs avantages, avant de montrer que tout dépend de l'usage qu'on en fait."]],
        [["arg", "D'abord, les réseaux sociaux font perdre beaucoup de temps."], ["expl", "En effet, les vidéos et les messages s'enchaînent sans fin, et l'élève oublie ses leçons."], ["ex", "Par exemple, un camarade qui reste connecté jusqu'à minuit arrive fatigué en classe, et ses notes baissent."]],
        [["arg", "De plus, ils exposent les jeunes à de graves dangers."], ["expl", "En effet, des escrocs y volent des identités et des harceleurs y humilient leurs victimes."], ["ex", "Ainsi, en 2026 encore, la police ivoirienne a appelé les jeunes à un usage responsable des réseaux sociaux."]],
        [["trans", "Pourtant, il serait injuste de ne voir que ces dangers."], ["arg", "En effet, les réseaux sociaux peuvent aider à apprendre."], ["expl", "Ils donnent accès à des cours en vidéo, à des exercices et à des groupes de révision."], ["ex", "Par exemple, beaucoup d'élèves de 3e partagent leurs fiches sur WhatsApp à l'approche du BEPC."]],
        [["arg", "Par ailleurs, ils rapprochent les familles."], ["expl", "Grâce à eux, un élève peut parler chaque jour avec un parent parti travailler loin."], ["ex", "C'est le cas de nombreuses familles ivoiriennes dont un membre vit à l'étranger."]],
        [["trans", "Les réseaux sociaux ne sont donc ni bons ni mauvais en eux-mêmes."], ["arg", "En réalité, tout dépend de l'usage qu'on en fait."], ["expl", "Un élève qui limite son temps d'écran et coupe son téléphone la nuit profite des avantages sans subir les dangers."], ["ex", "Par exemple, il peut s'accorder une heure par jour, une fois ses devoirs terminés."]],
        [["arg", "Enfin, les parents et l'école ont un rôle à jouer."], ["expl", "Ils doivent apprendre aux jeunes à protéger leurs données et à vérifier les informations."], ["ex", "C'est le but de la campagne nationale « En ligne, tous responsables »."]],
        [["bilan", "En somme, les réseaux sociaux présentent de vrais dangers pour les élèves, mais ils offrent aussi de belles possibilités pour apprendre et communiquer."], ["avis", "Je pense donc qu'ils ne sont pas un danger en eux-mêmes : c'est leur mauvais usage qui l'est."], ["ouverture", "Ne faudrait-il pas enseigner le bon usage d'internet dès l'école primaire ?"]]],
      relecture: ["Chaque paragraphe commence par un alinéa et un connecteur.", "Chaque argument a son explication et son exemple.", "Les transitions relient les parties (« Pourtant… », « Les réseaux sociaux ne sont donc ni bons ni mauvais… »).", "Accords vérifiés : « les vidéos s'enchaînent », « ses notes baissent ».", "Longueur : environ 30 lignes. Pas de langage SMS, pas de registre familier."] },
    { id: "ecole", titre: "Réfuter une opinion : « L'école ne sert à rien »", sujet: "Un camarade affirme : « L'école ne sert à rien pour réussir dans la vie, beaucoup de gens riches n'ont pas fait d'études. » Réfute cette opinion dans un développement argumenté.",
      analyse: ["<b>La thèse à combattre</b> : l'école ne sert à rien pour réussir.", "<b>La consigne</b> : « Réfute » : il faut montrer que cette opinion est <b>fausse ou exagérée</b>. On ne la défend pas.", "<b>La méthode</b> : on présente d'abord la thèse adverse honnêtement (concession), puis on la combat avec des arguments solides.", "<b>L'argument du camarade</b> : « des gens riches n'ont pas fait d'études ». Il faut aussi y répondre."],
      idees: [["Ce que dit l'adversaire", ["quelques personnes ont réussi sans diplôme", "certains diplômés sont au chômage"]], ["Mes arguments de réfutation", ["l'école donne les savoirs de base (lire, compter, raisonner)", "elle ouvre l'accès aux métiers (médecin, ingénieur, enseignant…)", "elle forme le citoyen (droits, devoirs, esprit critique)", "les réussites sans école sont des exceptions"]]],
      plan: ["<b>Introduction</b> : amorce, thèse adverse, annonce de la réfutation.", "<b>I. Ce qui peut sembler vrai (concession)</b> : quelques personnes réussissent sans diplôme.", "<b>II. Mais l'école est indispensable</b> : 1) les savoirs de base ; 2) l'accès aux métiers ; 3) la formation du citoyen.", "<b>Conclusion</b> : bilan de la réfutation, ouverture."],
      texte: [
        [["amorce", "On entend parfois des jeunes dire que les études sont une perte de temps."], ["sujet", "Selon eux, l'école ne sert à rien pour réussir, puisque certaines personnes riches n'ont jamais fait d'études."], ["annonce", "Cette opinion est pourtant très exagérée, comme nous allons le montrer."]],
        [["trans", "Certes, quelques commerçants ou artistes ont réussi sans diplôme."], ["expl", "Leur courage et leur talent méritent le respect."], ["arg", "Mais ces cas restent des exceptions, et la plupart d'entre eux regrettent de ne pas avoir pu étudier davantage."]],
        [["arg", "D'abord, l'école donne les savoirs indispensables à toute réussite."], ["expl", "Savoir lire un contrat, calculer un bénéfice ou rédiger une lettre protège contre les erreurs et les escroqueries."], ["ex", "Par exemple, une commerçante qui sait tenir ses comptes voit tout de suite si elle gagne ou perd de l'argent."]],
        [["arg", "Ensuite, l'école ouvre les portes de nombreux métiers."], ["expl", "On ne devient pas médecin, ingénieur ou enseignant sans diplôme."], ["ex", "Ainsi, les infirmiers et les sages-femmes qui soignent dans nos villages ont tous étudié de longues années."]],
        [["arg", "Enfin, l'école forme le citoyen."], ["expl", "Elle apprend à connaître ses droits et ses devoirs, à vivre avec les autres et à réfléchir par soi-même."], ["ex", "C'est grâce à elle qu'un jeune peut repérer une fausse information ou comprendre l'importance du vote."]],
        [["bilan", "En définitive, si quelques personnes réussissent sans études, l'école reste le chemin le plus sûr vers la réussite professionnelle et personnelle."], ["avis", "Affirmer qu'elle ne sert à rien est donc une erreur."], ["ouverture", "La vraie question n'est-elle pas plutôt de rendre l'école accessible à tous les enfants ?"]]],
      relecture: ["La thèse adverse est présentée honnêtement avant d'être combattue (« Certes… Mais… »).", "Trois arguments de réfutation, chacun avec explication et exemple.", "La conclusion rappelle clairement que la thèse adverse est fausse.", "Connecteurs variés : certes, mais, d'abord, ensuite, enfin, en définitive."] }
  ];
  const ROLES = { amorce: ["Amorce", "#2B63B8"], sujet: ["Rappel du sujet", "#2B63B8"], probleme: ["Question posée", "#2B63B8"], annonce: ["Annonce du plan", "#2B63B8"],
    arg: ["Argument", "#E0701F"], expl: ["Explication", "#7A4FB5"], ex: ["Exemple", "#1A8F5F"], trans: ["Transition / concession", "#9A6A12"],
    bilan: ["Bilan", "#CF3F35"], avis: ["Prise de position", "#CF3F35"], ouverture: ["Ouverture", "#CF3F35"] };
  const CONNECTEURS = ["D'abord", "Ensuite", "Enfin", "De plus", "En effet", "Par exemple", "Ainsi", "Pourtant", "Par ailleurs", "Grâce à eux", "En réalité", "En somme", "En définitive", "Certes", "Mais", "donc", "pourtant", "C'est le cas", "C'est le but", "C'est grâce à elle"];
