  // =========================================================
  // Sujets d'entraînement type BEPC, avec corrigés détaillés et barème
  // (sujets originaux, construits sur le programme officiel de 3e)
  // =========================================================
  const doc = (titre, html) => `<div class="document"><span class="etiquette">${titre}</span>${html}</div>`;
  const Q = (num, enonce, points, corrige) => ({ num, enonce, points, corrige });
  const SUJETS = [
    { id: "maths-a", matiere: "maths", titre: "Mathématiques · Sujet A", duree: "2 h",
      consignes: "La calculatrice scientifique est autorisée. Soigne la rédaction : chaque résultat doit être justifié.",
      questions: [
        Q("Exercice 1", `Réponds par <b>Vrai</b> ou <b>Faux</b> en justifiant : a) ${rac("16 + 9")} = ${rac(16)} + ${rac(9)} ; b) (x − 3)² = x² − 6x + 9 ; c) le nombre 5 appartient à ]−2 ; 5] ; d) la fonction f(x) = −2x + 3 est croissante.`, 4,
          `<b>a) Faux.</b> ${rac("16 + 9")} = ${rac(25)} = 5, alors que ${rac(16)} + ${rac(9)} = 4 + 3 = 7. On ne peut pas « couper » une racine d'une somme. (1 pt)<br><b>b) Vrai.</b> Identité (a − b)² = a² − 2ab + b² avec a = x, b = 3 : x² − 6x + 9. (1 pt)<br><b>c) Vrai.</b> Le crochet « ] » après 5 est tourné vers 5 : 5 est compris. (1 pt)<br><b>d) Faux.</b> Le coefficient a = −2 est négatif : f est <b>décroissante</b>. (1 pt)`),
        Q("Exercice 2 · 1)", "On donne A = (2x − 3)² − (x + 1)². Développe et réduis A.", 1.5,
          `(2x − 3)² = 4x² − 12x + 9 et (x + 1)² = x² + 2x + 1.<br>A = 4x² − 12x + 9 − (x² + 2x + 1) = 4x² − 12x + 9 − x² − 2x − 1 = <b>3x² − 14x + 8</b>.<br><i>Piège : les parenthèses après le signe « − » changent tous les signes.</i>`),
        Q("Exercice 2 · 2)", "Factorise A.", 1.5,
          `A est de la forme a² − b² avec a = 2x − 3 et b = x + 1.<br>A = [(2x − 3) − (x + 1)] × [(2x − 3) + (x + 1)] = (2x − 3 − x − 1)(2x − 3 + x + 1) = <b>(x − 4)(3x − 2)</b>.<br>Vérification : (x − 4)(3x − 2) = 3x² − 2x − 12x + 8 = 3x² − 14x + 8 ✓.`),
        Q("Exercice 2 · 3)", "Résous l'équation A = 0.", 1,
          `On utilise la forme factorisée : (x − 4)(3x − 2) = 0. Un produit est nul si l'un des facteurs est nul :<br>x − 4 = 0 ⇔ x = 4 ; ou 3x − 2 = 0 ⇔ x = ${fr(2, 3)}.<br>Les solutions sont <b>4 et ${fr(2, 3)}</b>.`),
        Q("Exercice 2 · 4)", `Calcule A pour x = ${rac(2)}.`, 1,
          `On utilise la forme développée : A = 3 × (${rac(2)})² − 14${rac(2)} + 8 = 3 × 2 − 14${rac(2)} + 8 = <b>14 − 14${rac(2)}</b>.`),
        Q("Exercice 3 · 1)", "ABC est un triangle tel que AB = 6 cm, AC = 8 cm, BC = 10 cm. Démontre que ABC est rectangle en A.", 1.5,
          `[BC] est le plus grand côté. BC² = 10² = 100. AB² + AC² = 36 + 64 = 100.<br>Comme BC² = AB² + AC², d'après la <b>réciproque de la propriété de Pythagore</b>, le triangle ABC est rectangle en A.`),
        Q("Exercice 3 · 2)", "M est le point de [AB] tel que AM = 3 cm. La parallèle à (BC) passant par M coupe [AC] en N. Calcule AN et MN.", 2,
          `M ∈ [AB], N ∈ [AC] et (MN) // (BC) : d'après la <b>propriété de Thalès</b>, ${fr("AM", "AB")} = ${fr("AN", "AC")} = ${fr("MN", "BC")}, soit ${fr(3, 6)} = ${fr("AN", 8)} = ${fr("MN", 10)}.<br>AN = ${fr("3 × 8", 6)} = <b>4 cm</b> ; MN = ${fr("3 × 10", 6)} = <b>5 cm</b>.`),
        Q("Exercice 3 · 3)", "Calcule cos ABC, puis donne la mesure de l'angle ABC arrondie au degré.", 1.5,
          `Dans le triangle ABC rectangle en A : cos ABC = ${fr("côté adjacent", "hypoténuse")} = ${fr("AB", "BC")} = ${fr(6, 10)} = <b>0,6</b>.<br>À la calculatrice : ABC = cos⁻¹(0,6) ≈ <b>53°</b>.`),
        Q("Exercice 4 · 1)", "À Yamoussoukro, le club A fait payer 1 500 F la séance. Le club B demande un abonnement de 6 000 F, puis 1 000 F la séance. Calcule le prix de 10 séances dans chaque club.", 1,
          `Club A : 10 × 1 500 = <b>15 000 F</b>. Club B : 6 000 + 10 × 1 000 = <b>16 000 F</b>. Pour 10 séances, A est moins cher.`),
        Q("Exercice 4 · 2)", "On note x le nombre de séances. Exprime f(x), prix au club A, et g(x), prix au club B. Précise la nature de f et de g.", 1.5,
          `f(x) = <b>1 500x</b> : application <b>linéaire</b> (de la forme ax).<br>g(x) = <b>1 000x + 6 000</b> : application <b>affine</b> (de la forme ax + b).`),
        Q("Exercice 4 · 3)", "Résous f(x) = g(x) et interprète.", 1.5,
          `1 500x = 1 000x + 6 000 ⇔ 500x = 6 000 ⇔ x = <b>12</b>.<br>Pour 12 séances, les deux clubs coûtent le même prix : 18 000 F.`),
        Q("Exercice 4 · 4)", "À partir de combien de séances le club B est-il plus avantageux ?", 2,
          `B est plus avantageux si g(x) < f(x) : 1 000x + 6 000 < 1 500x ⇔ 6 000 < 500x ⇔ x > 12.<br>Donc à partir de <b>13 séances</b>, le club B est moins cher. (Vérification pour 13 : A = 19 500 F ; B = 19 000 F ✓.)`)
      ] },
    { id: "maths-b", matiere: "maths", titre: "Mathématiques · Sujet B", duree: "2 h",
      consignes: "La calculatrice scientifique est autorisée. Toutes les réponses doivent être justifiées.",
      questions: [
        Q("Exercice 1 · 1)", `Écris C = ${rac(75)} − 2${rac(12)} + ${rac(27)} sous la forme a${rac(3)}.`, 1.5,
          `${rac(75)} = ${rac("25 × 3")} = 5${rac(3)} ; ${rac(12)} = ${rac("4 × 3")} = 2${rac(3)} ; ${rac(27)} = ${rac("9 × 3")} = 3${rac(3)}.<br>C = 5${rac(3)} − 2 × 2${rac(3)} + 3${rac(3)} = (5 − 4 + 3)${rac(3)} = <b>4${rac(3)}</b>.`),
        Q("Exercice 1 · 2)", `Écris ${fr(6, rac(3))} sans radical au dénominateur.`, 1,
          `${fr(6, rac(3))} = ${fr("6 × " + rac(3), rac(3) + " × " + rac(3))} = ${fr("6" + rac(3), 3)} = <b>2${rac(3)}</b>.`),
        Q("Exercice 1 · 3)", `Sachant que 1,41 < ${rac(2)} < 1,42, encadre 3 + 2${rac(2)}.`, 1.5,
          `On multiplie par 2 (positif, l'ordre est conservé) : 2,82 < 2${rac(2)} < 2,84.<br>On ajoute 3 : <b>5,82 < 3 + 2${rac(2)} < 5,84</b>.`),
        Q("Exercice 2", "Au marché de Bouaké, 3 kg de riz et 2 kg de sucre coûtent 2 600 F ; 2 kg de riz et 3 kg de sucre coûtent 2 900 F. Calcule le prix d'un kilogramme de riz et d'un kilogramme de sucre.", 5,
          `<b>Choix des inconnues</b> (0,5 pt) : r = prix d'un kg de riz, s = prix d'un kg de sucre.<br><b>Mise en équations</b> (1 pt) : 3r + 2s = 2 600 et 2r + 3s = 2 900.<br><b>Résolution par combinaison</b> (2 pts) : on multiplie la 1re équation par 3 et la 2e par 2 : 9r + 6s = 7 800 et 4r + 6s = 5 800. On soustrait : 5r = 2 000, donc r = 400. Puis 3 × 400 + 2s = 2 600 ⇔ 2s = 1 400 ⇔ s = 700.<br><b>Vérification</b> (0,5 pt) : 2 × 400 + 3 × 700 = 800 + 2 100 = 2 900 ✓.<br><b>Réponse</b> (1 pt) : le riz coûte <b>400 F le kg</b> et le sucre <b>700 F le kg</b>.`),
        Q("Exercice 3 · 1)", "Dans un repère orthonormé, A(−1 ; 2), B(3 ; 4) et C(5 ; 0). Calcule les coordonnées de AB⃗ et de BC⃗.", 1,
          `AB⃗ (3 − (−1) ; 4 − 2) = <b>(4 ; 2)</b>. BC⃗ (5 − 3 ; 0 − 4) = <b>(2 ; −4)</b>.`),
        Q("Exercice 3 · 2)", "Calcule AB et BC. Que peux-tu dire du triangle ABC ?", 1.5,
          `AB = ${rac("4² + 2²")} = ${rac(20)} = 2${rac(5)} ; BC = ${rac("2² + (−4)²")} = ${rac(20)} = 2${rac(5)}.<br>AB = BC : le triangle ABC est <b>isocèle en B</b>.`),
        Q("Exercice 3 · 3)", "Détermine une équation de la droite (AB).", 1.5,
          `Coefficient directeur : a = ${fr("4 − 2", "3 − (−1)")} = ${fr(2, 4)} = ${fr(1, 2)}. Avec A : 2 = ${fr(1, 2)} × (−1) + b ⇔ b = ${fr(5, 2)}.<br>Équation : <b>y = ${fr(1, 2)}x + ${fr(5, 2)}</b>. Vérification avec B : ${fr(3, 2)} + ${fr(5, 2)} = 4 ✓.`),
        Q("Exercice 3 · 4)", "Détermine les coordonnées du point D tel que ABCD soit un parallélogramme.", 1,
          `ABCD parallélogramme ⇔ AD⃗ = BC⃗. Donc x<sub>D</sub> + 1 = 2 et y<sub>D</sub> − 2 = −4, soit <b>D(1 ; −2)</b>.`),
        Q("Exercice 4 · 1)", "Notes de 25 élèves : 6 (2 élèves), 8 (5), 10 (8), 12 (6), 14 (3), 16 (1). Donne le mode et calcule la moyenne.", 2,
          `<b>Mode</b> : la note la plus fréquente, <b>10</b> (8 élèves).<br><b>Moyenne</b> : ${fr("6×2 + 8×5 + 10×8 + 12×6 + 14×3 + 16×1", 25)} = ${fr("12 + 40 + 80 + 72 + 42 + 16", 25)} = ${fr(262, 25)} = <b>10,48</b>.`),
        Q("Exercice 4 · 2)", "Dresse le tableau des effectifs cumulés croissants et détermine la médiane.", 2,
          `Effectifs cumulés croissants : 6 → 2 ; 8 → 7 ; 10 → 15 ; 12 → 21 ; 14 → 24 ; 16 → 25.<br>25 valeurs : la médiane est la 13e valeur. Or 7 < 13 ≤ 15 : la 13e valeur est 10. <b>Médiane = 10</b>.`),
        Q("Exercice 4 · 3)", "Quel pourcentage des élèves a au moins 12 ? Quel angle représente la note 10 dans un diagramme circulaire ?", 2,
          `Au moins 12 : 6 + 3 + 1 = 10 élèves, soit ${fr(10, 25)} × 100 = <b>40 %</b>.<br>Angle pour la note 10 : ${fr(8, 25)} × 360° = <b>115,2°</b>.`)
      ] },
    { id: "pc-a", matiere: "pc", titre: "Physique-Chimie · Sujet A", duree: "2 h",
      consignes: "On prendra g = 10 N/kg. Écris toujours la formule, puis l'application numérique, puis le résultat avec son unité.",
      questions: [
        Q("Chimie · 1", "Lors d'une électrolyse de l'eau, on recueille 15 cm³ de dihydrogène. a) À quelle électrode ? b) Quel volume de dioxygène obtient-on ? c) Écris l'équation-bilan. d) Comment identifier le dioxygène ?", 4,
          `a) Le dihydrogène se dégage à la <b>cathode</b> (électrode reliée à la borne −). (1 pt)<br>b) V(O₂) = V(H₂) ÷ 2 = 15 ÷ 2 = <b>7,5 cm³</b>. (1 pt)<br>c) <b>2 H₂O → 2 H₂ + O₂</b>. (1 pt)<br>d) Il <b>rallume une bûchette incandescente</b>. (1 pt)`),
        Q("Chimie · 2", "Le butane C₄H₁₀ brûle complètement dans le dioxygène. a) Nomme les produits. b) Écris et équilibre l'équation. c) Comment met-on en évidence le CO₂ ? d) Quel danger présente une combustion incomplète ?", 4,
          `a) Dioxyde de carbone (CO₂) et eau (H₂O). (1 pt)<br>b) <b>2 C₄H₁₀ + 13 O₂ → 8 CO₂ + 10 H₂O</b>. Vérification : C : 8 = 8 ; H : 20 = 20 ; O : 26 = 16 + 10 ✓. (1,5 pt)<br>c) Le CO₂ <b>trouble l'eau de chaux</b>. (0,5 pt)<br>d) Elle produit du <b>monoxyde de carbone (CO)</b>, gaz toxique et mortel sans odeur, et de la suie. Il faut aérer. (1 pt)`),
        Q("Physique · 1", "Un ouvrier soulève un sac de ciment de 50 kg à une hauteur de 3 m en 10 s. a) Calcule le poids du sac. b) Calcule le travail effectué. c) Calcule la puissance. d) Quelle est l'énergie potentielle du sac en haut (sol = référence) ?", 5,
          `a) P = m × g = 50 × 10 = <b>500 N</b>. (1 pt)<br>b) W = F × h = 500 × 3 = <b>1 500 J</b>. (1,5 pt)<br>c) P = W ÷ t = 1 500 ÷ 10 = <b>150 W</b>. (1,5 pt)<br>d) Ep = m × g × h = 50 × 10 × 3 = <b>1 500 J</b> : le travail fourni est stocké sous forme d'énergie potentielle. (1 pt)`),
        Q("Physique · 2", "Un fer à repasser porte l'indication « 220 V – 1 100 W ». a) Que signifient ces indications ? b) Calcule l'intensité du courant. c) Calcule l'énergie consommée en 30 min, en kWh. d) Calcule le coût si le kWh coûte 80 F. e) Calcule la résistance de son élément chauffant.", 5,
          `a) 220 V : tension nominale ; 1 100 W : puissance nominale. (1 pt)<br>b) P = U × I ⇒ I = ${fr("P", "U")} = ${fr("1 100", 220)} = <b>5 A</b>. (1 pt)<br>c) E = P × t = 1,1 kW × 0,5 h = <b>0,55 kWh</b>. (1 pt)<br>d) Coût = 0,55 × 80 = <b>44 F</b>. (1 pt)<br>e) U = R × I ⇒ R = ${fr("U", "I")} = ${fr(220, 5)} = <b>44 Ω</b>. (1 pt)`),
        Q("Physique · 3", "Une lentille convergente a une distance focale de 5 cm. a) Calcule sa vergence. b) Quels défauts de l'œil corrige-t-on avec une lentille convergente ?", 2,
          `a) f = 5 cm = 0,05 m ; C = ${fr(1, "f")} = ${fr(1, "0,05")} = <b>20 δ</b>. (1 pt)<br>b) L'<b>hypermétropie</b> et la <b>presbytie</b> (la myopie se corrige avec une lentille divergente). (1 pt)`)
      ] },
    { id: "svt-a", matiere: "svt", titre: "SVT · Sujet A", duree: "2 h",
      consignes: "Réponds avec des phrases complètes. Pour l'exploitation de documents : décris d'abord, puis interprète, puis conclus.",
      document: doc("Document : expérience sur la digestion de l'amidon", `<table class="vocab"><tr><td><b>Tube</b></td><td><b>Contenu (15 min)</b></td><td><b>Eau iodée</b></td><td><b>Fehling à chaud</b></td></tr>
        <tr><td>1</td><td>Empois d'amidon + eau, 37 °C</td><td>bleu-violet</td><td>pas de précipité</td></tr>
        <tr><td>2</td><td>Empois d'amidon + salive, 37 °C</td><td>pas de coloration</td><td>précipité rouge brique</td></tr>
        <tr><td>3</td><td>Empois + salive bouillie, 37 °C</td><td>bleu-violet</td><td>pas de précipité</td></tr>
        <tr><td>4</td><td>Empois + salive, 0 °C</td><td>bleu-violet</td><td>pas de précipité</td></tr></table>`),
      questions: [
        Q("Restitution · 1", "Définis : nutriment ; transfusion sanguine ; érosion.", 3,
          `<b>Nutriment</b> : substance simple issue de la digestion, qui peut passer dans le sang (glucose, acides aminés…). (1 pt)<br><b>Transfusion sanguine</b> : injection de sang (ou d'un de ses éléments) d'un donneur à un receveur compatible. (1 pt)<br><b>Érosion</b> : arrachement et transport des particules du sol par l'eau ou le vent. (1 pt)`),
        Q("Restitution · 2", "Une personne du groupe A peut recevoir du sang de quels groupes (système ABO) ? Justifie.", 2,
          `Son plasma contient des anticorps <b>anti-B</b>. Elle peut recevoir du sang <b>A</b> et <b>O</b>, dont les hématies ne portent pas l'antigène B. (1 pt pour les groupes, 1 pt pour la justification)`),
        Q("Restitution · 3", "Cite les trois modes de transmission du VIH.", 3,
          `1) La voie <b>sexuelle</b> (rapports non protégés). 2) La voie <b>sanguine</b> (objets souillés, sang contaminé). 3) La transmission de la <b>mère à l'enfant</b> (grossesse, accouchement, allaitement). (1 pt chacun)`),
        Q("Documents · 1", "Analyse les résultats des tubes 1 et 2.", 3,
          `<b>Tube 1</b> (sans salive) : l'eau iodée reste bleu-violet → l'amidon est toujours là ; Fehling négatif → pas de sucre réducteur. (1,5 pt)<br><b>Tube 2</b> (avec salive à 37 °C) : l'eau iodée ne colore plus → l'amidon a disparu ; Fehling rouge brique → un sucre réducteur (maltose) est apparu. (1,5 pt)`),
        Q("Documents · 2", "Interprète ces résultats : que contient la salive ?", 3,
          `La salive a transformé l'amidon en sucre réducteur. Elle contient donc une <b>enzyme</b> : l'<b>amylase salivaire</b>, qui digère l'amidon en maltose. C'est une digestion <b>chimique</b>. (3 pts)`),
        Q("Documents · 3", "Que montrent les tubes 3 et 4 sur les conditions d'action de cette enzyme ?", 4,
          `<b>Tube 3</b> : la salive bouillie n'agit plus → l'enzyme est <b>détruite par la chaleur</b>. (2 pts)<br><b>Tube 4</b> : à 0 °C, l'amidon n'est pas digéré → l'enzyme est <b>inactive au froid</b>. Elle agit le mieux vers <b>37 °C</b>, la température du corps. (2 pts)`),
        Q("Conclusion", "Rédige une conclusion générale.", 2,
          `La salive contient une enzyme, l'amylase, qui transforme l'amidon en maltose. Cette enzyme n'agit qu'à une température proche de 37 °C et elle est détruite par l'ébullition : la digestion de l'amidon commence dans la bouche. (2 pts)`)
      ] },
    { id: "hg-a", matiere: "hg", titre: "Histoire-Géographie · Sujet A", duree: "2 h",
      consignes: "Réponds aux questions à partir des documents et de tes connaissances.",
      document: doc("Document 1 (Histoire)", `<p style="font-style:italic">« Article premier : Le travail forcé ou obligatoire est interdit de façon absolue dans les territoires d'outre-mer. »</p><p style="font-size:14px">Loi n° 46-645 du 11 avril 1946, dite loi Houphouët-Boigny, votée par l'Assemblée nationale française.</p>`) +
        doc("Document 2 (Géographie)", `<p style="font-style:italic">« Premier producteur mondial de cacao, la Côte d'Ivoire tire de cette culture une grande part de ses recettes d'exportation. Le 1er septembre 2026, le prix garanti au planteur a été fixé à 1 200 F CFA le kilogramme, contre 2 800 F CFA la campagne précédente, à cause de la baisse des cours mondiaux. »</p><p style="font-size:14px">D'après la presse ivoirienne, septembre 2026.</p>`),
      questions: [
        Q("Histoire · 1", "Présente le document 1 (nature, auteur, date).", 2,
          `Il s'agit d'un <b>texte de loi</b> (extrait) : la loi du <b>11 avril 1946</b>, votée par l'Assemblée nationale française à l'initiative du député <b>Félix Houphouët-Boigny</b>. (2 pts)`),
        Q("Histoire · 2", "Explique l'expression « travail forcé ».", 2,
          `C'est le travail <b>obligatoire et non (ou très peu) payé</b> imposé aux Africains par l'administration coloniale : construction de routes et de chemins de fer, travail dans les plantations des colons, portage. (2 pts)`),
        Q("Histoire · 3", "Quelles furent les conséquences de cette loi pour Houphouët-Boigny et pour la lutte anticoloniale ?", 3,
          `Elle rend Houphouët-Boigny très <b>populaire</b> ; elle renforce le <b>PDCI</b> (créé en avril 1946) et le <b>RDA</b> (octobre 1946) ; elle accélère la mobilisation des Africains pour leurs droits. (3 pts)`),
        Q("Histoire · 4", "Cite trois grandes étapes qui ont conduit à l'indépendance après 1946.", 3,
          `1956 : la <b>loi-cadre Defferre</b> (autonomie interne) ; 28 septembre 1958 : <b>référendum</b> et proclamation de la République le 4 décembre 1958 ; <b>7 août 1960</b> : indépendance. (1 pt par étape)`),
        Q("Géographie · 1", "À quel secteur d'activité appartient la culture du cacao ? Justifie.", 2,
          `Au <b>secteur primaire</b>, car il s'agit d'exploiter directement la nature (agriculture). (2 pts)`),
        Q("Géographie · 2", "Cite deux atouts naturels qui favorisent la culture du cacao en Côte d'Ivoire.", 2,
          `Le <b>climat équatorial</b> chaud et humide du sud ; les <b>sols forestiers fertiles</b> (1 pt chacun ; on accepte aussi l'abondance des pluies).`),
        Q("Géographie · 3", "Quelle est la conséquence de la baisse du prix pour les planteurs ? Quel problème du développement ivoirien ce document illustre-t-il ?", 3,
          `Les <b>revenus des planteurs baissent fortement</b> (moins d'argent pour la scolarité, la santé, l'entretien des plantations). Le document illustre la <b>dépendance</b> de l'économie ivoirienne aux cours mondiaux des matières premières. (3 pts)`),
        Q("Géographie · 4", "Propose deux solutions à ce problème.", 3,
          `<b>Transformer le cacao sur place</b> (chocolaterie, beurre de cacao) pour garder plus de valeur ; <b>diversifier</b> les cultures et les activités (anacarde, hévéa, vivriers, industrie, services). (1,5 pt chacune)`)
      ] },
    { id: "fr-resume", matiere: "francais", titre: "Français · Résumé de texte argumentatif", duree: "2 h",
      consignes: "Résume ce texte au quart de sa longueur : le texte compte 267 mots, ton résumé doit donc faire environ 67 mots (entre 60 et 74 mots avec la marge de 10 %). Respecte l'ordre des idées et le système d'énonciation. Indique le nombre de mots à la fin.",
      document: doc("Texte (environ 300 mots)", `<p>Aujourd'hui, beaucoup de jeunes passent plus de temps devant leur téléphone que devant leurs livres. Pourtant, la lecture reste irremplaçable. Nous devons donc réapprendre à lire.</p><p>D'abord, la lecture enrichit notre langue. En lisant, nous découvrons des mots nouveaux, des tournures de phrases variées et une orthographe correcte. L'élève qui lit régulièrement écrit mieux et s'exprime plus facilement, à l'oral comme à l'écrit. Les meilleurs résultats aux examens appartiennent souvent à ceux qui lisent.</p><p>Ensuite, lire nous ouvre au monde. Un roman nous fait voyager dans d'autres pays et d'autres époques ; un journal nous informe de ce qui se passe autour de nous. Sans quitter notre quartier, nous rencontrons d'autres cultures et d'autres façons de penser. La lecture développe ainsi notre esprit critique et notre tolérance.</p><p>Enfin, la lecture est un loisir qui apaise. Dans un monde bruyant où les écrans nous sollicitent sans cesse, un livre nous offre un moment de calme et de concentration. Il nous apprend la patience, alors que les vidéos courtes nous habituent à tout vouloir tout de suite.</p><p>Certes, les livres coûtent cher et les bibliothèques sont rares. Mais on peut échanger des livres entre amis, lire sur son téléphone des ouvrages gratuits ou fréquenter le centre culturel de sa ville. Le problème n'est donc pas tant le manque de livres que le manque d'habitude.</p><p>Il appartient ainsi aux parents, aux enseignants et aux jeunes eux-mêmes de redonner à la lecture la place qu'elle mérite. Une nation qui lit est une nation qui progresse.</p>`),
      questions: [
        Q("1 · Comprendre", "Dégage le thème, la thèse et le plan du texte (idées essentielles, dans l'ordre).", 4,
          `<b>Thème</b> : la lecture chez les jeunes. <b>Thèse</b> : la lecture reste irremplaçable, il faut réapprendre à lire.<br><b>Idées dans l'ordre</b> : 1) la lecture enrichit la langue (vocabulaire, orthographe, expression, réussite) ; 2) elle ouvre au monde (voyages, informations, cultures, esprit critique) ; 3) elle apaise et apprend la patience face aux écrans ; 4) objection : les livres sont chers, mais on peut échanger, lire gratuitement, aller au centre culturel ; 5) conclusion : parents, enseignants et jeunes doivent redonner sa place à la lecture.`),
        Q("2 · Résumer", "Rédige ton résumé (environ 67 mots, entre 60 et 74).", 16,
          `<b>Résumé modèle (68 mots)</b> :<br><span style="font-style:italic">« Bien que les jeunes préfèrent leur téléphone, la lecture demeure indispensable. Elle améliore notre vocabulaire, notre orthographe et notre expression, gages de réussite. Elle nous fait découvrir d'autres pays et d'autres cultures, développant notre esprit critique. Elle nous apporte aussi calme et patience face aux écrans. Si les livres sont chers, on peut les échanger ou les lire gratuitement. Réhabilitons donc la lecture, source de progrès. »</span><br><br><b>Grille de correction</b> : fidélité aux idées et à leur ordre (8 pts) · reformulation personnelle, sans recopier (3 pts) · enchaînement logique avec des connecteurs (2 pts) · respect du nombre de mots (1 pt) · orthographe et syntaxe (2 pts).<br><i>Pièges : ne pas écrire « l'auteur dit que », ne pas donner son avis, ne pas recopier des phrases entières, garder le « nous » du texte.</i>`)
      ] },
    { id: "fr-redaction", matiere: "francais", titre: "Français · Rédaction (texte argumentatif)", duree: "2 h",
      consignes: "Sujet : « Certains pensent que les réseaux sociaux sont un danger pour les élèves. » Partages-tu ce point de vue ? Tu répondras dans un développement argumenté d'une trentaine de lignes, en t'appuyant sur des exemples précis.",
      questions: [
        Q("1 · Comprendre le sujet", "Identifie le thème, la thèse proposée et ce que l'on te demande.", 3,
          `<b>Thème</b> : les réseaux sociaux et les élèves. <b>Thèse</b> : ils sont un danger. <b>Consigne</b> : dire si tu partages ce point de vue et le justifier ; on attend une réponse <b>nuancée</b> (dangers réels, mais aussi avantages et conditions d'un bon usage).`),
        Q("2 · Faire le plan", "Rédige le plan détaillé de ta rédaction.", 5,
          `<b>Introduction</b> : les réseaux sociaux occupent une grande place dans la vie des jeunes ; la question ; annonce du plan.<br><b>I. Des dangers réels</b> : 1) perte de temps et baisse des résultats (nuits sur le téléphone) ; 2) harcèlement, arnaques, usurpation d'identité ; 3) fausses informations.<br><b>II. Mais aussi des avantages</b> : 1) apprendre (tutoriels, cours, révisions en groupe) ; 2) communiquer avec la famille éloignée ; 3) s'informer, créer, entreprendre.<br><b>III. Tout dépend de l'usage</b> : limiter le temps d'écran, protéger ses données, vérifier les informations, accompagnement des parents ; la loi punit les abus.<br><b>Conclusion</b> : bilan nuancé + ouverture (campagne « En ligne, tous responsables »).`),
        Q("3 · Rédiger", "Rédige ton texte complet.", 12,
          `<b>Exemple de début d'introduction</b> : <i>« Aujourd'hui, presque tous les élèves possèdent un téléphone et passent des heures sur les réseaux sociaux. Certains y voient un grand danger pour leur réussite. Qu'en est-il vraiment ? Nous verrons d'abord les dangers réels de ces réseaux, puis leurs avantages, avant de montrer que tout dépend de l'usage qu'on en fait. »</i><br><b>Exemple de paragraphe</b> : <i>« D'abord, les réseaux sociaux font perdre beaucoup de temps. En effet, les vidéos s'enchaînent sans fin et l'élève oublie ses leçons. Par exemple, un camarade qui reste connecté jusqu'à minuit arrive fatigué en classe et ses notes baissent. »</i><br><br><b>Grille de correction</b> : respect du sujet et de la consigne (2 pts) · introduction complète (2 pts) · qualité des arguments et des exemples (4 pts) · organisation et connecteurs logiques (2 pts) · conclusion (1 pt) · langue : orthographe, syntaxe, vocabulaire (3 pts, retirés en cas de nombreuses fautes).`)
      ] },
    { id: "en-a", matiere: "anglais", titre: "Anglais · Sujet A", duree: "2 h",
      consignes: "Read the text carefully, then answer the questions.",
      document: doc("Text", `<p lang="en">Kouadio is sixteen and lives in Yamoussoukro. Last year, he failed his BEPC because he spent too much time on his phone. His parents were sad, but they did not punish him. Instead, his father helped him to make a timetable. Now Kouadio studies every evening from seven to nine, and he only uses his phone on Saturdays. He has also joined a study group with three classmates. They meet at the library on Sundays and explain lessons to each other. His English teacher says he has made great progress. Kouadio is confident: he thinks he will pass his exam this year, and he wants to become a nurse.</p>`),
      questions: [
        Q("A · True or false", "Say if these statements are true or false and justify with the text: a) Kouadio lives in Abidjan. b) His parents punished him. c) He studies every evening. d) His study group meets at the library.", 4,
          `a) <b>False</b> : « lives in Yamoussoukro ». b) <b>False</b> : « they did not punish him ». c) <b>True</b> : « studies every evening from seven to nine ». d) <b>True</b> : « They meet at the library on Sundays ». (1 pt each: 0,5 for true/false, 0,5 for the justification)`),
        Q("B · Questions", "Answer: a) Why did Kouadio fail his BEPC? b) How did his father help him? c) When does he use his phone now? d) What does he want to become?", 4,
          `a) He failed because <b>he spent too much time on his phone</b>. b) His father <b>helped him to make a timetable</b>. c) He uses it <b>only on Saturdays</b>. d) He wants to <b>become a nurse</b>. (1 pt each; full sentences expected)`),
        Q("C · Vocabulary", "Find in the text words meaning: a) échoué ; b) emploi du temps ; c) camarades de classe ; d) sûr de lui.", 2,
          `a) <b>failed</b> ; b) <b>timetable</b> ; c) <b>classmates</b> ; d) <b>confident</b>. (0,5 pt each)`),
        Q("D · Language", "a) Put in the past simple: « He studies every evening. » b) Complete: « If he works hard, he ___ (pass). » c) Ask the question: « He meets his friends on Sundays. » (When…?) d) Passive: « His father made a timetable. »", 4,
          `a) He <b>studied</b> every evening. b) If he works hard, he <b>will pass</b>. c) <b>When does he meet his friends?</b> d) <b>A timetable was made by his father.</b> (1 pt each)`),
        Q("E · Writing", "In about 8 lines, write a letter to a friend to give him three pieces of advice to prepare for the BEPC.", 6,
          `<b>Model</b> : <i>Dear Awa, I hope you are fine. The BEPC is coming, so here is my advice. First, you should make a timetable and study every day, not only the week before the exam. Second, you mustn't stay on your phone at night: sleep is important. Finally, you could join a study group, because explaining lessons to friends helps you to remember them. I'm sure you will pass! Best wishes, Adriel.</i><br><b>Grille</b> : letter form: greeting, closing (1 pt) · three pieces of advice with should / must / could (3 pts) · correct English (2 pts).`)
      ] },
    { id: "edhc-a", matiere: "edhc", titre: "EDHC · Sujet A", duree: "2 h",
      consignes: "Lis la situation, puis réponds aux questions.",
      document: doc("Situation", `<p>Dans le quartier de Konan, l'unique borne-fontaine tombe souvent en panne. Chaque matin, de longues files se forment et des disputes éclatent. Certains jeunes cassent le robinet par colère, d'autres laissent l'eau couler. Le chef de quartier veut organiser une réunion pour ramener le calme.</p>`),
      questions: [
        Q("1", "Identifie deux problèmes présents dans cette situation.", 4,
          `1) Des <b>conflits</b> autour de l'eau qui menacent la <b>paix sociale</b>. 2) La <b>dégradation d'un bien public</b> (robinet cassé) et le <b>gaspillage</b> de l'eau. (2 pts chacun)`),
        Q("2", "Pourquoi l'eau et la borne-fontaine doivent-elles être protégées ?", 4,
          `La borne-fontaine est un <b>bien public</b> payé avec l'argent de tous et utile à tous. L'eau est une ressource <b>rare et vitale</b> : la gaspiller prive les autres. (2 pts + 2 pts)`),
        Q("3", "Propose trois comportements responsables que les habitants devraient adopter.", 6,
          `1) Respecter les <b>tours</b> et <b>dialoguer</b> au lieu de se disputer. 2) Ne pas <b>dégrader</b> la borne ; signaler les pannes à la SODECI ou à la mairie. 3) <b>Fermer le robinet</b> après usage et récupérer l'eau de pluie pour le nettoyage. (2 pts chacun)`),
        Q("4", "Si tu participais à la réunion, quel message donnerais-tu aux jeunes ? (5 à 6 lignes)", 6,
          `<b>Exemple</b> : <i>« Chers amis, casser le robinet ne règle rien : nous serons tous privés d'eau plus longtemps. Cette borne appartient à tout le quartier. Organisons plutôt des tours de passage, surveillons ensemble la borne et signalons vite les pannes. L'eau est précieuse : ne la gaspillons pas. Restons unis et calmes : la paix du quartier dépend de chacun de nous. »</i><br><b>Grille</b> : idée de respect du bien public (2 pts) · appel au dialogue et à la paix (2 pts) · propositions concrètes (2 pts).`)
      ] },
    { id: "es-a", matiere: "espagnol", titre: "Espagnol · Sujet A", duree: "2 h",
      consignes: "Lee el texto y contesta a las preguntas.",
      document: doc("Texto", `<p lang="es">Me llamo Aya y tengo catorce años. Vivo en Bouaké con mis padres y mi hermano pequeño. Por la mañana voy al colegio en bicicleta. Me gustan mucho las matemáticas, pero no me gusta la historia. Por la tarde ayudo a mi madre en el mercado: vendemos frutas y verduras. El año pasado fui a Abiyán con mi tío y visité el puerto. El año próximo voy a estudiar en un liceo de Abiyán porque quiero ser ingeniera.</p>`),
      questions: [
        Q("1 · Comprensión", "Contesta: a) ¿Cuántos años tiene Aya? b) ¿Dónde vive? c) ¿Qué asignatura le gusta? d) ¿Qué hace por la tarde?", 8,
          `a) Aya <b>tiene catorce años</b>. b) Vive <b>en Bouaké</b>. c) Le gustan <b>las matemáticas</b>. d) Por la tarde <b>ayuda a su madre en el mercado</b>. (2 pts cada una, con frases completas)`),
        Q("2 · Gramática", "a) Conjuga en presente: yo (tener), nosotros (vivir). b) Pon en pasado: « Voy a Abiyán. » c) ¿Gusta o gustan? « Me ___ las frutas. »", 6,
          `a) yo <b>tengo</b>, nosotros <b>vivimos</b> (2 pts). b) <b>Fui a Abiyán.</b> (2 pts) c) Me <b>gustan</b> las frutas (pluriel) (2 pts).`),
        Q("3 · Expresión escrita", "Preséntate en 4 o 5 frases (nombre, edad, ciudad, gustos, proyecto).", 6,
          `<b>Modelo</b> : <i>« Me llamo Adriel y tengo quince años. Vivo en Costa de Marfil con mi familia. Me gusta el fútbol y me encantan las matemáticas. Por la tarde estudio con mis amigos. En el futuro quiero ser ingeniero. »</i><br><b>Grille</b> : contenu (2 pts) · conjugaison correcte (2 pts) · vocabulaire et orthographe (2 pts).`)
      ] }
  ];
